### ISSUE TITLE
Time shift on the output file

### ISSUE THREAD

**Issue by EricLefe** [MontrealCorpusTools/Montreal-Forced-Aligner#100]
Hello.
I'm trying to align a Turkish corpus and I'm facing a shift right problem on the alignment after more or less one minute of audios. It start as a very small shift on the alignment and then accumulates  to an extend in which the alignment is completely incorrect. My audios are on average 5min long. I'm using the pretrained acoustic model that you provide, a pronunciation lexicon generated from my data with your g2p model. I already tried to change the beam as it's written on the documentation but it doesn't change much. Do you have any idea where it might comes from? Thank you.

**Comment by William-N-Havard** [comment]
Same problem here!

**Comment by mzboito** [comment]
Same problem happens when I try to align Portuguese.

**Comment by mmcauliffe** [comment]
Would it be possible for anyone experiencing this issue to send me an example input/output (michael.e.mcauliffe@gmail.com) that's having this issue so I can duplicate it?
