### ISSUE TITLE
mfa_validate_dataset exists or no?

### ISSUE THREAD

**Issue by Kedersha** [MontrealCorpusTools/Montreal-Forced-Aligner#102]
Hi! I reinstalled the aligner yesterday because I'm having some issues aligning data (hopefully won't need to create an actual Issue to deal with that though), and I noticed [the docs](https://montreal-forced-aligner.readthedocs.io/en/latest/data_validation.html) allude to a tool that will help validate datasets (bin/mfa_validate_dataset), but it doesn't seem to exist. Should it?

Thanks!

**Comment by mmcauliffe** [comment]
It depends on the version of MFA installed, if you're on v1.0 it does not exist, it's only a tool for v1.1 and above.
