### ISSUE TITLE
Cannot use pretrained models with the latest release

### ISSUE THREAD

**Issue by sailordiary** [MontrealCorpusTools/Montreal-Forced-Aligner#110]
The program only detects a pretrained English model although I placed other zip packages in the pretrained models folder.  Problem exists in the latest 1.0.1 release but not 1.1.0-Beta2.

**Comment by zzkzzk1996** [comment]
Try to check whether you put an acoustic model or a G2P model into your pre-trained models folder. They are two different things.

**Comment by sailordiary** [comment]
I can confirm I put in the acoustic model because the previous release did not have this problem.  Also interestingly even if I delete the English model that comes with the release, the software still detects English as available.

**Comment by zzkzzk1996** [comment]
Oh, OK, I tried 1.0.1 version before, but I've not met any problem like you. Now I just use 1.1.0-Beta2.

**Comment by mmcauliffe** [comment]
Right, version 1.0.1 doesn't scan the pre trained folder.  You'd have to use the full path to model (i.e. `/path/to/montreal-forced-aligner/pretrained_models/language.zip`).
