### ISSUE TITLE
Is there available pronunciation dictionaries for Chinese?

### ISSUE THREAD

**Issue by pchao6** [MontrealCorpusTools/Montreal-Forced-Aligner#115]
Hi, is there available pronunciation dictionaries for Chinese?

**Comment by xiangwan** [comment]
https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html

**Comment by pchao6** [comment]
@xiangwan There are only pronunciation dictionaries for English, French and German but not for Chinese.

**Comment by mmcauliffe** [comment]
Right, there are no full pronunciation dictionaries for Chinese, but you can generate your own using the G2P models and a list of words, either in pinyin or Chinese characters (though the pinyin is definitely more accurate).

**Comment by pchao6** [comment]
@mmcauliffe Got it, thanks

**Comment by leijue222** [comment]
Mandarin is Chinese?

**Comment by leijue222** [comment]
> @xiangwan只有英语，法语和德语的发音词典，而中文没有。

You can try [this](https://github.com/Jackiexiao/MTTS/blob/master/misc/mandarin-for-montreal-forced-aligner-pre-trained-model.lexicon) to see if it works.
