### ISSUE TITLE
Unable to Save Output Model

### ISSUE THREAD

**Issue by cmitch** [MontrealCorpusTools/Montreal-Forced-Aligner#123]
I've been trying to save an output model generated by the MFA using the "-o" flag. However, I keep getting errors relating to some missing file. I tested this output flag on example 2 in the docs  (https://montreal-forced-aligner.readthedocs.io/en/latest/example.html but with the "-o" option), I get the same error:

```
Traceback (most recent call last):

  File "aligner/command_line/train_and_align.py", line 131, in <module>

  File "aligner/command_line/train_and_align.py", line 73, in align_corpus

  File "aligner/aligner/trainable.py", line 61, in save

  File "aligner/trainers/base.py", line 295, in save

  File "os.py", line 220, in makedirs

FileNotFoundError: [Errno 2] No such file or directory: ''

[73344] Failed to execute script train_and_align
```

**Comment by mmcauliffe** [comment]
What's the exact command that you're running for it?  It looks like you might have just `-o` in there while it expects to take a path to save the model like `-o /path/to/save/model.zip`.

**Comment by cmitch** [comment]
With the different file names to match what I downloaded from the docs:
bin/mfa_train_and_align path/to/examples/CH  path/to/examples/chinese_dict.txt examples/aligned_output -o model.zip

Running bin/mfa_train_and_align path/to/examples/CH  path/to/examples/chinese_dict.txt examples/aligned_output works

Both cases say there were 2 segments/files not aligned, if that makes any difference

**Comment by mmcauliffe** [comment]
Could you try it with an absolute path and see if that makes a difference, i.e. `-o ~/Documents/model.zip`?  There's some code that looks like it assumes a fully specified path rather than a relative one.

**Comment by cmitch** [comment]
That worked, thanks
