### ISSUE TITLE
MacOS Update Blocking the Running of MFA

### ISSUE THREAD

**Issue by cmitch** [MontrealCorpusTools/Montreal-Forced-Aligner#126]
I recently upgraded to macOS Catalina, but now running the MFA produces errors in the following format:
`“libkaldi-util.dylib” cannot be opened because the developer cannot be verified.`

Originally this was shown for the top level function `mfa_train_and_align`, but I followed some work arounds to get past this (https://github.com/hashicorp/terraform/issues/23033). However, I keep getting errors like the one above but for libraries and files within the MFA, and even once I approve them I'm also getting some of the following types of errors:
`macOS cannot verify the developer of “libkaldi-tree.dylib”. Are you sure you want to open it?
`

**Comment by mmcauliffe** [comment]
I remember there being some setting you could configure in previous versions that allow all downloaded programs to run, is there anything like that in this version?  If there's no way to disable that and apple's requiring everyone buy into their developer program, I don't know there's anything I can do to help.  Maybe make a single larger application would get around it throwing errors with every dylib.

**Comment by cmitch** [comment]
As that other github issue I linked mentioned, Catalina removed the option. That issue did list a sudo command that was supposed to do that, but after running it I am still getting the same errors, but for other code (assumedly within MFA) like "fstcompile". I can try to make a Mac app that encapsulates MFA, but I'm not sure if just encapsulating it would fully resolve the issue

**Comment by cmitch** [comment]
As an update, I checked that thread I linked before and found a solution: in System Preferences > Security and Privacy > Privacy > Developer Tools, you can enable the terminal to set the terminal to run unidentified software. This fixed the issue for me. Link to post about it: https://github.com/hashicorp/terraform/issues/23033#issuecomment-543507812

**Comment by christianbrodbeck** [comment]
I spent some time until finding this solution, might it be worth adding it as a note to the installation instructions for macOS?
