### ISSUE TITLE
Doc link to "LibriSpeech data set" is broken

### ISSUE THREAD

**Issue by antimora** [MontrealCorpusTools/Montreal-Forced-Aligner#128]
The link to a dropbox zip file (LibriSpeech data set) in this document page is broken: https://montreal-forced-aligner.readthedocs.io/en/stable/example.html.

From this documentation is not obvious what the expected format for LibriSpeech is.

**Comment by sjmelsom** [comment]
Encountering the same issue. Is the dataset that was on DropBox the same as [this one](http://www.openslr.org/12)?

**Comment by mmcauliffe** [comment]
Updated the links to the dataset on the docs page (should be Google Drive instead of a DropBox link)

**Comment by manojpamk** [comment]
The links still point to Dropbox and are broken

**Comment by CharlieLei** [comment]
> The links still point to Dropbox and are broken

The website of doc has been changed.
https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/example.html
