### ISSUE TITLE
minor libpython3.6m.so issue

### ISSUE THREAD

**Issue by cainesap** [MontrealCorpusTools/Montreal-Forced-Aligner#132]
Hello,
Thank you for providing this resource, it's much appreciated!
A minor thing when unpacking the linux tar file. I get 'libpython3.6m.so.1.0' in the 'lib' directory, which causes an error when testing 'bin/mfa_align' because it can't find 'libpython3.6m.so'
I copied the file and renamed it so all is fine, but just filing this minor issue anyway.
regards, Andrew

**Comment by mfaytak** [comment]
This replicates issue #109 if you're running Linux v1.0.1. Still not fixed, apparently.
