### ISSUE TITLE
align error：Dim mismatch: data dim = 91 vs. model dim = 40 and Possible memory leak: 1023 != 1024:

### ISSUE THREAD

**Issue by kedengfeng** [MontrealCorpusTools/Montreal-Forced-Aligner#134]
when I use the pretrained model for alignment, it comes to this errors:
*******************************************************************************
align.py:92: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 2.0
/fast/3.ali-data/forced-aligner/lib/aligner/models.py:107: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
/fast/3.ali-data/forced-aligner/lib/aligner/config/__init__.py:124: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
Calculating CMVN...
Done with setup.
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 224, in <module>
  File "aligner/command_line/align.py", line 181, in validate_args
  File "aligner/command_line/align.py", line 141, in align_corpus
  File "aligner/aligner/pretrained.py", line 93, in align
  File "aligner/multiprocessing.py", line 322, in align
aligner.exceptions.AlignmentError: There were 1 job(s) with errors.  For more information, please see the following logs:

song/temp/song/align/log/align.final.0.log
**************************************************************************
cat song/temp/song/align/log/align.final.0.log
gmm-align-compiled --transition-scale=1.0 --acoustic-scale=0.1 --self-loop-scale=0.1 --beam=10 --retry-beam=20 --careful=false 'gmm-boost-silence --boost=1.0 6 "song/temp/song/align/final.mdl" - |' ark:song/temp/song/align/fsts.0 scp:song/temp/song/corpus_data/split1/features_mfcc_cmvn_lda.0.scp ark:song/temp/song/align/ali.0 ark,t:song/temp/song/align/ali.0.scores 
gmm-boost-silence --boost=1.0 6 song/temp/song/align/final.mdl - 
WARNING (gmm-boost-silence[5.5.2~4-bcf8]:main():gmm-boost-silence.cc:82) The pdfs for the silence phones may be shared by other phones (note: this probably does not matter.)
LOG (gmm-boost-silence[5.5.2~4-bcf8]:main():gmm-boost-silence.cc:93) Boosted weights for 5 pdfs, by factor of 1
LOG (gmm-boost-silence[5.5.2~4-bcf8]:main():gmm-boost-silence.cc:103) Wrote model to -
LOG (gmm-align-compiled[5.5.2~4-bcf8]:main():gmm-align-compiled.cc:127) kdf001
ERROR (gmm-align-compiled[5.5.2~4-bcf8]:LogLikelihoodZeroBased():decodable-am-diag-gmm.cc:50) Dim mismatch: data dim = 91 vs. model dim = 40

[ Stack-Trace: ]
kaldi::MessageLogger::LogMessage() const
kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)
kaldi::DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(int, int)
kaldi::DecodableAmDiagGmmScaled::LogLikelihood(int, int)
kaldi::FasterDecoder::ProcessEmitting(kaldi::DecodableInterface*)
kaldi::FasterDecoder::Decode(kaldi::DecodableInterface*)
kaldi::AlignUtteranceWrapper(kaldi::AlignConfig const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> >, fst::VectorState<fst::ArcTpl<fst::TropicalWeightTpl<float> >, std::allocator<fst::ArcTpl<fst::TropicalWeightTpl<float> > > > >*, kaldi::DecodableInterface*, kaldi::TableWriter<kaldi::BasicVectorHolder<int> >*, kaldi::TableWriter<kaldi::BasicHolder<float> >*, int*, int*, int*, double*, long*, kaldi::TableWriter<kaldi::KaldiObjectHolder<kaldi::Vector<float> > >*)
main
__libc_start_main
_start

WARNING (gmm-align-compiled[5.5.2~4-bcf8]:~HashList():util/hash-list-inl.h:117) Possible memory leak: 1023 != 1024: you might have forgotten to call Delete on some Elems
**************************************************************************************
my training config is:
cat forced-aligner/lib/aligner/config/basic_train.yaml 
beam: 10
retry_beam: 20

features:
  type: "mfcc"
  use_energy: false
  frame_shift: 10

training:
  - monophone:
      num_iterations: 10
      subset: 2000
      max_gaussians: 1000
      boost_silence: 1.25

  - triphone:
      num_iterations: 15
      subset: 50000
      num_leaves: 2000
      max_gaussians: 10000
      cluster_threshold: -1
      boost_silence: 1.25
      power: 0.25

  - lda:
      num_iterations: 15
      subset: 100000
      num_leaves: 2500
      max_gaussians: 15000
      features:
          splice_left_context: 3
          splice_right_context: 3
***********************************************************************************************
my align config is:
cat forced-aligner/lib/aligner/config/basic_align.yaml
beam: 10
retry_beam: 20
features:
  type: mfcc
  use_energy: false
  frame_shift: 10
  lda: true
  deltas: false
  fmllr: false
  ivectors: false
  pitch: false
  splice_left_context: 3
  splice_right_context: 3
**************************************************************************************
how to config my basic_align.yaml to use the model trained with basic_train.yaml ?

**Comment by Sinnerboy89** [comment]
Am also having this mismatch issue between data and model - is there any guidance?

**Comment by eziolotta** [comment]
i had the same problem, i solved it by following these steps:
https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/104#issuecomment-636250179

**Comment by mmcauliffe** [comment]
So this should be fixed in the latest MFA 2.0 alpha, there were a lot of bugs in the LDA training that have been fixed now. I'm going to close this since it's pretty old, but feel free to open new issues if more issues arise.
