### ISSUE TITLE
No words found in dictionary path

### ISSUE THREAD

**Issue by sjmelsom** [MontrealCorpusTools/Montreal-Forced-Aligner#137]
### Traceback
./bin/mfa_validate_dataset /data/LibriSpeechWav/ /repos/Montreal-Forced-Aligner/pretrained_models/english.dict english
Setting up corpus information...
INPUT PATH /repos/Montreal-Forced-Aligner/pretrained_models/english.dict
Traceback (most recent call last):
  File "aligner/command_line/validate_dataset.py", line 78, in <module>
  File "aligner/command_line/validate_dataset.py", line 30, in validate_corpus
  File "aligner/dictionary.py", line 155, in __init__
aligner.exceptions.DictionaryFileError: The specified path for the dictionary (No words were found in the dictionary path /repos/Montreal-Forced-Aligner/pretrained_models/english.dict) is not a file.
[65441] Failed to execute script validate_dataset

I have encountered this error several times when trying to run mfa_validate_dataset. I preprocessed LibriSpeech (convert to .wav, 16kHz, 1 channel). The dataset was sourced from openslr.org as the [Dropbox link](https://www.dropbox.com/s/i08yunn7yqnbv0h/LibriSpeech.zip?dl=0) mentioned in the documentation was broken. I am new to this tool and have not been able to figure out what is causing this error. Any help is appreciated!

**Comment by penkesiva** [comment]
I faced a similar issue. Its about the dictionary file but the missing .lab or .txt files corresponding to the .wav files. Make sure you set the corpus directory before running the validate command.

**Comment by sjmelsom** [comment]
Issue resolved. The transcription file must be broken into individual files for their respective audio files. The filename is the same as the audio file, but with a .txt extension.

**Comment by mmcauliffe** [comment]
Yes sorry about the dropbox link being broken, the docs have been updated with a new link.
