### ISSUE TITLE
Maximum number of files

### ISSUE THREAD

**Issue by cveaux** [MontrealCorpusTools/Montreal-Forced-Aligner#144]
Hi, is there a limit on the number of files that the MFA can process?

I was trying `train_and_align` on a dataset of 19000 files in total (split evenly into 50 fake speakers in order to allow multiprocessing). The average duration of each file is ~3s and the longest file is less than 19s.

After the alignment I got just 2000 aligned files and each time I was retrying `train_and_align` the set of aligned files was different and around the same amount of 2000 files (which made me think it wasn't a problem of mismatch between the text and the audio.  I checked the text and the audio of some of the rejected files and they were matching anyway.)

Finally I split the dataset into 3 subsets of ~6500 files each and everything worked well (got ~6480 files aligned for each subset). I tried to find if there was such limit for the number of files in Kaldi but couldn't find any mention of it.

Ps: I am using the latest version of MFA (version 1.1)

Thanks

**Comment by mmcauliffe** [comment]
That might just be a bug in version 1.1, which is pretty unstable and doesn't quite work in a lot of ways.  There might be something wrong in the 1.1 training regimen that's doing subsetting, I was playing around with allowing for training on different sized subsets to speed up training. You could try running it in version 1.0.1, which should not have any issues with number of files.

**Comment by cveaux** [comment]
Ok thanks for the quick reply!
