### ISSUE TITLE
No such file or directory: '/home/app/Documents/MFA/19/train/mfcc/raw_mfcc.0.scp'

### ISSUE THREAD

**Issue by zgoda** [MontrealCorpusTools/Montreal-Forced-Aligner#149]
I'm running 1.0.1 binary on Linux (both Debian 10 and Ubuntu 18.04) and I am getting following error:

```
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 140, in validate_args
  File "aligner/command_line/align.py", line 135, in align_included_model
  File "aligner/command_line/align.py", line 94, in align_corpus
  File "aligner/aligner/pretrained.py", line 74, in __init__
  File "aligner/aligner/pretrained.py", line 122, in setup
  File "aligner/aligner/base.py", line 89, in setup
  File "aligner/corpus.py", line 979, in initialize_corpus
  File "aligner/corpus.py", line 852, in create_mfccs
  File "aligner/corpus.py", line 863, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/home/app/Documents/MFA/19/train/mfcc/raw_mfcc.0.scp'
[11] Failed to execute script align
```

Software is installed as per https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#linux, binaries print usage instructions if invoked without arguments.

The issue https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/91 contains workaround that is not applicable - there's no other openblas version in the whole directory tree.

libatlas3-base is already installed and is up to date

```
libatlas3-base is already the newest version (3.10.3-5).
```

**Comment by zgoda** [comment]
Exact same failure on Amazon Linux 2

```
Dependencies Resolved

================================================================================
 Package            Arch       Version                     Repository      Size
================================================================================
Installing:
 atlas              x86_64     3.10.1-12.amzn2.0.2         amzn2-core     4.7 M
 gcc-gfortran       x86_64     7.3.1-6.amzn2.0.4           amzn2-core      11 M
Installing for dependencies:
 binutils           x86_64     2.29.1-30.amzn2             amzn2-core     5.8 M
 cpp                x86_64     7.3.1-6.amzn2.0.4           amzn2-core     9.2 M
 gcc                x86_64     7.3.1-6.amzn2.0.4           amzn2-core      22 M
 glibc-devel        x86_64     2.26-34.amzn2               amzn2-core     989 k
 glibc-headers      x86_64     2.26-34.amzn2               amzn2-core     510 k
 kernel-headers     x86_64     4.14.173-137.229.amzn2      amzn2-core     1.1 M
 libatomic          x86_64     7.3.1-6.amzn2.0.4           amzn2-core      44 k
 libcilkrts         x86_64     7.3.1-6.amzn2.0.4           amzn2-core      84 k
 libgfortran        x86_64     7.3.1-6.amzn2.0.4           amzn2-core     535 k
 libgomp            x86_64     7.3.1-6.amzn2.0.4           amzn2-core     203 k
 libitm             x86_64     7.3.1-6.amzn2.0.4           amzn2-core      83 k
 libmpc             x86_64     1.0.1-3.amzn2.0.2           amzn2-core      52 k
 libmpx             x86_64     7.3.1-6.amzn2.0.4           amzn2-core      50 k
 libquadmath        x86_64     7.3.1-6.amzn2.0.4           amzn2-core     188 k
 libsanitizer       x86_64     7.3.1-6.amzn2.0.4           amzn2-core     640 k
 mpfr               x86_64     3.1.1-4.amzn2.0.2           amzn2-core     208 k

Transaction Summary
================================================================================
Install  2 Packages (+16 Dependent packages)
```

**Comment by zgoda** [comment]
FYI, there are no issues on Ubuntu 16.04.

**Comment by net2cn** [comment]
Try installing `libopenblas-dev`.
`sudo apt install libopenblas-dev`
It works on both Ubuntu 18.04 and 20.04 for me. (I've installed `libatlas3-base` to compile PortAudio before. Nevertheless, it seems that MFA is not utilizing it at all.)

**Comment by zgoda** [comment]
Hi @net2cn I'm using binary package, not source build. Is that your case?

**Comment by net2cn** [comment]
@zgoda yes, I'm also using the binary package.

**Comment by zgoda** [comment]
Unfortunately on Ubuntu 20.04 this does not help at all, program fails in the exact same way.

gfortran: 4:9.3.0-1ubuntu2
libatlas3-base: 3.10.3-8ubuntu7
libopenblas-dev: 0.3.8+ds-1

**Comment by net2cn** [comment]
That's weird, I'm able to use the program after installing `libopenblas-dev`.

Here's a list of software that I installed to solve this problem.
`libatlas3-base/focal,now 3.10.3-8ubuntu7 amd64 [installed]
libopenblas-dev/focal,now 0.3.8+ds-1 amd64 [installed]
libopenblas-pthread-dev/focal,now 0.3.8+ds-1 amd64 [installed,automatic]
libopenblas0-pthread/focal,now 0.3.8+ds-1 amd64 [installed,automatic]
libopenblas0/focal,now 0.3.8+ds-1 amd64 [installed,automatic]` 

FYI, I'm running Ubuntu Server 20.04 on a physical machine.

**Comment by nbusser** [comment]
I'm facing the same issue.
I installed all the packages you, @net2cn, mentioned but still got the error.

**Comment by net2cn** [comment]
Oh, I'm so sorry that I forgot to mention that you should delete `libopenblas.so.0` file in path `lib/thirdparty/bin` after installing `libopenblas-dev`.
Once you deleted that file, MFA should work with no problem.

**Comment by zgoda** [comment]
@net2cn thank you, finally anything works!

**Comment by zgoda** [comment]
Closing with workaround. 1.1.0-b2 works because it does not ship `libopenblas.so.0` and always uses systemwide installed one.

**Comment by sushantakpani** [comment]
1. Install openblas-devel in active conda enviornment:
        conda install -c anaconda openblas-devel 

2. Delete libopenblas.so.0
      rm -rf montreal_forced_aligner/lib/thirdparty/bin/libopenblas.so.0

**Comment by 1006076811** [comment]
> 

Thanks for your solution, this problem has been bothering me all day

**Comment by GCable-Surrin** [comment]
Thanks for your solution, this problem has been bothering me all day
