### ISSUE TITLE
How can I use more number of workers for MFA training?

### ISSUE THREAD

**Issue by liusongxiang** [MontrealCorpusTools/Montreal-Forced-Aligner#157]
I find the training is very slow. Could I use more workers for the training, like specify `-j 30` in Kaldi training procedures?
Thx!

**Comment by keshawnhsieh** [comment]
> I find the training is very slow. Could I use more workers for the training, like specify `-j 30` in Kaldi training procedures? Thx!

Do you find any solution to this problem? I met the same problem now and found that `mfa train --num_jobs 200` is not working as expected.
