### ISSUE TITLE
What if I don't need to add “sp" inside an utterence?

### ISSUE THREAD

**Issue by feelins** [MontrealCorpusTools/Montreal-Forced-Aligner#166]
I've already got "sp" inside an utterence, so I don't need to add it automatically. 
Is there some configuration for that?

**Comment by tekinek** [comment]
@feelins 
The following pages say that it is possible to specify custom non-speech annotations in pronunciation dictionary with `sil` and `spn`, like:

{LG} spn
{SL} sil

https://montreal-forced-aligner.readthedocs.io/en/latest/dictionary.html?highlight=SIL#non-speech-annotations 
https://montreal-forced-aligner.readthedocs.io/en/latest/changelog.html?highlight=SIL

**Comment by feelins** [comment]
> @feelins
> The following pages say that it is possible to specify custom non-speech annotations in pronunciation dictionary with `sil` and `spn`, like:
> 
> {LG} spn
> {SL} sil
> 
> https://montreal-forced-aligner.readthedocs.io/en/latest/dictionary.html?highlight=SIL#non-speech-annotations
> https://montreal-forced-aligner.readthedocs.io/en/latest/changelog.html?highlight=SIL

Thank you. I tried your method, but it still generates SP even I add 'spn' around the silence.

**Comment by Welsun** [comment]
Hi! Have you solved it? I meet a same problem now.

**Comment by mmcauliffe** [comment]
Should be fixed as of recent version.
