### ISSUE TITLE
linux version

### ISSUE THREAD

**Issue by rohithkodali** [MontrealCorpusTools/Montreal-Forced-Aligner#17]
HI,

 in the http://montreal-forced-aligner.readthedocs.io/en/stable/installation.html  docs page i can see that a ubuntu version is available, but i didn't find it anywhere, is that still available somewhere?

**Comment by mmcauliffe** [comment]
Sorry it's taken me a bit to get back to you, I was hoping to have a new version of the aligner out, but the next major release is going to be a bit bigger and not backwards compatible with the current one.  In the meantime, I uploaded a release for Ubuntu 14.04+ version (https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases/download/v0.8.1/montreal-forced-aligner_linux.tar.gz it has a few fixes compared to the last release, so not quite the same).

**Comment by mmcauliffe** [comment]
Linux version for 1.0.0 is built and all future releases should have executables for linux.
