### ISSUE TITLE
Alignment breaking when numeric symbols are used as phonetic symbols

### ISSUE THREAD

**Issue by cveaux** [MontrealCorpusTools/Montreal-Forced-Aligner#187]
Hi,

I have been trying to use MFA with a French phonetic dictionary built on X-sampa that has some phonetic symbols with numbers, like "9" or "2". To my surprise, the aligner was not able to align 80% of the files after the first monophone alignment pass, yielding to errors in the subsequent alignment steps. I have been using the exact same MFA code with English phonetic dictionaries without issues so it had to be a format problem. Indeed it worked once I replaced the phonetic symbols using numbers by some non-numeric symbols. I just wanted to mention that issue. I have searched any mention of a similar issue in Kaldi forums but didn't find anything so I guess it might be due to the data preparation step done by MFA.

Ps: I'm using MFA v1.1

**Comment by mmcauliffe** [comment]
So there was some code for dictionary parsing that was causing initial numbers to get parsed as probabilities, the fix for this is in the 2.0 branch, so that *might* address this issue, I haven't tested it specifically.

**Comment by cveaux** [comment]
Thanks, I've seen the commit, I'll test it.
