### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ziweizh** [MontrealCorpusTools/Montreal-Forced-Aligner#19]
When running MFA using the retained model (~/montreal-forced-aligner/pretrained_models/english.zip), I kept encountering the unicode decode error, as shown below:
Setting up corpus information...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 140, in <module>
  File "aligner/command_line/align.py", line 61, in align_corpus
  File "aligner/corpus.py", line 279, in __init__
  File "aligner/helper.py", line 13, in load_text
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 190: invalid continuation byte
Failed to execute script align

Here is the command line that I was using where I specified the pretained model, the corpus directory with wav and lab files and an output directory:
$ bin/mfa_align /Users/ziweizh/Documents/ISU_ALT/2017_Spring/ENGL_515/Final_Project/Tools/montreal-forced-aligner/pretrained_models/english.zip /Users/ziweizh/Documents/ISU_ALT/2017_Spring/ENGL_515/Final_Project/Data/UIUC/Corpus2_withUTF8 /Users/ziweizh/Documents/ISU_ALT/2017_Spring/ENGL_515/Final_Project/Tools/montreal-forced-aligner/output 

Even though I tried converting the encoding of the lab files using shell scripts: $ find . -name '*.lab' -exec iconv --verbose  -t utf-8 {} \> {} \;
MFA still three me this decode error.

**Comment by mmcauliffe** [comment]
Thanks for letting me know!  There's obviously something in one or more of the files that Python's having a hard time decoding, but I should make MFA a bit more robust/informative to when this happens for the next release.  It looks like you're doing a class project, so you might need something faster to track down which files are having issues. You can find the offending file via a simple script:

```
import os
directory = '/Users/ziweizh/Documents/ISU_ALT/2017_Spring/ENGL_515/Final_Project/Data/UIUC/Corpus2_withUTF8 '
for root, dirs, files in os.walk(directory):
    for f in files:
	    path = os.path.join(root,f)
	    try:
	        with open(path, encoding ='utf8') as t:
	            pass
	    except UnicodeDecodeError:
			print(path)
```

If nothing looks obviously odd with those files, could you attach one here so I can play around with it and see?

Thanks!

**Comment by ziweizh** [comment]
Hello mmcauliffe, 

I ran the Python script you suggested, and it seemed that all the files were file. The test was passed. Please see attached a few of the files I am using.

Yes, I am a PhD student in applied linguistics and I am interested in automated scoring of speaking proficiency for nonnative spontaneous speech. I am using MFA to get some automated indices of measuring pronunciation quality. 

Thanks!











[Archive.zip](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/922581/Archive.zip)

**Comment by mmcauliffe** [comment]
So it looks like there are some encoding issues, for instance in 003_2.lab "Champs-Élysées" isn't realized properly.  I don't know what the original encoding of the files was, but you'd probably want to specify that in the call to iconv.

I also just realized the script I gave you wouldn't actually find the erroring files, it should be:

```
import os
directory = '/Users/ziweizh/Documents/ISU_ALT/2017_Spring/ENGL_515/Final_Project/Data/UIUC/Corpus2_withUTF8 '
for root, dirs, files in os.walk(directory):
    for f in files:
	    path = os.path.join(root,f)
	    try:
	        with open(path, encoding ='utf8') as t:
	            text = t.read()
	    except UnicodeDecodeError:
			print(path)
```

Sorry about that!

**Comment by ziweizh** [comment]
Hello mmcauliffe ,

The updated script showed the same output with the previous one -- every text were read successfully . I tried `file -I` in the command line and it shows that my .lab files are text/plain; charset=us-ascii.
Even though I used the command line: 
`$ find . -name '*.lab' -exec iconv --verbose  -f US-ASCII -t utf-8 {} \> {} \;`
to convert the .lab files from us-ascii to utf-8. The files were still encoded as us-ascii as I checked using file -I command.

Do you know if there is a way to solve this encoding issue?  

Much appreciated!

**Comment by mmcauliffe** [comment]
Try ISO-8859-1 instead of US-ASCII, see if it fairs better.

**Comment by ziweizh** [comment]
Still showed the same thing, saying `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 190: invalid continuation byte
`
It's getting strange ...

**Comment by mmcauliffe** [comment]
Ok, I don't really trust what iconv is doing, here's a python conversion script that should work for your data:

```
import os
directory = '/Users/ziweizh/Documents/ISU_ALT/2017_Spring/ENGL_515/Final_Project/Data/UIUC/Corpus2_withUTF8 '
for root, dirs, files in os.walk(directory):
    for f in files:
	    path = os.path.join(root,f)
            with open(path, 'r', encoding ='latin1') as t:
                text = t.read()
            with open(path, 'w', encoding='utf8') as new_t:
                new_t.write(text)
```

This works for the files you sent me (opening with utf8 in a text editor shows the right characters).

**Comment by ziweizh** [comment]
Hi Michael, 

The code did not seem to work for me. As I checked the file type (after running the python code), the lab files are still us-ascii and I got the same decoding error when running MFA :(

**Comment by Alex-Beh** [comment]
Hello, I am facing the same issue. May I know eventually how you solve it?
