### ISSUE TITLE
pretrained model links not working (server down?)

### ISSUE THREAD

**Issue by afourast** [MontrealCorpusTools/Montreal-Forced-Aligner#198]
Hi,

The server hosting the pretrained models (http://mlmlab.org/) seems to be down. Are there any mirrors / alternative ways for downloading the models? Or any ETA on when mlmlab.org will be up again?

Thanks

**Comment by mmcauliffe** [comment]
Yes, they're mirrored here: https://github.com/MontrealCorpusTools/mfa-models, and the links should be updated on the "latest" version, but I believe the "stable" version is out of date for the links.
