### ISSUE TITLE
Multilingual Audio 

### ISSUE THREAD

**Issue by Ithrael** [MontrealCorpusTools/Montreal-Forced-Aligner#200]
I have an audio with Mandarin and English, Can I use two acoustic models simultaneously

**Comment by mmcauliffe** [comment]
Not easily, unfortunately.  The hacky workarounds would be to add pronunciations to one language's dictionary for other language words (i.e., approximate mandarin words using ARPABET).  Alternatively, if you know what sections are one language or the other, you can extract a Mandarin TextGrid and an English TextGrid, run two separate alignments, and then merge them again somehow.

There might be some functionality within kaldi to merge two acoustic models?  But I really haven't looked much whether that exists.

**Comment by Ithrael** [comment]
thx，The first method failed， I will study kaldi
