### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by qo4on** [MontrealCorpusTools/Montreal-Forced-Aligner#204]
The documentation has a line:
```
bin/mfa_align corpus_directory dictionary_path acoustic_model_path output_directory
```
Where if I understand correctly:
`acoustic_model_path` - `montreal-forced-aligner\pretrained_models\english.zip`
`output_directory` - any empty directory for aligned text files

What is `corpus_directory` and `dictionary_path`?
I have English voice `0.wav` file and its transcript `0.txt`. How should I feed them to `mfa_align` to get a timestamp for each word of `0.txt`?

**Comment by mmcauliffe** [comment]
So if you have those `0.wav` and `0.txt` in a directory, the `corpus_directory` is the path to that containing directory.  `dictionary_path` should point to a dictionary text file (that specifies how words are pronounced).  There's a dictionary here for english that works with the pretrained model: https://github.com/MontrealCorpusTools/mfa-models/blob/master/dictionary/english.dict.

**Comment by qo4on** [comment]
Thank you for your help. I tried this in Colab, but got an error:
```
!sudo apt-get update -y -qqq --fix-missing && apt-get install -y -qqq ffmpeg > /dev/null

!wget https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases/download/v1.0.1/montreal-forced-aligner_linux.tar.gz -qqq
!wget https://github.com/MontrealCorpusTools/mfa-models/raw/master/dictionary/english.dict -qqq
!tar -xf montreal-forced-aligner_linux.tar.gz
!mkdir corpus_directory output_directory

mfa_align = "/content/montreal-forced-aligner/bin/mfa_align"
corpus_directory = "/content/corpus_directory"
dictionary_path = "/content/english.dict"
acoustic_model_path = "/content/montreal-forced-aligner/pretrained_models/english.zip"
output_directory = "/content/output_directory"

!ffmpeg -y -i /content/23.mp3 -acodec pcm_s16le /content/corpus_directory/0.wav
!printf "Some text" > $corpus_directory/0.txt

!$mfa_align $corpus_directory $dictionary_path $acoustic_model_path $output_directory
[1046] Error loading Python lib '/content/montreal-forced-aligner/lib/libpython3.6m.so': dlopen: /content/montreal-forced-aligner/lib/libpython3.6m.so: cannot open shared object file: No such file or directory
```
Colab has Python 3.6.9.

**Comment by mmcauliffe** [comment]
That's not an error per se, you can simply say "N" to continue with the alignment (and have the OOV words modeled as "<unk>").  You can also supply the `-q` flag to the aligner to make it not check for OOVs

**Comment by qo4on** [comment]
I don't know why but it does not work either:
```
!$mfa_align -q $corpus_directory $dictionary_path $acoustic_model_path $output_directory

Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
/content/montreal-forced-aligner/lib/aligner/models.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
Setting up training data...
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 94, in align_corpus
  File "aligner/aligner/pretrained.py", line 74, in __init__
  File "aligner/aligner/pretrained.py", line 122, in setup
  File "aligner/aligner/base.py", line 89, in setup
  File "aligner/corpus.py", line 979, in initialize_corpus
  File "aligner/corpus.py", line 852, in create_mfccs
  File "aligner/corpus.py", line 863, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/corpus_directory/train/mfcc/raw_mfcc.0.scp'
[848] Failed to execute script align
```

**Comment by nrgslp** [comment]
I was able to resolve this by installing openblas. Here is some context; the comment I linked has a link to the work around: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/91#issuecomment-422978941

**Comment by qo4on** [comment]
I'm not sure how to install `OpenBLAS` in `Colab`. Is there any working example of `Montreal-Forced-Aligner` usage? I mean a simple starting example to see what it's doing. At the moment, it's completely unusable, everything I have tried returns errors.

**Comment by mmcauliffe** [comment]
I'm not too familiar with the platform but my guess would be either
installation via system package:

sudo apt-get install libopenblas0

Or installation via conda:

conda install openblas -c conda-forge

**Comment by qo4on** [comment]
> sudo apt-get install libopenblas0

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libopenblas0
```

**Comment by mmcauliffe** [comment]
It could also be libopenblas-base or something, it's platform specific, so
search your package manager for openblas.

**Comment by qo4on** [comment]
Is there anybody who managed to run Montreal-Forced-Aligner without errors?

**Comment by nrgslp** [comment]
> Is there anybody who managed to run Montreal-Forced-Aligner without errors?

Yes, in both Windows and Debian.

**Comment by qo4on** [comment]
> Yes, in both Windows and Debian.

Can you show your code for both?

**Comment by nrgslp** [comment]
For alignment follow this template:
- Windows v 1.0:
`bin/mfa_align corpus_directory dictionary_path acoustic_model_path output_directory`

- Debian v2.0:
`mfa align corpus_directory dictionary_path acoustic_model_path output_directory`

So, for me I ran:
- Windows v1.0:
`mfa_align c:\...\job-1\ c:\...CMU.dict english c:\...\output\job-1b\  -j 8 -i `

- Debian v2.0:
`mfa align /.../job-2/ /.../CMU.dict english /.../output/job-2/ -j 8 i`
