### ISSUE TITLE
ThirdpartyError: Could not find 'fstcompile'.  

### ISSUE THREAD

**Issue by MMingabc** [MontrealCorpusTools/Montreal-Forced-Aligner#205]
I encountered this error when try to validate data. How do I fix it? Thanks!

**Comment by dlukes** [comment]
The easiest way should be to follow the installation instructions under [*All platforms*](https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#all-platforms). These suggest installing MFA in a conda environment, which means you let conda take care of installing these additional dependencies for you.

**Comment by MMingabc** [comment]
Problem solved. Thank you!
