### ISSUE TITLE
Could not decode (beam too narrow) V1.0.1

### ISSUE THREAD

**Issue by Ithrael** [MontrealCorpusTools/Montreal-Forced-Aligner#207]
Dear，
What is the cause of this problem

**Comment by mmcauliffe** [comment]
You can adjust the beam with the `-b` command, something like `mfa_align ... -b 1000` which will set the beam to 1000 and retry_beam to 4000

**Comment by Ithrael** [comment]
thanks， I solved this problem by modifying beam
