### ISSUE TITLE
V2.0.0a2 mfa align output is None

### ISSUE THREAD

**Issue by Ithrael** [MontrealCorpusTools/Montreal-Forced-Aligner#215]
mfa align -v -d align_input pretrained_models/english_dictionary.txt pretrained_models/english.zip out

![image](https://user-images.githubusercontent.com/38208715/104847154-65171c80-5919-11eb-8623-380ffec61696.png)
Dear,  
There is None in output_directory

**Comment by quanzzz123** [comment]
Hello, may i ask where did you find this english dict?  My english dict has some phones not included in the acoustic model. But I downloaded it from the homepage.... Seems like the all the phones in the dict is upper.

**Comment by kyleyxw** [comment]
Hi there, I got same problem using the example1
![Screen Shot 2021-01-19 at 19 19 09](https://user-images.githubusercontent.com/20818794/105109876-6bc5a100-5a8b-11eb-88f9-9dd8531f14a1.png)

**Comment by Ithrael** [comment]
I got this problem because I installed MFA by virtualenv
I solved this problem when I install MFA by conda 

conda create -n aligner -c conda-forge python=3.8 openfst=1.7.6 pynini=2.1.0 ngram=1.3.9 baumwelch=0.3.1

https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html

I hope this will help you!!!

**Comment by Ithrael** [comment]
> Hello, may i ask where did you find this english dict? My english dict has some phones not included in the acoustic model. But I downloaded it from the homepage.... Seems like the all the phones in the dict is upper.

I'm sorry, me too.
ALl phones in my dict is upper
I down it from https://github.com/MontrealCorpusTools/mfa-models
How do you know some phones not included in the acoustic model, how do you parse the acountstic model
