### ISSUE TITLE
A ISSUE in MFA 2.0 linux version

### ISSUE THREAD

**Issue by cuongnguyengit** [MontrealCorpusTools/Montreal-Forced-Aligner#217]
All required kaldi binaries were found!
Setting up corpus information...
Parsing dictionary without pronunciation probabilties without silence probabilties
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
Traceback (most recent call last):
File "/home/thuyth-is/anaconda3/envs/aligner/bin/mfa", line 8, in 
sys.exit(main())
File "/home/thuyth-is/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 292, in main
run_train_corpus(args)
File "/home/thuyth-is/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 109, in run_train_corpus
align_corpus(args)
File "/home/thuyth-is/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 65, in align_corpus
a = TrainableAligner(corpus, dictionary, train_config, align_config,
File "/home/thuyth-is/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 29, in init
super(TrainableAligner, self).init(corpus, dictionary, align_config, temp_directory,
File "/home/thuyth-is/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/base.py", line 40, in init
self.setup()
File "/home/thuyth-is/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 36, in setup
trainer.feature_config.generate_features(self.corpus)
File "/home/thuyth-is/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/features/config.py", line 170, in generate_features
self.generate_base_features(corpus)
File "/home/thuyth-is/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/features/config.py", line 158, in generate_base_features
corpus.combine_feats()
File "/home/thuyth-is/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/corpus/base.py", line 436, in combine_feats
with open(path, 'r') as inf:
FileNotFoundError: [Errno 2] No such file or directory: '/home/thuyth/Documents/MFA/indir/corpus_data/split1/feats.0.scp'

I can't know that. Who can  help me, PLEASE?

**Comment by mmcauliffe** [comment]
You can try installing system versions of openblas, i.e. `sudo apt-get install libopenblas0` (though it might be called something slightly different like `libopenblas-base`).  Next release will have a detection and some updated installation instructions.

**Comment by cuongnguyengit** [comment]
I did that. Then i have another issue:

Traceback (most recent call last):
  File "/home/thuyth/anaconda3/envs/aligner/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/thuyth/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 292, in main
    run_train_corpus(args)
  File "/home/thuyth/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 109, in run_train_corpus
    align_corpus(args)
  File "/home/thuyth/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 68, in align_corpus
    a.train()
  File "/home/thuyth/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 68, in train
    trainer.train(call_back=print)
  File "/home/thuyth/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/trainers/sat.py", line 96, in train
    raise(Exception('There was an error training in iteration {}, please check the logs.'.format(i)))
Exception: There was an error training in iteration 1, please check the logs.




AND the log is

/home/thuyth/Documents/MFA/thirdparty/bin/gmm-sum-accs - /home/thuyth/Documents/MFA/indir/sat1/1.0.acc 
ERROR (gmm-sum-accs[5.5]:Input():util/kaldi-io.cc:756) Error opening input stream /home/thuyth/Documents/MFA/indir/sat1/1.0.acc
kaldi::KaldiFatalError
ERROR (gmm-est[5.5]:Read():matrix/kaldi-vector.cc:1224) Failed to read vector from stream.  EOF while trying to read vector. File position at start is -1, currently -1
WARNING (gmm-est[5.5]:Close():util/kaldi-io.cc:515) Pipe /home/thuyth/Documents/MFA/thirdparty/bin/gmm-sum-accs - "/home/thuyth/Documents/MFA/indir/sat1/1.0.acc"| had nonzero return status 65280
kaldi::KaldiFatalError

What can i do next?

**Comment by HannesKath** [comment]
I downloaded MFA yesterday and tried to run the example LibriSpeech. I got the same error message as cuongnguyengit. 'sudo apt-get install libopenblas0' solved the issue for me and the files were aligned. I use linux version Kubuntu.

**Comment by cuongnguyengit** [comment]
Its great for you. I had another one.

 did that. Then i have another issue:

Traceback (most recent call last):
File "/home/thuyth/anaconda3/envs/aligner/bin/mfa", line 8, in
sys.exit(main())
File
"/home/thuyth/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py",
line 292, in main
run_train_corpus(args)
File
"/home/thuyth/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py",
line 109, in run_train_corpus
align_corpus(args)
File
"/home/thuyth/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py",
line 68, in align_corpus
a.train()
File
"/home/thuyth/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py",
line 68, in train
trainer.train(call_back=print)
File
"/home/thuyth/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/trainers/sat.py",
line 96, in train
raise(Exception('There was an error training in iteration {}, please check
the logs.'.format(i)))
Exception: There was an error training in iteration 1, please check the
logs.

AND the log is

/home/thuyth/Documents/MFA/thirdparty/bin/gmm-sum-accs -
/home/thuyth/Documents/MFA/indir/sat1/1.0.acc
ERROR (gmm-sum-accs[5.5]:Input():util/kaldi-io.cc:756) Error opening input
stream /home/thuyth/Documents/MFA/indir/sat1/1.0.acc
kaldi::KaldiFatalError
ERROR (gmm-est[5.5]:Read():matrix/kaldi-vector.cc:1224) Failed to read
vector from stream. EOF while trying to read vector. File position at start
is -1, currently -1
WARNING (gmm-est[5.5]:Close():util/kaldi-io.cc:515) Pipe
/home/thuyth/Documents/MFA/thirdparty/bin/gmm-sum-accs -
"/home/thuyth/Documents/MFA/indir/sat1/1.0.acc"| had nonzero return status
65280
kaldi::KaldiFatalError

What can i do next?

Vào 14:47, Th 5, 21 thg 1, 2021 HannesKath <notifications@github.com> đã
viết:

**Comment by mmcauliffe** [comment]
Can you try deleting the temporary directory that MFA creates for the corpus (/home/thuyth/Documents/MFA/indir), it's possible the previous errors are causing these ones (the EOF error indicates empty files).  Still working on the next alpha release that has better logging.

**Comment by cuongnguyengit** [comment]
I think that there has different in here. I used command "mfa
train_and_align ..", and you "mfa align ..."

Vào 14:47, Th 5, 21 thg 1, 2021 HannesKath <notifications@github.com> đã
viết:

**Comment by cuongnguyengit** [comment]
I am really looking forward to using the next alpha release. In fact, i always delete the temporary directory that MFA creates for the corpus, and the error is still existing. It's very good if i can be good at using MFA2.0 tool.

**Comment by mmcauliffe** [comment]
The new alpha 2.0.0a4 is out now, if you can test with that, it might have fixed your issues.

**Comment by cassiobatista** [comment]
I was having a similar issue with version 2.0.0a4, which I think leads to the same `split1/feats.0.scp` missing file error:

```text
$ mfa align /tmp/male /tmp/dict_mfa.dict \
    $HOME/Documents/MFA/pretrained_models/acoustic/portuguese.zip /tmp/out
All required kaldi binaries were found!                                                                                                                                                        
/home/cassio/Documents/MFA/male/align.log                                                                                                                                                      
INFO - Setting up corpus information...                                                                                                                                                        
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 200.0
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 200.0
INFO - Parsing dictionary without pronunciation probabilties without silence probabilties
INFO - Creating dictionary information...                                                      
INFO - Setting up training data...                                                             
Generating base features (mfcc)...                                                             
Done with setup.                                                                               
Traceback (most recent call last):                                                             
  File "/home/cassio/anaconda3/envs/aligner/bin/mfa", line 8, in <module>
    sys.exit(main())                                                                           
  File "/home/cassio/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 335, in main
    run_align_corpus(args, unknown, acoustic_languages)               
  File "/home/cassio/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 160, in run_align_corpus
    align_corpus(args, unknown_args)                                                                                                                                                           
  File "/home/cassio/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 99, in align_corpus   
    a.align()                          
  File "/home/cassio/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/pretrained.py", line 86, in align
    compile_train_graphs(self.align_directory, self.dictionary.output_directory,                                                                                                               
  File "/home/cassio/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing/alignment.py", line 190, in compile_train_graphs
    run_mp(compile_train_graphs_func, jobs, log_directory)                             
  File "/home/cassio/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing/helper.py", line 89, in run_mp
    parse_logs(log_directory)                                                                  
  File "/home/cassio/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/helper.py", line 196, in parse_logs
    raise ThirdpartyError('There was a problem locating libopenblas.so.0. '
montreal_forced_aligner.exceptions.ThirdpartyError: There was a problem locating libopenblas.so.0. Try installing openblas via system package manager?
```

Installing OpenBLAS via package manager didn't work out for me, but setting `LD_LIBRARY_PATH` did:

```bash
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/anaconda3/envs/aligner/lib/ 
```

```text
$ mfa align /tmp/male /tmp/dict_mfa.dict \
    $HOME/Documents/MFA/pretrained_models/acoustic/portuguese.zip /tmp/out
All required kaldi binaries were found!
/home/cassio/Documents/MFA/male/align.log
WARNING - WARNING: Using old temp directory, this might not be ideal for you, use the --clean flag to ensure no weird behavior for previous versions of the temporary directory.
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 200.0
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 200.0
INFO - Parsing dictionary without pronunciation probabilties without silence probabilties
INFO - Creating dictionary information...
INFO - Setting up training data...
Generating base features (mfcc)...
Calculating CMVN...
Done with setup.
INFO - All done!
```

**Comment by cuongnguyengit** [comment]
Oh sorry. Now i just can read your commends. I have another question. I want to build MFA aligner by a docker image. So i need a dockerfile. Thanks

**Comment by cuongnguyengit** [comment]
Hi @mmcauliffe,
I used MFA toolkit 2.0 good for my data. However, when i run " mfa train My_Data/wavs/ ./dict.txt /TextGrid/ -s 1 -j 16 -c", i received logs below:

INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 10, average number of utterances per speaker: 1256.3
INFO - Number of speakers in corpus: 10, average number of utterances per speaker: 1256.3
INFO - Parsing dictionary without pronunciation probabilities without silence probabilities
INFO - Creating dictionary information...
INFO - Setting up training data...

Number of speakers in corpus is 10 but my data is a single speaker.
Is it a error? What can i resolve the problem?

Many thanks.

**Comment by mmcauliffe** [comment]
The flag `-s 1` makes it so that it parses the first character of file names as the speaker identifier, which is likely not what you want.  If you remove that flag, it should parse the speakers from the directory they're in (assuming you have the corpus split up by speaker).  See https://montreal-forced-aligner.readthedocs.io/en/latest/data_prep.html for more details on how MFA parses speaker information.

**Comment by cuongnguyengit** [comment]
Thank you for your answer.
I didn't understand the flag thoroughly.
I think i know MFA more today.

**Comment by cuongnguyengit** [comment]
Thank you for your all support. This issue is closed.
