### ISSUE TITLE
Create mailing list for mfa-users with questions

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/Montreal-Forced-Aligner#22]
Update documentation to point to group for issues running MFA, should be more sustainable than just emailing me.

**Comment by ziweizh** [comment]
Good idea. I am looking forward to the mailing list.

**Comment by mmcauliffe** [comment]
Created at: https://groups.google.com/forum/#!forum/mfa-users, added links to docs introduction, and github pages site.
