### ISSUE TITLE
Recommended quantity of data in corpus for new models?

### ISSUE THREAD

**Issue by Kedersha** [MontrealCorpusTools/Montreal-Forced-Aligner#220]
Hi! One of the faculty in my dept is interested in running the aligner on a small corpus of Greek data. How many minutes/hours of recordings would you recommend (as a minimum) for using to create new language models and align this corpus data?

I had a quick look through the docs and existing issues, and couldn't find guidelines for this type of question--I hope I'm not doubling up on something that's been covered elsewhere, but thanks for your time regardless!

**Comment by mmcauliffe** [comment]
Hi Elise, hope you're doing well!  The question has popped up a few times, and I don't have a great answer, it really depends on the variability in the corpus.  I've added some data to the pretrained models page (https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html#pretrained-acoustic-models) for how much data the pretrained models contain.

I'd probably recommend something like 5 hours absolute minimum for training from scratch, more like 10-20 to get a robust model? But honestly it might be possible to get reasonable enough alignments with less.

**Comment by Kedersha** [comment]
Hi Michael, hope you're well too! Thanks for your response--knowing how much went into the pretrained models is very helpful, that's great information to have added to that page. 👍 I'll pass the info along to the professor, and hope for enough data in that corpus for a nice alignment! 5hrs seems possible, he's been collecting recordings for some time.

Thanks again, take care!
