### ISSUE TITLE
Sensitivity to Silence

### ISSUE THREAD

**Issue by MMingabc** [MontrealCorpusTools/Montreal-Forced-Aligner#222]
Hi,
The overall performance of MFA is impressive. 
But I found that the model is too sensitive to silence, i.e. some ends of phonemes are classified as SIL.
Any techniques to fix this?
Thanks!

**Comment by mmcauliffe** [comment]
You can try playing with the `boost_silence` parameter for alignment configs: https://montreal-forced-aligner.readthedocs.io/en/latest/configuration_align.html.  1.0 is the default which does not boost silence, greater than 1.0 will boost the probability of silence and lower than 1.0 will reduce the probability of silence.  I haven't played with it too much, but it might be what you're looking for.

**Comment by turian** [comment]
Strangely, I have found the opposite. A small amount of noise energy will cause MFA to grossly extend syllables instead of using silence.

Even when using boost_silence=20, a trailing phoneme goes from 1.29s to 1.25s, whereas in fact it is FAR shorter and there is just a little grit in the recording.

**Comment by MMingabc** [comment]
@turian I trained another ASR model for force alignment. The model has the exact problem you have. I post-processed the alignments with some rules by leveraging F0 and energy. The results are acceptable.

**Comment by DanielSWolf** [comment]
I'm also having the problem of MFA extending phonemes into silence for noisy recordings. Strangly, it only seems to affect the very last phoneme of an utterance. Silences between words are detected correctly.

![image](https://user-images.githubusercontent.com/5963162/158031807-2ffc5bbe-7884-4bd0-8adc-e826f1ceb620.png)

**Comment by mmcauliffe** [comment]
This should be fixed with recent improvements to how silence gets modeled.

**Comment by DanielSWolf** [comment]
@mmcauliffe Sounds great! What has changed?
