### ISSUE TITLE
2.0.0a3 - 'text' file in corpus_data inserting spaces between utterance graphemes 

### ISSUE THREAD

**Issue by nrgslp** [MontrealCorpusTools/Montreal-Forced-Aligner#223]
2.0.0a3 Command:

`mfa align /mnt/c/.../Rhotic-Corpus-zCondor-sync/gt-rhotics/ /mnt/c/.../Rhotic-Corpus-zExtras/MFA/librispeech.dict english /home/.../Documents/gt-rhotics-out/adult_eng2/ --num_jobs 8 --clean`

Source TGs:
![image](https://user-images.githubusercontent.com/53921196/106829945-1aa4d800-665b-11eb-871b-0497acc0d419.png)

The 2.0.0a3 `text ` file in corpus_data seems to be inserting spaces within the transcriptions:

```
1120_PTR_1120_WordProbe_PostTreatment_Sync_vlc_67_4671_68_9149 f a r m
1120_PTR_1120_WordProbe_PostTreatment_Sync_vlc_74_9702_76_0917 r a w
1120_PTR_1120_WordProbe_PostTreatment_Sync_vlc_77_7115_78_9308 b a r n
1120_PTR_1120_WordProbe_PostTreatment_Sync_vlc_82_1621_83_2971 r a f t
1120_PTR_1120_WordProbe_PostTreatment_Sync_vlc_84_6532_86_4483 s h a r e
1120_PTR_1120_WordProbe_PostTreatment_Sync_vlc_89_6705_91_1819 c h e e r
```
And 2.0.0a3 words.txt is the set of all graphemes:
```
<eps> 0
!sil 1
<unk> 2
a 3
b 4
c 5
d 6
e 7
f 8
g 9
h 10
i 11
k 12
l 13
m 14
n 15
o 16
p 17
r 18
s 19
t 20
u 21
w 22
y 23
#0 24
<s> 25
</s> 26
```

Which results in 2.0.0a3 alignments where each grapheme is transcribed as the grapheme name:
![image](https://user-images.githubusercontent.com/53921196/106830751-af5c0580-665c-11eb-84c9-a482de716ce3.png)

Behaves as expected after reverting to 2.0.0.a2:
![image](https://user-images.githubusercontent.com/53921196/106831917-c3086b80-665e-11eb-9361-9e6e158abcd5.png)

**Comment by mmcauliffe** [comment]
Ah, yes, I noticed that earlier today, try updating again to 2.0.0a4 and it should be fixed

**Comment by nrgslp** [comment]
Awesome, thanks!
