### ISSUE TITLE
SAT1 alignment failing

### ISSUE THREAD

**Issue by dlukes** [MontrealCorpusTools/Montreal-Forced-Aligner#226]
This is the main log:

<details>

```
All required kaldi binaries were found!
/home/lukes/Documents/MFA/ortofon-v2-mfa-in-test2/train_and_align.log
INFO - Cleaning old directory!
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 1431, average number of utterances per speaker: 178.93570929419985
INFO - Number of speakers in corpus: 1431, average number of utterances per speaker: 178.93570929419985
INFO - Parsing dictionary without pronunciation probabilties without silence probabilties
INFO - Creating dictionary information...
INFO - Setting up training data...
Generating base features (mfcc)...
Calculating CMVN...
INFO - Initializing training for mono...
INFO - Initialization complete!
100%|██████████| 39/39 [03:31<00:00,  5.42s/it]
INFO - Training complete!
INFO - Generating alignments using mono models using 5000 utterances...
INFO - Initializing training for tri...
INFO - Initialization complete!
100%|██████████| 34/34 [02:39<00:00,  4.70s/it]
INFO - Training complete!
INFO - Generating alignments using tri models using 10000 utterances...
INFO - Initializing training for lda...
INFO - Initialization complete!
100%|██████████| 35/35 [21:58<00:00, 37.67s/it]
INFO - Training complete!
INFO - Generating alignments using lda models using 10000 utterances...
INFO - Initializing training for sat1...
INFO - Initializing speaker-adapted triphone training...
INFO - Initialization complete!
100%|██████████| 34/34 [4:43:00<00:00, 499.41s/it]
INFO - Training complete!
INFO - Generating alignments using sat1 models for the whole corpus...
Traceback (most recent call last):
  File "/home/lukes/miniconda3/envs/mfa/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 337, in main
    run_train_corpus(args)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 143, in run_train_corpus
    align_corpus(args, unknown_args)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 95, in align_corpus
    a.train()
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 77, in train
    previous.align(trainer.subset)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/trainers/sat.py", line 171, in align
    align('final', self.align_directory, align_data_directory,
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing/alignment.py", line 302, in align
    run_mp(align_func, jobs, log_directory)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing/helper.py", line 89, in run_mp
    parse_logs(log_directory)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/helper.py", line 202, in parse_logs
    raise KaldiProcessingError(error_logs)
montreal_forced_aligner.exceptions.KaldiProcessingError: There was one or more errors when running Kaldi binaries.
```

</details>

After inspecting the Kaldi logs in MFA's working directory, I found three errors which all look more or less like this:

```
LOG (gmm-align-compiled[5.5]:main():gmmbin/gmm-align-compiled.cc:127) 13O001N-72_1355b-Uo
WARNING (gmm-align-compiled[5.5]:AlignUtteranceWrapper():decoder/decoder-wrappers.cc:617) Retrying utterance 13O001N-72_1355b-Uo with beam 40
ERROR (apply-cmvn[5.5]:ApplyCmvn():transform/cmvn.cc:70) Dim mismatch: cmvn 2x14, feats 0x0
kaldi::KaldiFatalErrorLOG (gmm-align-compiled[5.5]:main():gmmbin/gmm-align-compiled.cc:127) 13O001N-72_1355f-Uo
```

(In addition to a whole lot of lines with `WARNING (gmm-align-compiled[5.5]:main():gmmbin/gmm-align-compiled.cc:103) No features for utterance 13O001N-72_1356d-UO` following after the error, which also look problematic, but I'm guessing these may have been caused by Kaldi aborting at that point?)

What I'm planning to try at this point:

1. Widening the retry beam, maybe that'll help to align these pesky utterances?
2. Just leave them out.

Any other suggestions?

And second, I'm thinking maybe it would be nice for users new to MFA and Kaldi to provide a little bit more information when failing with a `KaldiProcessingError` -- maybe at least point the user to the relevant log directory which led to the error, something like `montreal_forced_aligner.exceptions.KaldiProcessingError: There was one or more errors when running Kaldi binaries. For more information, search for "ERROR" in the logs under /path/to/log/directory.` Ideally, there could even be a link to a page in the docs dedicated to suggestions on what to do when Kaldi chokes on some of the input files (widen the retry beam, leave them out, ...?).

**Comment by mmcauliffe** [comment]
Hmm, so this seems like something went wrong during feature generation (feats 0x0), but I've never seen this message before.  Would it be possible to email me the wav/text file and I can play around with getting it working/seeing what's going wrong?

**Comment by dlukes** [comment]
Sure, thanks for considering looking into this :) I'll drop you a line.

**Comment by dlukes** [comment]
E-mail sent, hopefully it doesn't land in your spam box :)

**Comment by dlukes** [comment]
Quoting from @mmcauliffe's e-mails [for posterity](https://xkcd.com/979/) (thank you very much again for getting to the bottom of this!) -- here's the original diagnosis:

> [I]t looks like there are a couple of extremely short wav files in there. I had some checks originally for ignoring these, but it seems like they're not getting done properly now with some updates to how features are used. I'll work on fixing that up [...]
> 
> For diagnosing a larger set, I used the command:
> 
> ```
> ~/Documents/MFA/thirdparty/bin/feat-to-len scp:/mnt/d/temp/train_temp/dim-mismatch/corpus_data/feats.scp ark,t:- | grep " 0"
> ```
> 
> Just substitute your own temp path to the feats.scp file and that should list out all the ones that had issues.

And here are some details after pushing 7c03241:

> [...] [T]he process extracting the features crashed when it hit the short files causing all the later ones to not return features, so that's where all the "no features found for X" came from.  Pushed a change to the mainline, so you can try installing that and it should work!  Also added a warning to it when it finds them, and it's hooked in with the validator utility again.  As an FYI, I've set the minimum duration to 13 frames (or 0.130 seconds), since that's basically a minimum phone duration (3 frames) plus two minimum silences on either side (5 frames).
