### ISSUE TITLE
2.0.0.a4 error loading custom yaml

### ISSUE THREAD

**Issue by nrgslp** [MontrealCorpusTools/Montreal-Forced-Aligner#230]
I am trying to use a custom yaml file, which I based off of the [default training config file](https://montreal-forced-aligner.readthedocs.io/en/latest/configuration.html#default-training-config-file). I copied this default into a file and modified from there.

Here is the command:

`mfa train /mnt/c/Apps-SU/Rhotic-Corpus-zCondor-sync/gt-rhotics/ /mnt/c/Apps-SU/Rhotic-Corpus-zExtras/MFA/gt-rhotics_CMU_full.dict /home/.../Documents/gt-rhotics-out/trained_regdict2/ --num_jobs 8 -o /home/.../Documents/gt-rhotics-out/model_regdict2.zip -t /home/.../Documents/MFA/job2/ -c --config_path /home/.../Documents/noLDA.yaml`

There seems to be an issue parsing the yaml, and it's taking it all as a string. Is it because of the content of the yaml? Or something else? Here is a txt version of the .yaml.
[noLDA.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/5997243/noLDA.txt)

```
/home/.../Documents/MFA/job2/gt-rhotics/train_and_align.log
Traceback (most recent call last):
  File "/home/.../miniconda3/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 337, in main
    run_train_corpus(args)
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 143, in run_train_corpus
    align_corpus(args, unknown_args)
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 32, in align_corpus
    train_config, align_config = train_yaml_to_config(args.config_path)
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/config/train_config.py", line 62, in train_yaml_to_config
    for k, v in data.items():
AttributeError: 'str' object has no attribute 'items'
```

Any pointers from the community would be appreciated. Thanks!

**Comment by nrgslp** [comment]
As a note about the [default config example](https://montreal-forced-aligner.readthedocs.io/en/latest/configuration.html#default-training-config-file), some of the defaults in the example differ from the defaults previously stated in the tables higher up on the page, so I'm unsure of what some of the default values actually are. For example, is the default `num_iterations `for `LDA ` `35 `or  `40`?

**Comment by mmcauliffe** [comment]
It looks like you're missing colons between keys and values?

Should be something like:

```
beam: 10
```

rather than `beam 10`.

For yaml, you have to have a colon after every key.

I'll take a look at the configurations doc, the default config will be more accurate than the tables, which I might have copy and pasted from elsewhere.
