### ISSUE TITLE
had an error message: ArgumentError: Could not find the corpus directory input

### ISSUE THREAD

**Issue by yj3341** [MontrealCorpusTools/Montreal-Forced-Aligner#233]
Hi all,

I am trying to run the grapheme-to-phoneme model to create the dictionary with the following commend: bin/mfa_generate_dictionary pretrained_models/korean_hangul_g2p.zip input  pretrained_models/korean_dict.tx

But I got the following error:

Do you have any idea what the issue is?
<img width="567" alt="Screen Shot 2021-02-24 at 1 27 32 PM" src="https://user-images.githubusercontent.com/57818299/108947575-11c88480-76a4-11eb-955a-945c5e594e8e.png">

**Comment by mmcauliffe** [comment]
This looks like an older version, so I don't know if this is still an issue in the 2.0 alpha.  One thing you can try is to specify full paths rather than relative paths, that might work better?
