### ISSUE TITLE
PretrainedAligner MFA v1.1 versus V2.0

### ISSUE THREAD

**Issue by cveaux** [MontrealCorpusTools/Montreal-Forced-Aligner#239]
Hi, this is more a question than an issue,  so far I've been using MFA v1.1 but using only with `train_and_align` as I generally have large datasets to process. However I wanted to consider using a pre-trained multi-speaker model of my own with the `align` command line. But looking at the code for the `PretrainedAligner` I noticed that it was just using the pre-trained model straight away without performing any adaptation. Then, looking at the same code for MFA v2.0 I can see that it is now performing fMLLR adaptation after a first pass of alignment: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/montreal_forced_aligner/aligner/pretrained.py#L99-L100

Do you confirm then that MFAv1.1 is not to be used for pre-trained alignment and that it's better to upgrade directly to MFA v2.0?
Thanks for all the work.

**Comment by mmcauliffe** [comment]
Yes, that's correct, there was a bug in 1.1 and earlier alpha versions of 2.0 where it wouldn't actually call the speaker adaptation.
