### ISSUE TITLE
Mandarin dict

### ISSUE THREAD

**Issue by zhangsanfeng86** [MontrealCorpusTools/Montreal-Forced-Aligner#243]
Hi mmcauliffe,

when align mandarin ,  Where could get the mandarin dictionary?

**Comment by mmcauliffe** [comment]
So there aren't dictionaries available, but there are G2P models for generating pronunciations from your corpora text here: https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html#pretrained-g2p-models.  There's one that takes as input pinyin, and another that takes hanzhi.

You'll follow the command here: https://montreal-forced-aligner.readthedocs.io/en/latest/g2p_dictionary_generating.html#use and point the input path to your corpus directory, which will compile a word list and run it through the G2P model to give you a dictionary.

**Comment by zhangsanfeng86** [comment]
@mmcauliffe thank you for ur quick reply :)
another question is : 
what's the difference:
1) mfa g2p g2p_model_path input_path output_path
2) mfa g2p input_path output_path

If generate mandarin dictionary, which should use?

**Comment by zhangsanfeng86** [comment]
thank you for ur quick reply:)

**Comment by zhangsanfeng86** [comment]
@mmcauliffe 

Anoter question:

Does the lexicon.txt equal to the dictionary?

**Comment by YoungKang1222** [comment]
https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/365#issue-1071833993
