### ISSUE TITLE
Vietnamese acoustic model phones and g2p model phones does not match

### ISSUE THREAD

**Issue by namdn** [MontrealCorpusTools/Montreal-Forced-Aligner#247]
I am using MFA to align my Vietnamese corpus, I am using pretrained Vietnamese acoustic and Vietnamese g2p, after generator dictionary, I align my corpus but an error has occurred:

dictionary phones: {'ieu_T2', 's', 'i_T1', 'e1_T5', 'u2_T5', 'e2_T5', 'ie2_T1', 'uoi3_T2', 'a3_T2', 'a2_T4', 'iu_T2', 'o1_T5', 'nh', 'ua2_T4', 'o2_T5', 'ui_T3', 'u2_T1', 'o3_T6', 'u1_T2', 'uoi3_T4', 'oi_T1', 'uy_T3', 'e1_T4', 'i_T2', 'oi_T2', 'oi2_T4', 'ng', 'u1_T4', 'au3_T6', 'iu_T1', 'ui2_T4', 'au3_T4', 'uoi2_T3', 'uy_T6', 'ay_T5', 'ieu_T5', 'i_T5', 'ay_T6', 'e1_T2', 'ua2_T3', 'uu2_T3', 'l', 'au_T2', 'ao_T5', 'n', 'oi3_T4', 'ieu_T1', 'uoi2_T2', 'ch', 'a1_T1', 'x', 'ui_T2', 'k', 'ao_T4', 'uou_T3', 'uy_T1', 'a2_T3', 'uy_T2', 'uoi3_T1', 'oi3_T2', 'o3_T5', 'au_T1', 'ua_T6', 'ieu_T6', 'iu_T6', 'oi2_T5', 'au3_T2', 'o1_T2', 'a2_T1', 'uoi3_T5', 'oi3_T6', 'oe_T3', 'oi_T3', 'iu_T5', 'eu_T2', 'oi_T5', 'uu2_T5', 'a1_T3', 'kh', 'uy_T4', 'ao_T3', 'uoi2_T6', 'a3_T3', 'ay3_T3', 'oi_T6', 'au_T6', 'u2_T3', 'a3_T6', 'uoi2_T4', 'o3_T4', 'ie2_T5', 'u1_T6', 'ua2_T5', 'ua_T2', 'eu_T3', 'uu2_T2', 'a1_T2', 'eo_T6', 'e1_T3', 'ie2_T2', 'i_T4', 'a2_T2', 'a2_T5', 'ay3_T6', 'u2_T4', 'o1_T3', 'a3_T1', 'ai_T4', 'ai_T6', 'eo_T5', 'h', 'e2_T1', 'e2_T3', 'oi2_T6', 'o3_T3', 'au_T3', 'tr', 'u1_T3', 'uy_T5', 'oe_T1', 'ui_T1', 'o3_T1', 'oa_T6', 'ay_T3', 'oi3_T1', 'ie2_T4', 'uu2_T6', 'j', 'au3_T5', 'ay_T1', 'oa_T3', 'o1_T1', 'oi_T4', 'uoi3_T6', 'ay3_T4', 'au3_T3', 'o2_T1', 'ay3_T1', 'o1_T6', 'ai_T3', 'ua2_T1', 'e1_T1', 'ua_T3', 'ai_T2', 'oa_T2', 'ua2_T6', 'u2_T6', 'ay3_T5', 'g', 'eo_T4', 'a3_T4', 'oa_T1', 'ao_T6', 'a1_T4', 'o2_T2', 'ua_T5', 'ao_T2', 'ieu_T4', 'eu_T5', 'au_T4', 'iu_T4', 'ay3_T2', 'uoi2_T1', 'oi2_T3', 'u1_T1', 'eo_T1', 'o2_T3', 'oe_T6', 'd2', 'ua2_T2', 'ay_T2', 'ui_T4', 't', 'o1_T4', 'p', 'ay_T4', 'o3_T2', 'ua_T4', 'i_T3', 'ai_T1', 'i_T6', 'd1', 'oi2_T2', 'oe_T4', 'u1_T5', 'eu_T6', 'e2_T6', 'a1_T5', 'r', 'ie2_T6', 'o2_T4', 'o2_T6', 'iu_T3', 'ua_T1', 'ui_T5', 'ieu_T3', 'ph', 'uoi3_T3', 'b', 'a1_T6', 'oa_T5', 'e2_T4', 'a3_T5', 'uoi2_T5', 'eo_T3', 'oi2_T1', 'eu_T4', 'oe_T5', 'au3_T1', 'm', 'v', 'oa_T4', 'uu2_T4', 'oi3_T5', 'uou_T6', 'eo_T2', 'a2_T6', 'uou_T1', 'oi3_T3', 'e2_T2', 'u2_T2', 'ai_T5', 'e1_T6', 'ie2_T3', 'uou_T2', 'th', 'uu2_T1', 'ao_T1', 'oe_T2', 'ui_T6'}
model phones: {'ieu_T2', 's', 'i_T1', 'e1_T5', 'u2_T5', 'e2_T5', 'ie2_T1', 'uoi3_T2', 'a3_T2', 'a2_T4', 'iu_T2', 'o1_T5', 'nh', 'ua2_T4', 'o2_T5', 'ui_T3', 'u2_T1', 'o3_T6', 'u1_T2', 'uoi3_T4', 'oi_T1', 'uy_T3', 'e1_T4', 'i_T2', 'oi_T2', 'oi2_T4', 'ng', 'u1_T4', 'au3_T6', 'iu_T1', 'ui2_T4', 'au3_T4', 'uoi2_T3', 'ay_T5', 'uy_T6', 'i_T5', 'ay_T6', 'e1_T2', 'ua2_T3', 'uu2_T3', 'l', 'au_T2', 'ao_T5', 'n', 'oi3_T4', 'ieu_T1', 'ch', 'a1_T1', 'x', 'ui_T2', 'k', 'ao_T4', 'uy_T1', 'a2_T3', 'uoi3_T1', 'uy_T2', 'au_T1', 'o3_T5', 'oi3_T2', 'ua_T6', 'ieu_T6', 'iu_T6', 'oi2_T5', 'au3_T2', 'o1_T2', 'a2_T1', 'uoi3_T5', 'oi3_T6', 'oe_T3', 'oi_T3', 'iu_T5', 'eu_T2', 'oi_T5', 'uu2_T5', 'a1_T3', 'kh', 'uy_T4', 'ao_T3', 'uoi2_T6', 'a3_T3', 'ay3_T3', 'oi_T6', 'u2_T3', 'a3_T6', 'uoi2_T4', 'o3_T4', 'ie2_T5', 'u1_T6', 'ua2_T5', 'ua_T2', 'eu_T3', 'uu2_T2', 'a1_T2', 'ua_T4', 'eo_T6', 'e1_T3', 'ie2_T2', 'i_T4', 'a2_T2', 'a2_T5', 'ay3_T6', 'u2_T4', 'o1_T3', 'a3_T1', 'ai_T4', 'ai_T6', 'eo_T5', 'h', 'e2_T1', 'e2_T3', 'oi2_T6', 'o3_T3', 'au_T3', 'tr', 'u1_T3', 'uy_T5', 'oe_T1', 'ui_T1', 'o3_T1', 'ay_T3', 'oa_T6', 'oi3_T1', 'ie2_T4', 'uu2_T6', 'j', 'au3_T5', 'ay_T1', 'WB', 'oa_T3', 'o1_T1', 'oi_T4', 'au3_T3', 'ay3_T4', 'o2_T1', 'ay3_T1', 'o1_T6', 'ai_T3', 'ua2_T1', 'e1_T1', 'ua_T3', 'ai_T2', 'oa_T2', 'ay3_T5', 'u2_T6', 'ua2_T6', 'g', 'eo_T4', 'a3_T4', 'oa_T1', 'ao_T6', 'a1_T4', 'o2_T2', 'ua_T5', 'ao_T2', 'ieu_T4', 'iu_T4', 'ay3_T2', 'uoi2_T1', 'oi2_T3', 'u1_T1', 'eo_T1', 'o2_T3', 'oe_T6', 'd2', 'ua2_T2', 'ay_T2', 'ui_T4', 't', 'o1_T4', 'ay_T4', 'p', 'o3_T2', 'oe_T4', 'd1', 'ai_T1', 'eu_T6', 'i_T3', 'i_T6', 'oi2_T2', 'oi3_T5', 'u1_T5', 'e2_T6', 'a1_T5', 'ie2_T6', 'o2_T4', 'r', 'o2_T6', 'iu_T3', 'ua_T1', 'ui_T5', 'ieu_T3', 'ph', 'uoi3_T3', 'b', 'a1_T6', 'oa_T5', 'a3_T5', 'e2_T4', 'uoi2_T5', 'eo_T3', 'oi2_T1', 'eu_T4', 'au3_T1', 'm', 'oa_T4', 'uu2_T4', 'v', 'uou_T6', 'eo_T2', 'a2_T6', 'oi3_T3', 'e2_T2', 'ai_T5', 'e1_T6', 'u2_T2', 'ie2_T3', 'th', 'uu2_T1', 'ao_T1', 'oe_T2', 'ui_T6'}
Traceback (most recent call last):
  File "/home/amin/anaconda3/envs/aligner/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/amin/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 339, in main
    run_align_corpus(args, unknown, acoustic_languages)
  File "/home/amin/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 159, in run_align_corpus
    align_corpus(args, unknown_args)
  File "/home/amin/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 88, in align_corpus
    acoustic_model.validate(dictionary)
  File "/home/amin/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/models.py", line 152, in validate
    raise (PronunciationAcousticMismatchError(missing_phones))
montreal_forced_aligner.exceptions.PronunciationAcousticMismatchError: There were phones in the dictionary that do not have acoustic models: au_T4, au_T6, eu_T5, ieu_T5, oe_T5, uoi2_T2, uoi3_T6, uou_T1, uou_T2, uou_T3

Could you please retrain your Vietnamese acoustic model for matching phones.
Thank you

**Comment by NTT123** [comment]
I got similar problem in the past. You can train your own model instead of reusing the pretrained model. Or,

you can replace missing phonemes *au_T4, au_T6, eu_T5, ieu_T5, oe_T5, uoi2_T2, uoi3_T6, uou_T1, uou_T2, uou_T3* by similar sounding phonemes (for example, same phone but with different tone) in the dictionary file.

**Comment by namdn** [comment]
thank @NTT123
How can I train myself acoustic model?

**Comment by NTT123** [comment]
You can see an training example at https://montreal-forced-aligner.readthedocs.io/en/latest/example.html#example-1-aligning-librispeech-english for v2 and 
at https://montreal-forced-aligner.readthedocs.io/en/stable/example.html#alignment for v1.

**Comment by namdn** [comment]
Yes, i do the same. But follow the link, if you want to train the dictionary you need a g2p model, or if you want to train g2p model you need a dictionary. And both of them all use the new phones not in acoustic model.
So how can we rebuild acoustic model with new phones in the dictionary and g2p model.
Thank you

**Comment by NTT123** [comment]
If I recall correctly, you can use the dictionary (lexicon file) generated by the pretrained g2p model. And you only need to train a new acoustic model using `.wav files`  + `.txt transcript files` + `lexicon file` generated by the pretrained g2p model.

To generate the lexicon file, see https://montreal-forced-aligner.readthedocs.io/en/stable/dictionary_generating.html

**Comment by namdn** [comment]
thank you. I generated the lexicon successfully,  could you please help me to generate the new acoustic model. I don't see it in the document

**Comment by NTT123** [comment]
Please look at https://montreal-forced-aligner.readthedocs.io/en/stable/aligning.html#align-using-only-the-data-set
with the `-o` option.

**Comment by namdn** [comment]
thank you very much

**Comment by mmcauliffe** [comment]
This shouldn't be an issue any more as there are newly trained acoustic models and dictionaries that should be better than the 1.0 ones: https://mfa-models.readthedocs.io/en/latest/index.html
