### ISSUE TITLE
MFA 2.0 too slow compared to 1.0.1

### ISSUE THREAD

**Issue by weixsong** [MontrealCorpusTools/Montreal-Forced-Aligner#249]
Hi, 

I tried MFA 2.0, but found it was too slow, it spends really a long time on "INFO - Setting up corpus information..."

Is there any trick to speed up the process?

**Comment by mmcauliffe** [comment]
Hm, interesting, it should be a lot faster, but as a result of using multiprocessing.  Couple of questions:

1. What is the command you're running?
2. What's the data set up? Number of speakers and utterances?
3. What platform, number of cores, etc?

One workaround you can do is using a config file with `use_mp: false` at the top for something like https://montreal-forced-aligner.readthedocs.io/en/latest/configuration_align.html#default-training-config-file.  You can see some example configs with the option in the tests folder: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/tests/data/configs/basic_train_config.yaml (these are both for training, but you can take a look at just alignment configs if you're running just `mfa align`).  Multiprocessing is inconsistent on Travis, so the test configs all have it disabled.

**Comment by binglel** [comment]
> Hi,
> 
> I tried MFA 2.0, but found it was too slow, it spends really a long time on "INFO - Setting up corpus information..."
> 
> Is there any trick to speed up the process?

Hi, Can you find the reason for the slow with MFA 2.0?

**Comment by Rashi2011** [comment]
hii,
MFA validation and alignment both taking a lot of time to process that it never completes , I am using LJspeech dataset with lexicon dictionary.
My command is mfa align ./ljspeech/LJSpeech-1.1.0/wavs ./montreal-forced-aligner/pretrained_models/librispeech-lexicon.txt ./montreal-forced-aligner/pretrained_models/english.zip ./TextGrid -j 40
It only reaches log = first pass alignment

**Comment by shtoshni** [comment]
Hi, 

Any updates on this thread?
MFA aligner is pretty slow for me as well. I'm trying to do the alignment for Librispeech.

**Comment by Keeyahto** [comment]
I have the same problem. I installed Montreal Forced Aligner 2.0 rc5 on Anaconda, python version 3.10, and my execution process is very slow, although I was running mfa -j 6. My processor is also idle for 80%

**Comment by shtoshni** [comment]
I'm at the Textgrid export step and it takes forever there for some reason. I timed the function of interest [export_grid](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/f0bdc02294f5df47f26890bf126240a315ab2dbf/montreal_forced_aligner/textgrid.py#L115) where the process is apparently taking only a few milliseconds. I'm trying to see if downgrading helps with this issue because the title suggests that this wasn't a problem in v1.0.1.

**Comment by Keeyahto** [comment]
I think that the function parallelizing threads does not create new processes, although the use_mp flag is True. I figured it out from this snippet of code, which, as far as I understand, should create these files by the number of threads. 
![image](https://user-images.githubusercontent.com/57627790/163437327-5f7c4d67-e77d-4db1-bb49-6f183eefd63e.png)

```
def alignment_extraction_arguments(self) -> List[AlignmentExtractionArguments]:
        arguments = []
        for j in self.jobs:
            arguments.append(
                AlignmentExtractionArguments(
                    j.name,
                    getattr(self, "db_path", ""),
                    os.path.join(self.working_log_directory, f"get_phone_ctm.{j.name}.log"),
                    self.alignment_model_path,
                    round(self.frame_shift / 1000, 4),
                    self.cleanup_textgrids,
                    j.construct_path_dictionary(self.working_directory, "ali", "ark"),
                    j.construct_path_dictionary(self.data_directory, "text", "int.scp"),
                )
            )

        return arguments
```
The function running 80 hours for my data is found in the file https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/montreal_forced_aligner/alignment/base.py. This is the _collect_alignments function

**Comment by shtoshni** [comment]
Interesting. This isn't the bottleneck for me. I'm getting stuck on the step "Exporting TextGrids to " which follows alignment collection step. Multiprocessing is happening there because I do see logs corresponding to the different processes. So can't really pinpoint what's the reason!

**Comment by mmcauliffe** [comment]
This should be a lot faster now on the latest release 2.0.0rc5.  I haven't benchmarked it in a while, but it should be quite a bit optimized over the beta versions.  Can I get some more details on the corpus set ups you have?  

Namely:

* How many speakers do you have? How many files per speaker?
* What's the exact command you're using?
* If you're using Librispeech/some other corpus, what steps did you take to convert it to an MFA input format? What does the directory structure for it look like?
* Any other details about your set up?

**Comment by Keeyahto** [comment]
@mmcauliffe 
- There is 1 speaker in my corpus and 17990 files for it.
- I use mfa align -j 6 --clean corpus_folder dictionary_path acoustic_model_path output_directory
- My data looks like a file directory containing pairs of files of the form .wav and .txt. 
- I made the pronunciation probability for the pretrained dictionary. At the same time, I also trained a new acoustic model on my data, as it was not available for my language.

**Comment by shtoshni** [comment]
@mmcauliffe 

I'm working with Librispeech 960h

> How many speakers do you have? How many files per speaker?
Number of speakers = 2484, Number of files = 292367, Average number of files per speaker =  117.7

> What's the exact command you're using?
`mfa align mfa_960h/ dictionary/librispeech-lexicon.txt english ../mfa_test_aligned -j 20 & 
`

> If you're using Librispeech/some other corpus, what steps did you take to convert it to an MFA input format? What does the directory structure for it look like?
I adapted [this script](https://github.com/MontrealCorpusTools/MFA-reorganization-scripts/blob/main/Librispeech/reorganize_librispeech.py) to convert the original flac files to wav. 

Directory structure looks like:
PARTITION/ID/*.{lab, wav}

For eg, dev-clean/1272/1272-128104-0000.{lab, wav}


> Any other details about your set up?
I'm using the latest dev version.
mfa version == 2.0.0rc6.dev0+gf0bdc02.d20220414

It's predicting multiple days (~2 days) for even train-clean-100.

**Comment by mmcauliffe** [comment]
@Keeyahto So MFA's optimizations are centered around speakers, with each speaker assigned to a single job, so that's why it's only using 1 core.  If you have speaker info, then splitting the corpus up into sub directories or specifying numbers of characters to identify speakers with `-s` would work.  If you don't have any speaker information at all, then you can try splitting up each file into its own directory (or use `-s 100` which would say each file name corresponds to a speaker), but I'm not sure what the alignment performance is going to be like.

**Comment by mmcauliffe** [comment]
@shtoshni Hmm, ok that should definitely take like max 2 hours to train on all 960h.  Can you see if there's any errors in the log files for the final alignments?  It could be that something threw an error that wasn't properly handled by MFA.  I'll try to take a look over the code and see if there's any way that queues and processes aren't joining correctly after errors.

**Comment by shtoshni** [comment]
@mmcauliffe I didn't see any errors. I was able to align smaller datasets in a couple of hours.

**Comment by kdonbekci** [comment]
Having similar problem to @shtoshni with the 2.0.0rc5. 
Running on TIMIT by running
```
mfa align --clean -j 8 output/timit english_us_mfa  english_mfa /tmp/mfa-timityogski9x
```
blazes through all the steps until `Exporting TextGrids to ...` step. First TQDM bar fills in 5 seconds, but the second bar completes in 15 minutes for such a small dataset.

`htop` shows 8 CPU cores being utilized at 100%. 
Problem appears to be IO Bottleneck, running `iotop`, I get
```
Total DISK READ: 4.5 G/s
```
which is an immense amount of READ sustained for such a long time. I have a nvme device so I am impressed it can sustain such high speeds but this is probably the source of the bottleneck.

@shtoshni could you try running `iotop` as well during the `Exporting TextGrids` phase?

**Comment by kdonbekci** [comment]
I'm not too familiar with sql so I'm not going to try to fix this, but for anyone looking for a quick hack while someone from the dev team takes a look at this can do the following.
With this fix, TIMIT completes in about 1 minute rather than 17.
1. In `corpus/db.py`, mark `utterance_id` in both `WordInterval` and `PhoneInterval` as below.
```
utterance_id = Column(Integer, ForeignKey("utterance.id"), nullable=False, index=True)
```
2. Replace `construct_output_tiers(...)` in `alignment/multiprocessing.py` with below.
```
def construct_output_tiers(
    session: Session, file_id: int
) -> Dict[str, Dict[str, List[CtmInterval]]]:
    """
    Construct aligned output tiers for a file

    Parameters
    ----------
    session: Session
        SqlAlchemy session
    file_id: int
        Integer ID for the file

    Returns
    -------
    Dict[str, Dict[str,List[CtmInterval]]]
        Aligned tiers
    """
    data = {}
    utterances = (
        session.query(Utterance)
        .filter_by(file_id=file_id)
        .options(
            # subqueryload(Utterance.word_intervals), 
            # subqueryload(Utterance.phone_intervals),
            joinedload(Utterance.speaker).load_only(Speaker.name),
        )        
    )
    
    for utt in utterances:
        word_intervals = session.query(WordInterval).filter_by(utterance_id=utt.id)
        phone_intervals = session.query(PhoneInterval).filter_by(utterance_id=utt.id)
        if utt.speaker.name not in data:
            data[utt.speaker.name] = {"words": [], "phones": []}
        # for wi in utt.word_intervals:
        for wi in word_intervals:
            data[utt.speaker.name]["words"].append(CtmInterval(wi.begin, wi.end, wi.label, utt.id))

        # for pi in utt.phone_intervals:
        for pi in phone_intervals:
            data[utt.speaker.name]["phones"].append(
                CtmInterval(pi.begin, pi.end, pi.label, utt.id)
            )
    return data
```

**Comment by dunky11** [comment]
@kdonbekci thanks, that worked wonders. It changed the time spend on the step from 2 hours to ~10 seconds.
