### ISSUE TITLE
After align , got unaligned.txt

### ISSUE THREAD

**Issue by zhangsanfeng86** [MontrealCorpusTools/Montreal-Forced-Aligner#255]
I have finished run "mfa train .....",
After that ,in TextGrid folder, got a "unaligned.txt"
How to align this items?

**Comment by mmcauliffe** [comment]
So it depends.  I would recommend running the validation utility: https://montreal-forced-aligner.readthedocs.io/en/latest/data_validation.html and see if it detects any issues.  If that doesn't report anything, some further questions:

* What size of data set are you trying to train on?
* Could you try using a pretrained model (https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html)?  You might have better performance there, especially if your dataset is smaller.

**Comment by zhangsanfeng86** [comment]
ok
Thank you !
I'll try it.
