### ISSUE TITLE
Google colab notebook to align LJSpeech english dataset

### ISSUE THREAD

**Issue by NTT123** [MontrealCorpusTools/Montreal-Forced-Aligner#256]
Hi,

I did prepare a working script to forced align LJSpeech dataset (for my personal purpose of building a TTS system), that I want to share with you.

https://colab.research.google.com/drive/1quZcsBgh98YfTqfVGhaMBXG5-DxLBBbY?usp=sharing

This script will automatically install MFA, download LJS dataset, normalize audio clips, prepare transcript files, and finally forced align the transcript and speech. The whole script takes 2 hours to run.

I hope this is helpful for some of you!

**Comment by mmcauliffe** [comment]
Oh cool! Would it be alright to link to it from the documentations as an example?

**Comment by NTT123** [comment]
Sure! However, for better transparency can you link to this gist instead?

https://gist.github.com/NTT123/12264d15afad861cb897f7a20a01762e

It is the same notebook with revision history.

**Comment by jodumagpi** [comment]
Will this work with other datasets?

**Comment by Aloento** [comment]
`pip install pgvector`
