### ISSUE TITLE
There was a problem locating libopenblas.so.0

### ISSUE THREAD

**Issue by FreSch1848** [MontrealCorpusTools/Montreal-Forced-Aligner#259]
Hi,
I'm new here and I'm testing the MFA for the first time today. I have already installed the MFA according to the instructions and so far there have been no problems.
Now I just want to test Example 1: Aligning LibriSpeech (English) from the Docs. I entered the appropriate command for this:
mfa align /path/to/librispeech/dataset /path/to/librispeech/lexicon.txt english ~/Documents/aligned_librispeech
However, I then get the following error:

![Screenshot from 2021-03-24 15-56-10](https://user-images.githubusercontent.com/81155076/112332398-fe680380-8cb9-11eb-96f4-684ae96239be.png)

But when I look in the Anaconda Navigator, the packages "openblas" and "libopenblas" are installed for the environment "aligner".

![Screenshot from 2021-03-24 16-02-25](https://user-images.githubusercontent.com/81155076/112332892-69b1d580-8cba-11eb-838e-e6309d75f878.png)

Can someone help me please?

**Comment by mmcauliffe** [comment]
Hm, I'm not too sure why openblas isn't available on the path if you have the package installed in the environment.  I'm not familiar with that interface, but one thing you can try is to run `sudo apt-get install libopenblas-base` and see that gets you past it.  You could also try finding the libopenblas.so.0 and making sure its containing foldder is on your `LD_LIBRARY_PATH`, but that might be a bit more fragile of a solution.

**Comment by FreSch1848** [comment]
Thanks, your first tip seems to have solved my problem.

**Comment by tshmak** [comment]
I also came across this problem. May I suggest the authors update the [installation instructions](https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html) with 
```
conda env config vars set LD_LIBRARY_PATH=$CONDA_PREFIX/lib
```
to update LD_LIBRARY_PATH to point to the conda library?
