### ISSUE TITLE
Source for the phone set used by the Mandarin pretrained model?

### ISSUE THREAD

**Issue by AimainaHito** [MontrealCorpusTools/Montreal-Forced-Aligner#260]
I'm currently using alignments computed by the pretrained Mandarin acoustic model in my research and am wondering if there is a reference for the phone set used by the model. It is listed as "GlobalPhone" next to the acoustic model and "Pinyin phones" next to the G2P models on the website, but so far I couldn't find any sources mentioning the phone set by searching for these terms.
Any help in tracking down a reference to this phone set would be appreciated.

**Comment by mmcauliffe** [comment]
Ah thanks, it should be pinyin based phones for the acoustic model as well. GlobalPhone processed the pinyin transcription into phones and associated tones with the vowel in the nucleus.  I'll update the docs to ensure it's consistent.
