### ISSUE TITLE
Error when trying out the Librispeech alignment example

### ISSUE THREAD

**Issue by tshmak** [MontrealCorpusTools/Montreal-Forced-Aligner#261]
I'm trying out MFA with the [Librispeech alignment example](https://montreal-forced-aligner.readthedocs.io/en/latest/example.html), and I'm running into an error. I installed using `pip install montreal-forced-aligner` following the instructions [here](https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#installation) and the version is `2.0.0a8`. 

Here's my directory: 
```
drwxrwxr-x 1 tshmak tshmak   12 Dec 13  2019 Librispeech/
-rw-r--r-- 1 tshmak tshmak 5.4M Mar 25 16:14 librispeech-lexicon.txt
-rw-r--r-- 1 tshmak tshmak 107M Mar 25 16:13 Librispeech.zip
drwxrwxr-x 1 tshmak tshmak    0 Mar 25 16:16 test/
```
where `Librispeech` and `librispeech-lexicon.txt` were obtained following the instructions [here](https://montreal-forced-aligner.readthedocs.io/en/latest/example.html#example-1-aligning-librispeech-english). 

I ran: 
```
$ mfa train Librispeech librispeech-lexicon.txt test
```
and got this error: 

```
All required kaldi binaries were found!
/home/tshmak/Documents/MFA/Librispeech/train_and_align.log
WARNING - WARNING: Using old temp directory, this might not be ideal for you, use the --clean flag to ensure no weird behavior for previous versions of the temporary directory.
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 3, average number of utterances per speaker: 122.33333333333333
INFO - Number of speakers in corpus: 3, average number of utterances per speaker: 122.33333333333333
INFO - Parsing dictionary without pronunciation probabilties without silence probabilties
INFO - Creating dictionary information...
INFO - Setting up training data...
Generating base features (mfcc)...
INFO - Initializing training for mono...
WARNING - Subset specified is larger than the dataset, using full corpus for this training block.
INFO - Generating base features (mfcc)...
Traceback (most recent call last):
  File "/mnt/nas2/tshmak/WORK/Projects/TTS/FanoFastSpeech2/conda_gpu2_MFA/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/mnt/nas2/tshmak/WORK/Projects/TTS/FanoFastSpeech2/conda_gpu2_MFA/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 341, in main
    run_train_corpus(args)
  File "/mnt/nas2/tshmak/WORK/Projects/TTS/FanoFastSpeech2/conda_gpu2_MFA/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 143, in run_train_corpus
    align_corpus(args, unknown_args)
  File "/mnt/nas2/tshmak/WORK/Projects/TTS/FanoFastSpeech2/conda_gpu2_MFA/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 95, in align_corpus
    a.train()
  File "/mnt/nas2/tshmak/WORK/Projects/TTS/FanoFastSpeech2/conda_gpu2_MFA/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 78, in train
    trainer.init_training(identifier, self.temp_directory, self.corpus, self.dictionary, previous)
  File "/mnt/nas2/tshmak/WORK/Projects/TTS/FanoFastSpeech2/conda_gpu2_MFA/lib/python3.8/site-packages/montreal_forced_aligner/trainers/monophone.py", line 65, in init_training
    self._setup_for_init(identifier, temporary_directory, corpus, dictionary)
  File "/mnt/nas2/tshmak/WORK/Projects/TTS/FanoFastSpeech2/conda_gpu2_MFA/lib/python3.8/site-packages/montreal_forced_aligner/trainers/base.py", line 155, in _setup_for_init
    self.feature_config.generate_features(self.corpus, logger=self.logger)
  File "/mnt/nas2/tshmak/WORK/Projects/TTS/FanoFastSpeech2/conda_gpu2_MFA/lib/python3.8/site-packages/montreal_forced_aligner/features/config.py", line 243, in generate_features
    self.generate_base_features(corpus, logger=logger, compute_cmvn=cmvn)
  File "/mnt/nas2/tshmak/WORK/Projects/TTS/FanoFastSpeech2/conda_gpu2_MFA/lib/python3.8/site-packages/montreal_forced_aligner/features/config.py", line 180, in generate_base_features
    corpus.combine_feats()
  File "/mnt/nas2/tshmak/WORK/Projects/TTS/FanoFastSpeech2/conda_gpu2_MFA/lib/python3.8/site-packages/montreal_forced_aligner/corpus/base.py", line 437, in combine_feats
    with open(lengths_path, 'r') as inf:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tshmak/Documents/MFA/Librispeech/corpus_data/split3/utterance_lengths.0.scp'
```

Your help is much appreciated.

**Comment by mmcauliffe** [comment]
Thanks for this, I'll try to reproduce it tonight and see if I can get a fix out asap.

**Comment by mmcauliffe** [comment]
It seems to be working correctly for me.  There is a warning at the top about an old temp directory.  Do you think you can rerun the command with the `--clean` flag?  `mfa train Librispeech librispeech-lexicon.txt test --clean`

**Comment by tshmak** [comment]
Thanks for this. In fact, I found that running the above was ok within a docker container. So do you have any ideas on where it might have gone wrong? I noticed that the `Documents/MFA/Librispeech/corpus_data/` folder does contain `utterance_lengths.scp` file (although it's 0 byte). It just wasn't created in the `split3` sub-folder. I tried running in sudo (outside docker), but it didn't help.

**Comment by tshmak** [comment]
On another note, I noticed that even within docker, I had to do `export LD_LIBRARY_PATH=$CONDA_PREFIX/lib` to add the `libopenblas.so.0` into the shared library path. I suggest adding this to the installation instruction.

**Comment by joan126** [comment]
@tshmak I met same issue with you, have you solved this issue?

**Comment by tshmak** [comment]
Here's a Dockerfile that can produce a working environment: 
```
FROM continuumio/anaconda3:2020.11 AS base
RUN conda install openblas python=3.8 openfst pynini ngram baumwelch -c conda-forge 
RUN pip install pyqt5==5.12 
RUN pip install pyqtwebengine==5.12
RUN pip install montreal-forced-aligner
RUN apt-get -y install libsndfile1
RUN mfa thirdparty download
```

**Comment by damiankwasnyr** [comment]
Hey, same issue here! And I am quite close to spotting the underlying reason. Looking at logs (which are quite randomly scattered through the `Documents/MFA` directory ... ) it looks that the way the installation is performed now does not assure that all the dynamically linked libraries required for kaldi are there, for example:
```
GCC/4.8.4/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found
```
(but there are a few more depending on kaldi binary used, most do not work, like compute-feats etc).
@mmcauliffe you may want to look into that. I remember version 1 did not have these kind of problems. I am not expert on C++ but I think it should be possible to link all there is required statically into the binaries you are downloading, not sure though.

**Comment by damiankwasnyr** [comment]
I guess the problem originates here:

```
The prebuilt Kaldi binaries were built on Ubuntu 18.04 and MacOSX 10.15 (Catalina). If you’re using an older version of either of those, follow the instructions in Building platform-specific binaries from scratch.
```

Maybe it is a good idea to mention it in the beginning of the installation process or where downloading the binaries takes place. Not sure for others, nut I would just go through the "all platforms" process and would never scroll down as I would generally not be interested in compiling the binaries myself. I managed to make it work within a kaldi docker container.

**Comment by mmcauliffe** [comment]
Moved the note about versions higher up in installation.
