### ISSUE TITLE
setting the beam width

### ISSUE THREAD

**Issue by Sixtease** [MontrealCorpusTools/Montreal-Forced-Aligner#262]
Hello. This is more of a question than an issue:

I want to use the aligner to tell correct and erroneous transcripts apart. I thought with a properly set beam width, unlikely transcripts could be rejected. Do you think this would work? How would you recommend setting the beam width? I guess it should be proportional to the audio length, right?

Thank you for insights

**Comment by mmcauliffe** [comment]
So this is more in the realm of the validator utility: https://montreal-forced-aligner.readthedocs.io/en/latest/data_validation.html, it does basic monophone training as part of it that can capture some of these issues.  There's a flag for testing transcriptions with a pretrained acoustic model as well, where it'll use a basic unigram language model with common words across the corpus and all the words in the utterance transcription to generate a transcript, that might be useful too, but I've had only limited success with it so far.
