### ISSUE TITLE
AttributeError: module 'pynini' has no attribute 'acceptor'

### ISSUE THREAD

**Issue by FreSch1848** [MontrealCorpusTools/Montreal-Forced-Aligner#264]
Hi,
I'm new here and I'm still testing the Examples of the MFA-Documentation. The first example now works fine after solving a problem (see issue #259).
Now I tried to run Example 2: Generate Mandarin dictionary from the Docs. I followed the first three instructions and then entered the given command:
mfa g2p mandarin_pinyin_g2p /path/to/mandarin/dataset /path/to/save/mandarin_dict.txt
However, I then get the following error:

![Screenshot from 2021-03-30 14-20-52](https://user-images.githubusercontent.com/81155076/112990158-06b2b980-9166-11eb-8c58-fc64f9ec6ffa.png)

I don't understand what the error message exactly means or how I can fix the error. Could anyone help me, please?

**Comment by FreSch1848** [comment]
I am just seeing that issue #258 is already addressing the same problem. However, the already given tip from @mmcauliffe doesn't work for me.

**Comment by FreSch1848** [comment]
@mmcauliffe or anybody else, do you have another advice for me please?

**Comment by mmcauliffe** [comment]
Can you paste the output of `conda list` once you've activated the aligner environment?  Pynini should be at 2.1.4 to fix this issue, so if the upgrade command isn't working, this would reveal that.

**Comment by FreSch1848** [comment]
Apparently Pynini is at 2.1.4, but the problem is still there.

![Screenshot from 2021-04-15 09-38-20](https://user-images.githubusercontent.com/81155076/114832890-4a94f800-9dcf-11eb-81a9-0adb5a68ae7c.png)

**Comment by FreSch1848** [comment]
I just read your comment on Issue #251. That's why I also tried the pip install montreal-forced-aligner -U command and now Example 2 works. However, Example 3 still comes up with the following error FileNotFoundError: [Errno 2] No such file or directory: ''

![Screenshot from 2021-04-15 10-05-35](https://user-images.githubusercontent.com/81155076/114836869-60a4b780-9dd3-11eb-8bcc-3e0317d61173.png)

I have not changed the directory in the commands from Examples 2 and 3. So I cannot explain the error.

**Comment by mmcauliffe** [comment]
I've run into this as well, have a fix for it in the pipeline. In the meantime, you can work around it by specifying the full absolute path for the output g2p model.

**Comment by FreSch1848** [comment]
Okay, if you specify the entire storage path ('/path/to/mandarin_test_model.zip') instead of the file name ('mandarin_test_model.zip') at the end, Example 3 works wonderfully for me.

@mmcauliffe, thank you for your help.
