### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'path/Documents/MFA/AISHELL-3/corpus_data/split3/utterance_lengths.0.scp'

### ISSUE THREAD

**Issue by CrazyCharles6** [MontrealCorpusTools/Montreal-Forced-Aligner#267]
when i want to use 'mfa train ', there is some errors. how can i solve this error?

**Comment by Olabiyisam** [comment]
Hello @CrazyCharles6  were you able to resolve this as I am having the same error
