### ISSUE TITLE
¿Spanish dictionaries?

### ISSUE THREAD

**Issue by Daniel29234** [MontrealCorpusTools/Montreal-Forced-Aligner#269]
Is it possible to add a dictionary for the Spanish language?

**Comment by mmcauliffe** [comment]
There is a G2P model available on https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html#pretrained-g2p that can be used to generate a dictionary for use with the pretrained Spanish acoustic model.  There is also a IPA based dictionary available on https://github.com/kylebgorman/wikipron/tree/master/data/scrape that might be useful depending on what you're using it for.

**Comment by MiClobiMC** [comment]
Does the IPA dictionary work? https://raw.githubusercontent.com/kylebgorman/wikipron/master/data/scrape/tsv/spa_latn_la_phonemic_filtered.tsv

**Comment by Daniel29234** [comment]
I do not understand anything. I meant that they will add the Spanish language in this section https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html#available-pronunciation-dictionaries

**Comment by mmcauliffe** [comment]
Closing this as there are new Spanish pronunciation dictionaries and acoustic models released: https://mfa-models.readthedocs.io/en/latest/dictionary/index.html
