### ISSUE TITLE
Adding a word (<unk>) to dictionary possible? 

### ISSUE THREAD

**Issue by ccp388** [MontrealCorpusTools/Montreal-Forced-Aligner#272]
I am trying to align an audio transcription which repeatedly features the word "ninja". I have tried to add this word along with its phonemes to the librispeech-lexicon file and re-save however it didn't seem to register. Typically, I could just cross reference the "< unk >" from the aligned transcription with "ninja" in the normal transcription and replace it where appropriate. However, it seems like recently that "ninja" is having a more disruptive effect in the transcription such that the following few words can be mixed up. The program seems to refuse to accept "ninja" as < unk > but instead tries to split "ninja" up into different words or match it with words coming before or after. 

Does anyone have ideas for getting around this? Any simple solution I am missing? 

Thanks!!

**Comment by mmcauliffe** [comment]
It should be available as a pronunciation when you re-save.  I would double check that you're editing the same dictionary that the aligner is using, and also try re-running with the `--clean` flag to clear out temporary files, since MFA caches things like the dictionary/training graphs to speed things up.

**Comment by ccp388** [comment]
> It should be available as a pronunciation when you re-save. I would double check that you're editing the same dictionary that the aligner is using, and also try re-running with the `--clean` flag to clear out temporary files, since MFA caches things like the dictionary/training graphs to speed things up.

Thank you for answering! I tried with the --c flag and it worked!
