### ISSUE TITLE
There was an issue importing Pynini, please ensure that it is installed.

### ISSUE THREAD

**Issue by Dallak** [MontrealCorpusTools/Montreal-Forced-Aligner#273]
I'm using the Windows Subsystem for Linux and trying to go through [Example 2](https://montreal-forced-aligner.readthedocs.io/en/latest/example.html#example-2-generate-mandarin-dictionary) in the documentation. I've already installed `pynini-2.1.4` following [these steps](https://stackoverflow.com/questions/57898360/how-can-i-install-and-use-pynini-on-windows-10), and `openfst-1.8.1` is also installed. But when I ran the following code: 

`mfa g2p mandarin_pinyin_g2p /home/dallak/.local/lib/python3.8/site-packages/montreal_forced_aligner/mandarin_example /home/dallak/.local/lib/python3.8/site-packages/montreal_forced_aligner/mandarin_dict.txt`

I get this message:

`There was an issue importing Pynini, please ensure that it is installed. If you are on Windows, please use the Windows Subsystem for Linux to use g2p functionality.`

Not sure if there is something else missing, but I would appreciate any advice.

**Comment by mmcauliffe** [comment]
I would double check the conda environment you're in for running MFA is the same as the one that has pynini installed.  `conda list` should have pynini==2.1.4.  You can also verify that it's installed by running `python` and then `import pynini` for that conda environment.

**Comment by Dallak** [comment]
To avoid any potential installation errors, I re-did [the installation procedures](https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#installation) and created a new environment called 'alignr' in miniconda3>envs. This didn't help in that running the following code inside the activated environment:

`mfa g2p mandarin_pinyin_g2p /home/dallak/miniconda3/envs/alignr/lib/python3.8/site-packages/montreal_forced_aligner/mandarin_example /home/dallak/miniconda3/envs/alignr/lib/python3.8/site-packages/montreal_forced_aligner/mandarin_dict.txt`

still produces this issue:

`There was an issue importing Pynini, please ensure that it is installed. If you are on Windows, please use the Windows Subsystem for Linux to use g2p functionality.`
 
However, when I run 'conda list', I get:

`# packages in environment at /home/dallak/miniconda3/envs/alignr:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
baumwelch                 0.3.6                h4bd325d_0    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
expat                     2.3.0                h9c3ff4c_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      2.001                hab24e00_0    conda-forge
font-ttf-source-code-pro  2.030                hab24e00_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gdk-pixbuf                2.42.6               h04a7f16_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.47.1               hebd9034_0    conda-forge
gtk2                      2.24.33              hab0c2f8_0    conda-forge
gts                       0.7.6                h64030ff_2    conda-forge
harfbuzz                  2.8.0                h83ec7ef_1    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgd                     2.3.2                h78a0170_0    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libglib                   2.68.1               h3e27bee_0    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libopenblas               0.3.13          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
librsvg                   2.50.3               hfa39831_1    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libtool                   2.4.6             h58526e2_1007    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.0                h3452ae3_0    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.10               h72842e0_4    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
ngram                     1.3.13               h4bd325d_0    conda-forge
openblas                  0.3.13          pthreads_h4748800_0    conda-forge
openfst                   1.8.1                h4bd325d_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pango                     1.42.4               h69149e4_5    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pynini                    2.1.4            py38h1fd1430_0    conda-forge
python                    3.8.8           hffdb5ce_0_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
sqlite                    3.35.4               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.0                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge`

Also here is the output of running `python` and then `import pynini`.

`python`
`Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.`

`>>> import pynini`
`>>>`
`import pynini` did not return anything. I feel that it is a silly mistake that I'm unable yet to figure it out.

**Comment by mmcauliffe** [comment]
Weird. So here's the code block that sets G2P_ENABLED to false if there's an ImportError:

```
    import pynini
    from pynini import Fst, TokenType
    from pynini.lib import rewrite
```

Can you try running the other import commands and see if they're throwing ImportErrors?

**Comment by Dallak** [comment]
No errors at all.

`>>> import pynini`
`>>> from pynini import Fst, TokenType`
`>>> from pynini.lib import rewrite`
`>>>`

**Comment by mmcauliffe** [comment]
Very odd, so more specifically it's this code here that's triggering it: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/montreal_forced_aligner/command_line/mfa.py#L334.

Can you try doing a `which mfa` and see where it's been installed? I feel like it must be trying to run mfa from a location that doesn't have pynini rather than the current environment.  Another idea would be to do `pip uninstall montreal_forced_aligner` until pip says it isn't found, because it seems like it's just not using the correct location?

**Comment by Dallak** [comment]
Yes! It was indeed a path issue. When I ran `which mfa`, it returned a path different from where pynini==2.1.4 was installed. So I followed your instruction and uninstalled MFA. Now Examples 2 & 3 are working.
Thank you!
