### ISSUE TITLE
about handling punctuation

### ISSUE THREAD

**Issue by keonlee9420** [MontrealCorpusTools/Montreal-Forced-Aligner#277]
Hi, as the [official document](https://montreal-forced-aligner.readthedocs.io/en/latest/data_format.html#transcription-normalization-and-dictionary-lookup) says
> As part of parsing orthographic transcriptions, punctuation is stripped from the ends of words. In addition, all words are converted to lowercase so that dictionary lookup is not case-sensitive.

, I removed all the punctuation from raw transcriptions (text data). But I'm curious about whether there are differences in aligning (or training) performance between using raw text and punctuation removed text, even with the same lookup dictionary (lexicon.txt). For example, is there any difference between MFA training with input text `"oh yes, they - they, you know, they love her and so i mean..."` and `"oh yes they they you know they love her and so i mean"`?

**Comment by mmcauliffe** [comment]
Nope, no difference between those transcripts.  The only case that might have differences is if a quotation with single quotes is there, since end apostrophes are kept.
