### ISSUE TITLE
Parsing error in dictionary.py while processing devanagari script

### ISSUE THREAD

**Issue by amogh-gulati** [MontrealCorpusTools/Montreal-Forced-Aligner#287]
Hey! while using devanagari script for hindi dataset we observed that " हैं", "हूं" and "हौं" were being mapped to the same phonemes in the Textgrids even when the input dictionary has different phonemes for all of them. 
It seems like the sanitize function in montreal_forced_aligner/dictionary.py (https://github.com/gan-studio/Montreal-Forced-Aligner/blob/027417db978d8ac9074087007119bb9d28db7eba/montreal_forced_aligner/dictionary.py#L49) strips the all above words to "ह"  which causes this error. If I understand it correctly the regex is meant to remove punctuations at the end of the words but is removing more than that from the devanagari script.

**Comment by mmcauliffe** [comment]
I updated the code a bit to expand the punctuation set getting explicitly replaced and also to use regular expressions again. I added some explicit tests for those tokens to ensure it doesn't regress in the future.  Thanks!

**Comment by amogh-gulati** [comment]
Thank you for the additions and the quick response!
