### ISSUE TITLE
MFA treating valid orthographic characters as "punctuation"

### ISSUE THREAD

**Issue by roedoejet** [MontrealCorpusTools/Montreal-Forced-Aligner#290]
Hi @mmcauliffe - thanks for this great tool!

I'm getting a lot of OOVs because it appears that word-final colons and single quotes are being stripped, so while my lexicon has something like `iahotenniéhtén: i a h o d ʌ̃ n i é h d ʌ̃́ː` it doesn't get found by MFA, because it's looking for just `iahotenniéhtén` - is there some way to disable this behaviour or include `:` and `'` as legitimate orthographic characters not to be stripped?

**Comment by mmcauliffe** [comment]
I've added a field to alignment configuration yamls for specifying what characters should be treated as punctuation, so you can either modify the training yaml to have a field like:

```
pronunciation: ".,"
``` 

or pass an argument in via `mfa train ... --punctuation ".,"` should work as well, just supply some string of punctuation that omits the characters that are part of the orthography.  Let me know if you have any issues!

**Comment by phamlehuy53** [comment]
> For 2.0.0a19, I've added a field to alignment configuration yamls for specifying what characters should be treated as punctuation, so you can either modify the training yaml to have a field like:
> 
> ```
> pronunciation: ".,"
> ```
> 
> or pass an argument in via `mfa train ... --punctuation ".,"` should work as well, just supply some string of punctuation that omits the characters that are part of the orthography. Let me know if you have any issues!

With `mfa train ... --punctuation`, I get this error:
```python
INFO - Saved model to /root/vlsp.zip
Traceback (most recent call last):
  File "/opt/conda/envs/torch/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 383, in main
    run_train_corpus(args, unknown)
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 158, in run_train_corpus
    align_corpus(args, unknown_args)
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 115, in align_corpus
    a.export_textgrids(args.output_directory)
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 82, in export_textgrids
    convert_ali_to_textgrids(self.align_config, output_directory, ali_directory, self.dictionary,
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing/alignment.py", line 588, in convert_ali_to_textgrids
    parsed = parse_ctm(word_ctm_path, corpus, dictionary, mode='word')
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/montreal_forced_aligner/textgrid.py", line 40, in parse_ctm
    cur = current_labels[cur_ind]
IndexError: list index out of range
```
Do you have any ideas?

**Comment by mmcauliffe** [comment]
What's the full command you're running?  What version are you running?  Any other notes about what punctuation you're trying to include in the orthography?

**Comment by phamlehuy53** [comment]
> What's the full command you're running? What version are you running? Any other notes about what punctuation you're trying to include in the orthography?

The version is 2.0.0a24
The command is :
```bash
mfa train ./raw_data/vlsp-punc \
lexicon/tts-lexicon-punc.txt \
preprocessed_data/TextGrid/vlsp-punc \
-o /root/tts/vlsp-punc.zip \
-j 32 \
--clean \
--punctuation ".,:;-?!{}[]()\"'"
```
Is it right?
