### ISSUE TITLE
Underscore replaced with dashes in TextGrid filenames

### ISSUE THREAD

**Issue by tshmak** [MontrealCorpusTools/Montreal-Forced-Aligner#293]
I suspect because of https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/266, my new version of MFA creates TextGrid files with my underscores replaced with dashes. Before, it used to be: 

`{speaker}_{utterance}.TextGrid`

Now it's 

`{speaker}-{utterance}.TextGrid`

which is ok. But I think it overdoes it by changing the underscore within {utterance} to dashes also. Or is this necessary?

**Comment by mmcauliffe** [comment]
It was causing some crashes with sorting differences between Kaldi and Python, whereas dashes helped sort it better, but I'll look at restoring the original file name, I agree that it's annoying to get different file names.

**Comment by mmcauliffe** [comment]
This shouldn't be an issue anymore with the shift to using utterance/speaker primary keys.
