### ISSUE TITLE
montreal_forced_aligner.exceptions.KaldiProcessingError: There was one or more errors when running Kaldi binaries.

### ISSUE THREAD

**Issue by turian** [MontrealCorpusTools/Montreal-Forced-Aligner#296]
There is one speaker folder I have that causes the following error:

```
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 616.0
INFO - Parsing dictionary without pronunciation probabilities without silence probabilities
INFO - Creating dictionary information...
INFO - Setting up training data...
INFO - Generating base features (mfcc)...
montreal_forced_aligner.exceptions.KaldiProcessingError: There was one or more errors when running Kaldi binaries.
```

How do I diagnose what file(s) cause this problem? I tried `mfa validate` but it didn't give more information.

My current workaround is just to remove this speaker folder. This workaround is kinda sucky because
a) It was a pain to determine which folder wasn't working
b) I think most (if not all) files in the speaker folder are correct, and it would be tricky to "divide-and-conquer" to figure out what file is tripping up Kaldi.

How do I get more details about the error?

**Comment by tom-huntington** [comment]
Thanks, this happened to me the first first time I ran `mfa align`. But it turned out it was just the wav file.

**Comment by vatnid** [comment]
@tom-huntington Could you elaborate on how you fixed it? I am also having this error and the message is honestly not very descriptive.

**Comment by mmcauliffe** [comment]
Can you paste the output of the `~/Documents/MFA/your-directory/align.log`?  `mfa validate` is error on MFCC generation as well?

**Comment by turian** [comment]
@mmcauliffe I have no align.log file in my runs

**Comment by turian** [comment]
@vatnid If the WAVs are not mono 16-bit WAVs, you get this error. Check using

```
soxi -T *wav
```

**Comment by tom-huntington** [comment]
> @tom-huntington Could you elaborate on how you fixed it? I am also having this error and the message is honestly not very descriptive.

I created a new wav file through a different program

**Comment by neurlang** [comment]
In addition to converting your wavs to 16bit 16KHZ, to pass the error:

 KaldiProcessingError: There were 1 job(s) with errors when running Kaldi binaries.

just run your command in a loop, this error is manifesting randomly.

e.g.

while [ 1 ] ; do /opt/conda/envs/aligner/bin/mfa train --clean --overwrite --debug /dataset/slovak /lexicon.txt ~/out/new_acoustic_model.zip ~/out/corpus_aligned --beam=10000 ; done

I had the error to appear 5 times, after that 6 th run was fine.

**Comment by brisaann** [comment]
> > @tom-huntington Could you elaborate on how you fixed it? I am also having this error and the message is honestly not very descriptive.
> 
> I created a new wav file through a different program

Which program did you use?

**Comment by tom-huntington** [comment]
> > > @tom-huntington Could you elaborate on how you fixed it? I am also having this error and the message is honestly not very descriptive.
> > 
> > 
> > I created a new wav file through a different program
> 
> Which program did you use?

Don't remember, but I use praat, audacity, ffmpeg

**Comment by mmcauliffe** [comment]
This should be fixed with adding ffmpeg as a back up to the conda forge version of sox not being able to handle certain sets of formats.

**Comment by muskanturaha** [comment]
I'm getting the same error I tried both changing the wav to 16bit wav and running in a loop what else can I try?
