### ISSUE TITLE
ERRORS about generating mfcc features(maybe?)

### ISSUE THREAD

**Issue by KinamSalad** [MontrealCorpusTools/Montreal-Forced-Aligner#300]
First, Thank you for your contribution!

I got an error when I train the aligner using my own multi-speaker dataset(in korean)

There was no problem when training for another single speaker dataset (22kHz), but it seems that there is a problem when making the mfcc feature, considering that there is a problem in this dataset (16kHz). But I know that this aligner also supports 16kHz. So I'm not exactly sure what to fix.

I am attaching the following three clues:

**1. DEBUG**

> All required kaldi binaries were found!
> Cleaning old directory!
> /root/Documents/MFA/corpus/train_and_align.log
> WARNING - Running in DEBUG mode, may have impact on performance and disk usage.
> INFO - Setting up corpus information...
> INFO - Number of speakers in corpus: 2841, average number of utterances per speaker: 154.72263287574796
> INFO - Parsing dictionary without pronunciation probabilities without silence probabilities
> INFO - Creating dictionary information...
> INFO - Setting up training data...
> Generating base features (mfcc)...
> INFO - Initializing training for mono...
> Traceback (most recent call last):
>   File "/opt/conda/bin/mfa", line 33, in <module>
>     sys.exit(load_entry_point('Montreal-Forced-Aligner==2.0.0a19', 'console_scripts', 'mfa')())
>   File "/opt/conda/lib/python3.6/site-packages/montreal_forced_aligner/command_line/mfa.py", line 349, in main
>     run_train_corpus(args, unknown)
>   File "/opt/conda/lib/python3.6/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 153, in run_train_corpus
>     align_corpus(args, unknown_args)
>   File "/opt/conda/lib/python3.6/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 105, in align_corpus
>     a.train()
>   File "/opt/conda/lib/python3.6/site-packages/montreal_forced_aligner/aligner/trainable.py", line 80, in train
>     trainer.init_training(identifier, self.temp_directory, self.corpus, self.dictionary, previous)
>   File "/opt/conda/lib/python3.6/site-packages/montreal_forced_aligner/trainers/monophone.py", line 65, in init_training
>     self._setup_for_init(identifier, temporary_directory, corpus, dictionary)
>   File "/opt/conda/lib/python3.6/site-packages/montreal_forced_aligner/trainers/base.py", line 159, in _setup_for_init
>     self.data_directory = corpus.subset_directory(self.subset, self.feature_config)
>   File "/opt/conda/lib/python3.6/site-packages/montreal_forced_aligner/corpus/align_corpus.py", line 521, in subset_directory
>     self.create_subset(subset, feature_config)
>   File "/opt/conda/lib/python3.6/site-packages/montreal_forced_aligner/corpus/align_corpus.py", line 590, in create_subset
>     subset_utts = set(random.sample(larger_subset, subset))
>   File "/opt/conda/lib/python3.6/random.py", line 320, in sample
>     raise ValueError("Sample larger than population or is negative")
> ValueError: Sample larger than population or is negative

**2. train_and_align.log**

> train_and_align - DEBUG -     ERROR (compute-mfcc-feats[5.5]:Read():feat/wave-reader.cc:202) Unexpected byte rate 64000 vs. 16000 * 2 * ^A

Every single wav file output those errors...

**3. wav file description**
Input File     : ‘{FILE_NAME}.wav’
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:04.86 = 77805 samples ~ 364.711 CDDA sectors
File Size      : 156k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM

I hope that the following clues will help you solve the problem.
Thank you.

**Comment by mmcauliffe** [comment]
This looks like there might be something weird with that audio file?  It looks like Kaldi is complaining that the sample rate might be different from the reported one in the headers.  Can you try opening it in some sort of audio editing software to verify that it sounds correct (not pitched up or down) and then try resaving it?

There's nothing that jumps out in the soxi output, for reference this is one of the test files:

```
Input File     : 'tests/data/wav/acoustic_corpus.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:26.72 = 427572 samples ~ 2004.24 CDDA sectors
File Size      : 855k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM
```

**Comment by KinamSalad** [comment]
@mmcauliffe 

I found that the wav file has 512k Bit Rate 

So that formula cannot be satisfied : 
bit rate(512k) != sampling_rate(16k) * BitPerSample(16) * Channel(1)

But structurally, is it possible not to satisfy this formula?

I don't understand how can this error appears:(

My guess is that not only bit rate but also some of the other parameters in the header are lying.

**Comment by KinamSalad** [comment]
@mmcauliffe 

Okay I solve the problem. 

That Just header has wrong info and There is a problem in my audio archive. 

Thank you for your help!

I think you can close the issue
