### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by laurens777** [MontrealCorpusTools/Montreal-Forced-Aligner#301]
Hello all, on a fresh install of Ubuntu 20.04.2 LTS after installing Conda and following the instructions for setting up the Conda environment I run "mfa thirdparty download" I get the following error:
```
0.00B [00:00, ?B/s]
urllib.error.HTTPError: HTTP Error 404: Not Found
```
My python version is Python 3.8.10
MY conda version is conda 4.9.2

Any ideas what might be causing this?

**Comment by mmcauliffe** [comment]
Sorry about that, was doing some housecleaning in a dependent repo earlier today.  This should be fixed now in 2.0.0a20, can you try running `pip install montreal_forced_aligner -U` again?

**Comment by laurens777** [comment]
Thank you, looks like it is all good now. I'll close the issue.

**Comment by mmcauliffe** [comment]
@laurens777 just a note that I discovered a memory leak in 2.0.0a20, so I'd recommend upgrading to the latest version again to fix that.
