### ISSUE TITLE
How to generate TextGrid files?

### ISSUE THREAD

**Issue by dsli208** [MontrealCorpusTools/Montreal-Forced-Aligner#302]
Hi, I'm a first time user of this and I am wondering how to generate TextGrid files as required for `mfa align`.  Currently I only have the audio files (wav/mp3) in my corpus directory to pass in, leading to this error:
```
montreal_forced_aligner.exceptions.CorpusError: There were no sound files found of the appropriate format. Please double check the corpus path and/or run the validation utility (mfa validate).
```
When running `mfa validate`, I see that no sound files are read, but that many are missing subscriptions, even though the files do exist.  I'm not sure how I can generate the TextGrid files; I'm trying to look through the documentation, as well as the `textgrid.py` that I found in this repo, is there any functionality that I can use to generate TextGrid files?

**Comment by nrgslp** [comment]
Do you have orthographic transcriptions for the audio files? A TextGrid is a format for a time-aligned orthographic transcription that can be made manually in the Praat program or can be automated using a tool such as http://timmahrt.github.io/praatIO/praatio/tgio.html.

**Comment by dsli208** [comment]
I eventually was able to resolve, as I had the text in a data file, which I used to generate corresponding `.lab` files

**Comment by mmcauliffe** [comment]
Cool, glad you got it working! I'll close this one, but feel free to open further issues as necessary!

**Comment by utkuturk** [comment]
@dsli208 Thank you for this idea! I was battleing a lot with the 'appropriate' format. Converting TextGrids to `.lab` helped me as well. The TextGrids were generated with `praat-textgrids`

```py
@staticmethod
def create_textgrid(
    filename: str,
    transcription: str,
    wav_path: Path,
    onset_time: Optional[float] = None,
    context_text: str = ""
) -> textgrids.TextGrid:
    # Get audio duration
    audio = AudioSegment.from_file(str(wav_path))
    audio_duration = audio.duration_seconds

    # Determine onset time
    if onset_time is None or np.isnan(onset_time) or onset_time <= 0:
        if onset_time is not None:
            logger.warning(f"Invalid onset for {filename}, using default")
        onset_time = Config.DEFAULT_ONSET

    # Calculate speech end time
    end_time = audio_duration - Config.END_BUFFER

    # Create TextGrid
    tg = textgrids.TextGrid()
    tg.xmin = 0
    tg.xmax = audio_duration

    # Words tier (3 intervals: silence | speech | silence)
    words_tier = textgrids.Tier()
    words_tier.xmin = 0
    words_tier.xmax = audio_duration
    words_tier.extend([
        textgrids.Interval("", 0, onset_time),
        textgrids.Interval(transcription, onset_time, end_time),
        textgrids.Interval("", end_time, audio_duration)
    ])
    tg["words"] = words_tier

    # Context tier
    context_tier = textgrids.Tier()
    context_tier.xmin = 0
    context_tier.xmax = audio_duration
    context_tier.extend([
        textgrids.Interval(context_text, 0, audio_duration)
    ])
    tg["context"] = context_tier

    # Notes tier
    notes_tier = textgrids.Tier()
    notes_tier.xmin = 0
    notes_tier.xmax = audio_duration
    notes_tier.extend([
        textgrids.Interval("", 0, audio_duration)
    ])
    tg["notes"] = notes_tier

    return tg

```
