### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/work/Documents/MFA/LibriTTS/corpus_data/split3/feats.0.scp'

### ISSUE THREAD

**Issue by XXXHUA** [MontrealCorpusTools/Montreal-Forced-Aligner#307]
Hi, i face this error below during using mfa2.0.a21 in CentOS 7.8.5, the opereation is mfa align.

All required kaldi binaries were found!
/home/work/Documents/MFA/LibriTTS/align.log
WARNING - WARNING: Using old temp directory, this might not be ideal for you, use the --clean flag to ensure no weird behavior for previous versions of the temporary directory.
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 40, average number of utterances per speaker: 143.4
INFO - Parsing dictionary without pronunciation probabilities without silence probabilities
INFO - Creating dictionary information...
INFO - Setting up training data...
INFO - Generating base features (mfcc)...
FileNotFoundError: [Errno 2] No such file or directory: '/home/work/Documents/MFA/LibriTTS/corpus_data/split3/feats.0.scp'

I have try some methods metioned in previous issues, but not work in my platform, please help me solve it ? Thanks you very much !!!

**Comment by mmcauliffe** [comment]
Can you take a look in `/home/work/Documents/MFA/LibriTTS/corpus_data/split3/log/make_mfcc.0.log` and attach it/paste it here?  Hard to know what happened, but it's weird that it wasn't caught by the normal error logging.

**Comment by XXXHUA** [comment]
> Can you take a look in `/home/work/Documents/MFA/LibriTTS/corpus_data/split3/log/make_mfcc.0.log` and attach it/paste it here? Hard to know what happened, but it's weird that it wasn't caught by the normal error logging.

Thanks for your relay, the content of make_mfcc.0.log is as follows: 
/home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats)
/home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats)
/home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats)
/home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats)
/home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats)
/home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats)
/home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.23' not found (required by /home/work/Documents/MFA/thirdparty/bin/compute-mfcc-feats)
/home/work/Documents/MFA/thirdparty/bin/copy-feats: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/work/Documents/MFA/thirdparty/bin/copy-feats)
/home/work/Documents/MFA/thirdparty/bin/copy-feats: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/work/Documents/MFA/thirdparty/bin/copy-feats)
/home/work/Documents/MFA/thirdparty/bin/copy-feats: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/work/Documents/MFA/thirdparty/bin/copy-feats)
/home/work/Documents/MFA/thirdparty/bin/copy-feats: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/work/Documents/MFA/thirdparty/bin/copy-feats)
/home/work/Documents/MFA/thirdparty/bin/copy-feats: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/work/Documents/MFA/thirdparty/bin/copy-feats)
/home/work/Documents/MFA/thirdparty/bin/copy-feats: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/work/Documents/MFA/thirdparty/bin/copy-feats)
/home/work/Documents/MFA/thirdparty/bin/copy-feats: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.23' not found (required by /home/work/Documents/MFA/thirdparty/bin/copy-feats)
/home/work/Documents/MFA/thirdparty/bin/feat-to-len: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/work/Documents/MFA/thirdparty/bin/feat-to-len)
/home/work/Documents/MFA/thirdparty/bin/feat-to-len: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/work/Documents/MFA/thirdparty/bin/feat-to-len)
/home/work/Documents/MFA/thirdparty/bin/feat-to-len: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/work/Documents/MFA/thirdparty/bin/feat-to-len)
/home/work/Documents/MFA/thirdparty/bin/feat-to-len: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/work/Documents/MFA/thirdparty/bin/feat-to-len)
/home/work/Documents/MFA/thirdparty/bin/feat-to-len: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/work/Documents/MFA/thirdparty/bin/feat-to-len)
/home/work/Documents/MFA/thirdparty/bin/feat-to-len: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/work/Documents/MFA/thirdparty/bin/feat-to-len)
/home/work/Documents/MFA/thirdparty/bin/feat-to-len: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.23' not found (required by /home/work/Documents/MFA/thirdparty/bin/feat-to-len)

**Comment by mmcauliffe** [comment]
Ah right, I'll add some parsing for this.  It looks like your OS is not compatible with the version that I used, if you follow the instructions for building Kaldi here: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#building-platform-specific-binaries-from-scratch, once you run the `mfa thirdparty kaldi ...` command, it should run.
