### ISSUE TITLE
Clarify that OpenGRM Baum-Welch is required for mfa train_g2p

### ISSUE THREAD

**Issue by nmfisher** [MontrealCorpusTools/Montreal-Forced-Aligner#308]
Apologies if I missed it, but so far I haven't seen anything in the docs that indicates that OpenGRM Baum-Welch is required to run `mfa train_g2p`. Seems `mfa thirdparty validate` doesn't pick this up if it's missing either.

If you don't have this available, the script will simply freeze at `Calculating alignments...` with no error message. I had to dig into the script to see that `baumwelchtrain` was being called, then I had to guess that this referred to the binary built in http://www.opengrm.org/twiki/bin/view/GRM/BaumWelchDownload.

**Comment by mmcauliffe** [comment]
Closing this as it should be resolved with conda-forge installation.
