### ISSUE TITLE
Dictionary check before calculating MFCCs

### ISSUE THREAD

**Issue by JoFrhwld** [MontrealCorpusTools/Montreal-Forced-Aligner#31]
Calculating MFCCs can take a long time for a large corpus, and it is likely that many users will walk away from the computer before the prompt asking about fixing OOVs, which pauses the alignment.

**Comment by ChristopherLandreth** [comment]
As a temporary workaround, I use a fairly simple shell script to find OOV words  before using mfa_align.  Then generate an OOV dictionary with mfa_generate_dictionary or phonetisaurus-g2pfst in the $MFAPATH/lib/thirdparty/bin folder.  Then sort these back into the main dictionary and do the alignment on the large corpus, which no longer has OOV words.  Will share this if you want.
