### ISSUE TITLE
KeyError bug

### ISSUE THREAD

**Issue by tshmak** [MontrealCorpusTools/Montreal-Forced-Aligner#310]
Perhaps related to https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/292

I'm getting a 'KeyError' at [line 697](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/b1d28e1def4e4c72e2c155ebba99ba2e890f19dc/montreal_forced_aligner/dictionary.py#L697)

After some debugging, I found that it's because a phone that should be in `self.phone_mapping` isn't there, and the reason is that the phone is contained in one of the words in `self.clitic_set` but not otherwise in `word_set`. 

In [line 267](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/b1d28e1def4e4c72e2c155ebba99ba2e890f19dc/montreal_forced_aligner/dictionary.py#L267), we see that the dictionary of nonsilent phones (`self.nonsil_phones`) only gets updated if the word is in `self.word_set`. However, at this point, `self.word_set` does not include `self.clitic_set`. Rather `self.word_set` gets expanded to include `self.clitic_set` [line 280](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/b1d28e1def4e4c72e2c155ebba99ba2e890f19dc/montreal_forced_aligner/dictionary.py#L280). 

So, when doing `_write_align_lexicon`, the `self.word_set` is different, resulting in new line 697 asking for phones in `phone_mapping` that isn't there. 

I don't know how to fix this as I don't know why `self.word_set` has to be expanded to include `self.clitic_set` in the first place.

**Comment by mmcauliffe** [comment]
Ok this should be fixed in the latest release, clitic set is kept separate as they don't usually appear in the corpora, and the word set is used to trim the alignment lexicon, since not having all words except those that are actually present in the corpus speeds it up.
