### ISSUE TITLE
problem while processing lda.mat

### ISSUE THREAD

**Issue by Jueun0505** [MontrealCorpusTools/Montreal-Forced-Aligner#318]
Hi, 

I am running the following code in Montreal Forced Alignment and could not tackle the problem alone. Could anyone possible have a look at it and advise me on that? Many thanks!

`june@Juneui-MacBookAir test_my_work % mfa train audio korean_dict.txt out`
.
.
.

`FileNotFoundError: [Errno 2] No such file or directory: '/Users/june/Documents/MFA/audio/lda/lda_composed.mat' -> '/Users/june/Documents/MFA/audio/lda/lda.mat'`

**Comment by suwhoanlim** [comment]
Hey there. How did you solve the issue? I am having the same problem of not being able to locate lda.mat when trying to perform mfa train.

**Comment by suwhoanlim** [comment]
> Hi,
> 
> I am running the following code in Montreal Forced Alignment and could not tackle the problem alone. Could anyone possible have a look at it and advise me on that? Many thanks!
> 
> `june@Juneui-MacBookAir test_my_work % mfa train audio korean_dict.txt out` . . .
> 
> `FileNotFoundError: [Errno 2] No such file or directory: '/Users/june/Documents/MFA/audio/lda/lda_composed.mat' -> '/Users/june/Documents/MFA/audio/lda/lda.mat'`

Hey there. How did you solve the issue? I am having the same problem of not being able to locate lda.mat when trying to perform mfa train.
