### ISSUE TITLE
No such file or directory: '/home/aaa/Documents/MFA/Librispeech/models/HCLGa.temp'

### ISSUE THREAD

**Issue by 980202006** [MontrealCorpusTools/Montreal-Forced-Aligner#319]
when I run mfa transcribe,there is an error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/aaa/Documents/MFA/Librispeech/models/HCLGa.temp'

when run    os.remove(temp_compose_path)

Is there  an example for how to run mfa transcribe

**Comment by mmcauliffe** [comment]
This should be resolved in the latest release, duplicate of #327
