### ISSUE TITLE
CLI flag to not pause for OOV check

### ISSUE THREAD

**Issue by JoFrhwld** [MontrealCorpusTools/Montreal-Forced-Aligner#32]
A flag to not pause for OOV fixes would be useful. Doesn't seem to be one currently implemented.

**Comment by pifthemighty** [comment]
This might help. There is a workaround: pipe through echo, e.g., "echo y|/bin/mfa_align...". echo will throw down a "y" if need be, or switch to "echo n|/bin/mfa_align..." if you want a "n" for no stopping.
