### ISSUE TITLE
About the silence

### ISSUE THREAD

**Issue by daxintan-cuhk** [MontrealCorpusTools/Montreal-Forced-Aligner#324]
Hi I have some question about the silence label. I train an acoustic model from scratch, and I find that the alignment result doesn't contain the 'sil' label that represents the silence. Even after I add the two line "{LG} spn" and " {SL} sil" into the dictionary as the documentation said, the 'sil' label is still missed. In the past, when I use the pretrianed acoustic model, the 'sil' and 'spn' symbol will appear. May I know how to fix this problem? Thank you a lot!

**Comment by mmcauliffe** [comment]
So I recently removed the outputting of "sil" and "sp" to simplify the export logic and clean up the output textgrids.  Do you need these outputted?  You should be able to just use any blank output in the textgrid to mean silence.  

"spn" should still be output correctly (i.e. for unknown words), but I haven't tested the "{LG}" case in a long while, I'll try to take a look at it to verify it.

**Comment by daxintan-cuhk** [comment]
Thank you for your reply! I am glad to know this is not my implementation problem but a new property of the new MFA version. I was stucked that I can't access the interval with '' label. But I find this can be fixed by upgrading the version of praatio.
