### ISSUE TITLE
Using pretrained models in mfa align v2.0.0a24

### ISSUE THREAD

**Issue by ninamarkl** [MontrealCorpusTools/Montreal-Forced-Aligner#325]
mfa align does not seem to properly find the pretrained acoustic models - neither the one downloaded via mfa download nor the one I created and added to the pretrained_models/acoustic folder. 

When I specify a path I get a "acoustic_model" KeyError in the python script (doesn't matter whether I omit the '.zip' ending or whether or not I put the path in quotes). 

![pretrained_path](https://user-images.githubusercontent.com/56387666/130456208-a25e3e3c-abe8-4ca5-832b-1b892cbe7551.JPG)

And if I specify a string I get this error (note that something is weird with the quotation marks here - but if I don't put the string in quotes I get the KeyError seen above). 

![pretrained_string](https://user-images.githubusercontent.com/56387666/130456215-1b027eb4-2353-497a-8aa7-be151c938568.JPG)

I'm on Windows and updated MFA today - I am pretty sure I was able to align with the pretrained english model and the older 2.0 version of MFA a couple of weeks ago so this may be a new bug?

**Comment by zubeyirgenc** [comment]
The acoustic model must be in zip file and file name and zip name are same. For example the four model file in a folder which named edinbourh_english and compress this file to zip. Then give zip files path to mfa align command. For clean the previous log, you could try with --clean flag

**Comment by mmcauliffe** [comment]
As mentioned, running with the `--clean` flag will fix the issue, but I'll be updating the code so that it doesn't throw a KeyError in that case (it should just be warning you that the previous run was done with a different command so you might get some weird behavior that `--clean` would fix).
