### ISSUE TITLE
Post-MFA duration extraction

### ISSUE THREAD

**Issue by qalabeabbas49** [MontrealCorpusTools/Montreal-Forced-Aligner#328]
Hi! i have .wav , .lab and textgrid files from MFA. I need to extract features like duration etc. 
Can someone please explain that part. 
I am preparing the data for fastSpeech2 if that helps.

**Comment by mmcauliffe** [comment]
There's a couple of ways you can do this, but they're generally outside of the scope of MFA, but you can you a Praat script like https://www.acsu.buffalo.edu/~cdicanio/scripts/Get_duration_2.0.praat, or use https://github.com/timmahrt/praatIO to extract durations with Python.
