### ISSUE TITLE
No field found for key fmllr_power

### ISSUE THREAD

**Issue by babua** [MontrealCorpusTools/Montreal-Forced-Aligner#331]
When using the training config from [here](https://montreal-forced-aligner.readthedocs.io/en/latest/configuration_align.html#training-configuration) with `mfa train` , I get `No field found for key fmllr_power` error and process quits. Removing the field from the config lets the training continue. 

As far as I understand [SatTrainer](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/a3b31012afa0eea6478df23544b421943b59c6ca/montreal_forced_aligner/trainers/sat.py#L16) does not explicitly have that field and if the field is not provided in the config, it just continues with the default value.

**Comment by mmcauliffe** [comment]
Rename `fmllr_power` key to just `power`, this should be updated in documentation shortly, see also: #332
