### ISSUE TITLE
Is there anyway to suppress the hidden behavior of adding leading and trailing "sil" in .lab representation?

### ISSUE THREAD

**Issue by YangWangGit** [MontrealCorpusTools/Montreal-Forced-Aligner#334]
Very useful tool!

In my understanding, the word sequence corresponding to a wave file is like this:
   word1 word2 ... wordn
Then, by adding leading and trailing but hidden phone "sil", when doing alignment the above line is converted to:
   sil word1 word2 ... wordn sil

This is normally true to ASR and TTS requirement, but to my specific song synthesis case, where song segments are segmented based on breath sound, I typically have:
   br word1 word2 ... wordn
In another word, I have a special word "br" for breath, and no trailing "sil". Thus a typical 60s song segments will look like this:
   sil word1 word2 ... wordn      # The first song segment starting with a leading "sil"
   br word1 word2 ... wordn      # The second song segment starting with a leading "br" (breath), instead of a "sil"
   br word1 word2 ... wordn      # The third song segment starting with a leading "br" (breath), instead of a "sil"
   ...
   br word1 word2 ... wordn sil  # The last song segment starting with a leading "br" (breath), and a trailing "sil"
All above song segments would be just a few seconds normally, and all these song segments are just segmented from longer song recording, say, 60s.

Thus, I do not need the default, hidden behavior of adding leading and trailing "sil", but explicit presence/absence control of "sil" and "br" in its *.lab representation. Is there any way to do so based on MFA? 

Thank you!

**Comment by mmcauliffe** [comment]
Yeah, that behavior is currently hard coded in the dictionary generation.  I'm thinking I'll do a refactor pass to allow for some more use cases like this one.  

One thing I can think of for the near term, would it be possible to take out the `br` tokens and let the default silence model capture them?  One of the types of silence they include is breaths, and I usually do utterance breaks at breaths as well, but without the explicit modelling of them in the transcription.  If you need to pull them back out (i.e., are you using the breath segments as input to the synthesis?), you might be able to get what you want through post-processing the TextGrids?

**Comment by YangWangGit** [comment]
Thanks for your quick reply. I currently post-processing the TextGrid files to meet my requirement, and it is not ideal but works.

In the next release, it may be worth to make the hard-coded behavior as a command line option? If so, both tranditional ASR/TTS users and specific user, like me, will be very grateful on the ready-to-use MFA tool. Thank you in advance.  :-)

**Comment by mmcauliffe** [comment]
This should be resolved as of one of the more recent versions that refactored lexicon FST creation.  Specifying `--silence_probability 0 --initial_silence_probability 0` having dictionary entries with explicit silence (`br    sil`) should cover this use case.
