### ISSUE TITLE
Fatal error with Kaldi binaries

### ISSUE THREAD

**Issue by connieting** [MontrealCorpusTools/Montreal-Forced-Aligner#341]
Hi MFA Team,

I'm trying to align a new dataset using 'mfa align' and am running into a Kaldi issue:
When running, the training for mono runs fine and gets to 100%, but training for tri gives back this error:
"WARNING - Subset specified is larger than the dataset, using full corpus for this training block. 
There was one or more errors when running Kaldi binaries. For more details, please check /[Directory]/train_and_align.log"
Within the .log file, I'm not sure which portions are relevant for the issue, but the last lines are:

2021-09-28 15:18:27,458 - train_and_align - DEBUG - 	kaldi::KaldiFatalError

I've attached the end portion of the .log file as a picture for more info, in case helpful.
(Running on Mac OS 11.6; MFA version 2.0.0b3)

Any suggestions to troubleshoot this would be much appreciated, thank you!

<img width="992" alt="train_and_align" src="https://user-images.githubusercontent.com/54696636/137398708-7a263fa7-d2cb-4d73-9e30-ab269151b017.png">

**Comment by xiaofeng1020** [comment]
Hi，I encountered the same problem, did you solve it?
Thank you！

**Comment by mmcauliffe** [comment]
Hi, can you try updating the latest version using the new conda build? https://montreal-forced-aligner.readthedocs.io/en/latest/getting_started.html#getting-started-ref  I don't know for sure that it'll solve your issue, but they Kaldi binaries are now built on conda forge, so they should support more setups.

**Comment by turinaf** [comment]
I'm also facing this issue, I'm using latest MFA 
```
mfa version: 3.1.3
```
@mmcauliffe any suggested solution?

**Comment by mmcauliffe** [comment]
Closing this issue since it's pretty stale and many versions old.

@turinaf, please create a new issue with the relevant information and I can help more.

**Comment by turinaf** [comment]
The 2.0.6 version worked without any issue. 
I'm using it
@mmcauliffe
