### ISSUE TITLE
No such file or directory: 'C:\\Users\\.../Documents/MFA\\mfaTest\\corpus_data\\split1\\feats.librispeech.0.scp' and '...\corpus_data\split1\log\make_mfcc.0.log' is empty

### ISSUE THREAD

**Issue by nrgslp** [MontrealCorpusTools/Montreal-Forced-Aligner#348]
Hi Michael,

I'm now able to get past the openfst error I previously mentioned, (I think? using `conda install -c conda-forge kaldi`), so I'm still trying to get the Windows install to work. Apologies if this can be solved by your suggestion to use WSL. I am still trying to run MFA 2.0.0.b4 in Windows 10 per my previous message about needing to talk to the software people to see if we can run WSL within our workflow on the Windows server, plus I thought I was past the openfst error. 

I'm trying to validate a small batch of files that I've been able to align on linux.

`mfa validate "C:\...\...\mfaTest\" "C:\...\...\mfaTest\librispeech.dict" english  -v  --clean`

Here is the error message:
```
INFO - Creating dictionary information...
INFO - Setting up training data...
INFO - Generating base features (mfcc)...
Traceback (most recent call last):
  File "c:\...\conda\envs\...\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\...\conda\envs\...\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\...\Conda\envs\...\Scripts\mfa.exe\__main__.py", line 7, in <module>
  File "c:\...\conda\envs\...\lib\site-packages\montreal_forced_aligner\command_line\mfa.py", line 757, in main
    run_validate_corpus(args, unknown)
  File "c:\...\conda\envs\...\lib\site-packages\montreal_forced_aligner\command_line\validate.py", line 145, in run_validate_corpus
    validate_corpus(args, unknown)
  File "c:\...\conda\envs\...\lib\site-packages\montreal_forced_aligner\command_line\validate.py", line 79, in validate_corpus
    a = CorpusValidator(
  File "c:\...\conda\envs\...\lib\site-packages\montreal_forced_aligner\validator.py", line 117, in __init__
    self.setup()
  File "c:\...\conda\envs\...\lib\site-packages\montreal_forced_aligner\validator.py", line 139, in setup
    self.corpus.initialize_corpus(self.dictionary, fc)
  File "c:...\conda\envs\...\lib\site-packages\montreal_forced_aligner\corpus\base.py", line 738, in initialize_corpus
    self.generate_features()
  File "c:\...\conda\envs\...\lib\site-packages\montreal_forced_aligner\corpus\base.py", line 804, in generate_features
    self.combine_feats()
  File "c:\...\conda\envs\...\lib\site-packages\montreal_forced_aligner\corpus\base.py", line 845, in combine_feats
    with open(path, "r") as inf:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\...\\.../Documents/MFA\\mfaTest\\corpus_data\\split1\\feats.librispeech.0.scp'
```
And when I open `"C:\...\...\Documents\MFA\mfaTest\corpus_data\split1\log\make_mfcc.0.log"`, the file is empty. 

I've tried stepping through the code but am still trying to find where things go wrong. In the meantime, I'm wondering if you have any thoughts about pinpointing the reason for this error. 

Thanks,
Nina

**Comment by mmcauliffe** [comment]
Hmm, just to be clear, are the ...'s the result of your scrubbing?

Also, can you try re-installing MFA straight from conda? `conda install -c conda-forge montreal-forced-aligner` it should be up as of today, and should take care of any missing dependencies.

**Comment by nrgslp** [comment]
Yes I put the `...`s in during scrubbing for this post.

I reinstalled the MFA through conda-forge and reran the command above in the anaconda prompt instead of anaconda powershell.

After these changes I now get an error in a pop-up window. The error is:
```
extract-segments.exe - System Error

The code execution cannot proceed because mkl_sequential.1.dll was not found. Reinstalling the program may fix this problem.
```

**Comment by mmcauliffe** [comment]
Ok, if you do a `conda list` are `libblas` and `libcblas` in the package list?  The should look something like:

```
...
  libblas            conda-forge/win-64::libblas-3.9.0-12_win64_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-12_win64_mkl
...
```

**Comment by nrgslp** [comment]
`libblas                   3.9.0           1_h8933c1f_netlib    conda-forge
libcblas                  3.9.0           5_hd5c7e75_netlib    conda-forge`

**Comment by mmcauliffe** [comment]
Oh interesting, I thought it would install the mkl versions by default on windows, I'll do some digging, but in the meantime, `conda install -c conda-forge "libblas=*=*mkl"` should get the dll's that you need (and maybe `conda install "libcblas=*=*mkl"` if the first command doesn't autoupdate it).

**Comment by nrgslp** [comment]
I now have 
```
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
```
in the current environment. 

`mfa validate "C:\...\...\mfaTest" "C:\...\...\mfaTest\librispeech.dict" english`

but the same error appears
```
extract-segments.exe - System Error

The code execution cannot proceed because mkl_sequential.1.dll was not found. Reinstalling the program may fix this problem.
```

I appreciate your help with this. I will owe you so much cake when this dissertation is over 🙃

**Comment by mmcauliffe** [comment]
Haha no worries, I appreciate you testing MFA! 

Maybe also try `conda install mkl`? Possible the one above didn't actually install the real dll.  Should have this in your conda environment:

```
mkl                       2021.4.0           h0e2418a_729    conda-forge
```

**Comment by nrgslp** [comment]
It seems to be there. Here's everything in that environment (attached).
[conda-list.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/7527442/conda-list.txt)

**Comment by mmcauliffe** [comment]
Ok, couple more ideas.  My version of mkl is more recent and also platform dependent, see mine here:
[mm_conda_list.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/7529923/mm_conda_list.txt)

So maybe upgrading your mkl version if it's an older environment: `conda update mkl`  Also maybe try updating conda itself `conda update conda`?

Also, do you have any details on the exact platform that you're running here?  Windows version, any reason why it wouldn't be requesting win64 versions of Kaldi packages?

**Comment by nrgslp** [comment]
So good news... your questions pointed me toward the fact that something about PyTorch wasn't playing well with the third party binaries. So, I created a new environment with the MFA, and then added PyTorch to it. And it's validating....I'm going to roll with it. 

ps. loving the enhanced printouts in 2.0.0b4
You'll hear from me again, I'm sure...it's going to be one huge lasagna eventually coming your way.
