### ISSUE TITLE
thirdparty and download unrecognized

### ISSUE THREAD

**Issue by benWarnick** [MontrealCorpusTools/Montreal-Forced-Aligner#349]
Hi,

I'm using windows 10.
I performed the following commands:
pip install montreal-forced-aligner                                                
pip install git+https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner.git 

Afterward I tried the two following commands:
mfa thirdparty download
mfa download acoustic english

In the first case I get the following error:
mfa: error: argument subcommand: invalid choice: 'thirdparty' (choose from 'version', 'align', 'adapt', 'train', 'validate', 'g2p', 'train_g2p', 'model', 'train_lm', 'train_
dictionary', 'train_ivector', 'classify_speakers', 'create_segments', 'transcribe', 'configure', 'history', 'annotator', 'anchor')

In the second case the same error happens with the invalid choice being "download"

I'd appreciate any help. Specifically if I'm missing something from the command or if there is another way to download the acoustic english model.

Thanks!

**Comment by mmcauliffe** [comment]
Docs are updated now with the correct command (https://montreal-forced-aligner.readthedocs.io/en/latest/index.html) and the new version shows deprecation messages for the old commands, so I'll close this
