### ISSUE TITLE
unhandled markups and punctuation signs

### ISSUE THREAD

**Issue by benWarnick** [MontrealCorpusTools/Montreal-Forced-Aligner#355]
Hi,

I'm using the MFA for the alignment of the gulliver_intro dataset (part of librispeech). I found that in lab file some of the words are surrounded by underscores, for example _Yahoos_ . In the TextGrid output I will find a timestamp for  "_yahoos_", however during this timestamp there is no breakdown to phones and instead the output is "". The word YAHOOS appears in the lexicon file. When removing the underscores manually the output is correct. I am assuming the _ isn't a punctuation sign that is removed during parsing. 
I saw that other punctuation signs are ignored as I would expect (periods, commas, semicolons, parenthesis, etc.)

Can you please add "_" to the list of signs to remove when parsing? In the mean time, where can I find the list of signs that are removed/handled? 

Thank you!

**Comment by mmcauliffe** [comment]
Yep, here's the fields available for dictionary parsing: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/dictionary.html#configuration-dictionary, you can see an example here: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/290, it's just a field on a custom `--config_path` yaml.

The current config documentation is due for a bit of refresh, especially as I've been working on changing how config is handled internally, so I'll make it more clear.

**Comment by mmcauliffe** [comment]
Ok, refreshed the configuration documentation to try to make how you configure specific commands more clear: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/index.html#configuring-specific-commands  The text parsing options available are: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/global.html#dictionary-and-text-parsing-options
