### ISSUE TITLE
Why the TextGrid is empty

### ISSUE THREAD

**Issue by yaoxunji** [MontrealCorpusTools/Montreal-Forced-Aligner#357]
I download the montreal-forced-aligner_linux.tar.gz instead of using conda, and then I run this commend:
`../../tools/montreal-forced-aligner/bin/mfa_align dataset/wav16/ lexicon/librispeech-lexicon.txt  ../../tools/montreal-forced-aligner/pretrained_models/english.zipdataset/TextGrid/ -j 10 -v`
after running, I find the TextGrid is empty

**Comment by hsyi** [comment]
You should check your third-party dependencies.
Without using conda, you need to build kaldi and other third-party(egs: opengrm, openfst) dependencies.
