### ISSUE TITLE
There is no 'model' argument in the command

### ISSUE THREAD

**Issue by YoungKang1222** [MontrealCorpusTools/Montreal-Forced-Aligner#361]
![image](https://user-images.githubusercontent.com/30460985/144350287-22c7d647-f55f-4a71-b3f4-4c7cbb3b1cfa.png)

Excuse, I use mfa model to inspect the acoustic model ,but it gives command error.
the MFA verison is 2.0.0
![image](https://user-images.githubusercontent.com/30460985/144350515-5de4f996-c49c-458c-87b6-24cb35d92120.png)

**Comment by mmcauliffe** [comment]
That version of MFA doesn't have the model command, I think.  Upgrade to the latest and it should have it: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#upgrading-from-non-conda-version

**Comment by YoungKang1222** [comment]
thanks! Upgrading works.
