### ISSUE TITLE
"--clean" might be a bit dangerous, and a permissions issue.

### ISSUE THREAD

**Issue by pifthemighty** [MontrealCorpusTools/Montreal-Forced-Aligner#37]
Great software! I do have nagging issue: If the "-c" argument is used, and a user were to enter "~/" or "~/Documents" as their output location is there any protection against erasing the whole User or whole Documents folder? 

Also it seems whether "--clean" is used or not 'mfa_align' will delete the whole output folder and replace it with a identically named folder but with different permissions than the one it is replacing. It is causing me some headaches. Thanks!

**Comment by mmcauliffe** [comment]
Yeah, that's definitely true, and there's a better system in place for tracking whether the temporary files should be cleaned up now, so I think something more measured for the output directory would be good. The main thing I would want to ensure is that any TextGrids (or better, just the ones matching the names of those to be generated) in the output folder were generated by this exact run of the aligner.

For the permissions issue, I don't know why it would be changing permissions without clean.  It does a `os.makedirs(output_directory, exist_ok=True)` call, but the folder shouldn't be deleted, but I can wrap that in a existence check first to make sure the aligner doesn't touch existing folders at all.  Would it be possible for you to write a quick python script to see if the `os.makedirs` call is causing the issue?

**Comment by mmcauliffe** [comment]
Removed deletion of output directory.
