### ISSUE TITLE
My code was working last week but now it is not working

### ISSUE THREAD

**Issue by yasntrk** [MontrealCorpusTools/Montreal-Forced-Aligner#371]
```
%%writefile install_mfa.sh
#!/bin/bash

## a script to install Montreal Forced Aligner (MFA)

root_dir=${1:-/tmp/mfa}
mkdir -p $root_dir
cd $root_dir

# download miniconda3
wget -q --show-progress https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p $root_dir/miniconda3 -f

# create py38 env
$root_dir/miniconda3/bin/conda create -n aligner -c conda-forge openblas python=3.8 openfst pynini ngram baumwelch -y
source $root_dir/miniconda3/bin/activate aligner

# install mfa, download kaldi
pip install montreal-forced-aligner # install requirements
pip install git+https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner.git # install latest updates

mfa thirdparty download

echo -e "\n======== DONE =========="
echo -e "\nTo activate MFA, run: source $root_dir/miniconda3/bin/activate aligner"
echo -e "\nTo delete MFA, run: rm -rf $root_dir"
echo -e "\nSee: https://montreal-forced-aligner.readthedocs.io/en/latest/aligning.html to know how to use MFA"



# download and install mfa
INSTALL_DIR="/tmp/mfa" # path to install directory

!bash ./install_mfa.sh {INSTALL_DIR}
!source {INSTALL_DIR}/miniconda3/bin/activate aligner; mfa align --help

```
I am using this code but it says:

``` "montreal_forced_aligner.exceptions.ThirdpartyError: ThirdpartyError: Could not find 'compute-mfcc-feats'. Please ensure that you have installed MFA's conda dependencies." ```

Can anyone help me? I was using this notebook as a reference but this notebook is not working anymore. You can check if you want. 

https://colab.research.google.com/gist/NTT123/12264d15afad861cb897f7a20a01762e/mfa-ljspeech.ipynb#scrollTo=_twSwprjG_M9

**Comment by mmcauliffe** [comment]
There was an issue with the packaging on Kaldi last night, but there should be a new version up and should be available tonight (5.5.992_3 instead of 5.5.992_2)

**Comment by yasntrk** [comment]
> There was an issue with the packaging on Kaldi last night, but there should be a new version up and should be available tonight (5.5.992_3 instead of 5.5.992_2)

Thank you! I almost went crazy :D

**Comment by yasntrk** [comment]
> There was an issue with the packaging on Kaldi last night, but there should be a new version up and should be available tonight (5.5.992_3 instead of 5.5.992_2)

I'm sorry if I'm bothering you, but the notebook I share is still not working. Will there be an update?

**Comment by mmcauliffe** [comment]
Oh I don't actually maintain that, it was posted by @NTT123, looks like it's hosted here: https://gist.github.com/NTT123/12264d15afad861cb897f7a20a01762e#file-mfa-ljspeech-ipynb.  I think getting it updated is just a matter of replacing:

```
# create py38 env
$root_dir/miniconda3/bin/conda create -n aligner -c conda-forge openblas python=3.8 openfst pynini ngram baumwelch -y
source $root_dir/miniconda3/bin/activate aligner

# install mfa, download kaldi
pip install montreal-forced-aligner # install requirements
pip install git+https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner.git # install latest updates

mfa thirdparty download
```
with 
```
$root_dir/miniconda3/bin/conda create -n aligner -c conda-forge montreal-forced-aligner
```

And you should be good to go.

**Comment by NTT123** [comment]
@yasntrk I've updated the notebook. Thanks @mmcauliffe for the fix.

**Comment by yasntrk** [comment]
> @yasntrk I've updated the notebook. Thanks @mmcauliffe for the fix.

Thank you!
