### ISSUE TITLE
Spanish acoustic model

### ISSUE THREAD

**Issue by tbright17** [MontrealCorpusTools/Montreal-Forced-Aligner#39]
Do you have plan to add Spanish acoustic model?

Thanks

**Comment by mmcauliffe** [comment]
Yes, it's there now, it was uploaded, just didn't have a link in the table (http://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html#pretrained-acoustic-models), fixed now!

**Comment by tbright17** [comment]
Thanks for providing this new link.

**Comment by tbright17** [comment]
Don't want to open a new issue so I will post it here.

I downloaded the pretrained spanish acoustic model and generated dictionary usin trained G2P model. Then I use bin/mfa_align to do the alignment:
```python
bin/mfa_align -t SP_words/temp  -j 10 SP_words/ pretrained_models/spanish/dictionary spanish SP_words/
```
There was an error: the language spanish is currently included in the distribution, please align via training or specify one of the following language names: english

How should I align using the pretrained model other than English?

Thanks

**Comment by mmcauliffe** [comment]
Right, so only English ships with the aligner, so there's just that one shortcut.  For any pretrained model you download, you have to specify it's full path, something like:

```
bin/mfa_align -t SP_words/temp  -j 10 SP_words/ pretrained_models/spanish/dictionary /path/to/spanish.zip SP_words/
```

With the model specification ending in in .zip.

**Comment by tbright17** [comment]
Thanks again.
