### ISSUE TITLE
item[1] item[2]  in textgrid file

### ISSUE THREAD

**Issue by Liujingxiu23** [MontrealCorpusTools/Montreal-Forced-Aligner#390]
hi, when I did "mfa align" and get textgrid file, why there are two items(seems two version of results) in the textgrid file?
what is the difference?
![捕获](https://user-images.githubusercontent.com/49260794/149856365-afa38fd9-3c19-446c-824c-bc188e18582a.JPG)

**Comment by mmcauliffe** [comment]
Item [1] is the tiers for word alignments and Item [2] is the tier for phone alignments (depending on your use case, you might only be interested in the phones, and can ignore the words tier).

**Comment by Liujingxiu23** [comment]
@mmcauliffe Thank you for your reply!
