### ISSUE TITLE
[BUG] Problems installing on MacOS 12.2 M1 with Miniconda

### ISSUE THREAD

**Issue by ThatBernie** [MontrealCorpusTools/Montreal-Forced-Aligner#398]
I'm having an issue installing MFA on a MacOS 12.2 with an M1 processor. At first I tried manually installing the Intel-version of Miniconda from the Conda website, as had been suggested in a previous report for a similar issue, but I still end up getting the following error when I try to run the MFA:

<img width="951" alt="Screen Shot 2022-02-04 at 10 41 05 AM" src="https://user-images.githubusercontent.com/60358488/152616398-22396869-6c1a-41a8-a9d3-0064232b0214.png">

So instead I went back and uninstalled the Intel-version of Miniconda, and manually installed the M1-version from the Conda website, and instead I get this error:

<img width="1211" alt="Screen Shot 2022-02-04 at 6 18 19 PM" src="https://user-images.githubusercontent.com/60358488/152616683-cad18d6b-f4ba-463e-a76d-e7e4158e2ccd.png">

Not sure how to proceed, thank you!

**Comment by mmcauliffe** [comment]
Ok, so we got openfst and ngram building on conda-forge for osx_arm64 yesterday, and there should be a new MFA build available that links against them.  Could you try reinstalling the non-intel version and running MFA?

**Comment by ThatBernie** [comment]
Amazing, it worked! Thank you!
