### ISSUE TITLE
[BUG] Error on g2p train

### ISSUE THREAD

**Issue by massimo1980** [MontrealCorpusTools/Montreal-Forced-Aligner#401]
**Debugging checklist**

[x] Have you updated to latest MFA version?
[x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
when run g2p training get this error:
`

INFO - Constructing grapheme and phoneme FARs
INFO - Processed 6,417 examples
INFO - Constructing covering grammar
INFO - 30 unique graphemes
INFO - 37 unique phones
INFO - Covering grammar has 1,177 arcs
INFO - Training aligner
INFO - Calculating alignments...
  0%|                                                                                                                                                                                                      | 0/250 [00:02<?, ?it/s]
PyniniAlignmentError: The following Pynini alignment jobs encountered errors:   2 (RandomStart(idx=2, seed=2394,
  g_path='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p/g.far',
  p_path='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p/p.far',
  c_path='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p/c.fst',
  tempdir='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p', train_opts=['--batch_size=800',
  '--delta=0.0009765625', '--fst_default_cache_gc=false', '--lr=1.0', '--max_iters=10']), Exception(['Traceback (most
    recent call last):\n', '  File
  "/home/max/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/g2p/trainer.py", line 144, in
    run\n    assert match, line\n', 'AssertionError: FATAL: SetFlags: Bad option: --lr=1.0\n'])) 1 (RandomStart(idx=1,
  seed=7577, g_path='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p/g.far',
  p_path='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p/p.far',
  c_path='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p/c.fst',
  tempdir='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p', train_opts=['--batch_size=800',
  '--delta=0.0009765625', '--fst_default_cache_gc=false', '--lr=1.0', '--max_iters=10']), Exception(['Traceback (most
    recent call last):\n', '  File
  "/home/max/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/g2p/trainer.py", line 144, in
    run\n    assert match, line\n', 'AssertionError: FATAL: SetFlags: Bad option: --lr=1.0\n'])) 3 (RandomStart(idx=3,
  seed=28608, g_path='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p/g.far',
  p_path='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p/p.far',
  c_path='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p/c.fst',
  tempdir='/home/max/Documents/MFA/italian_dict_pynini_train_g2p/pynini_train_g2p', train_opts=['--batch_size=800',
  '--delta=0.0009765625', '--fst_default_cache_gc=false', '--lr=1.0', '--max_iters=10']), Exception(['Traceback (most
    recent call last):\n', '  File
  "/home/max/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/g2p/trainer.py", line 144, in
    run\n    assert match, line\n', 'AssertionError: FATAL: SetFlags: Bad option: --lr=1.0\n']))
`

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? Italian
   * How many files/speakers? 1
   * Are you using lab files or TextGrid files for input? lab files
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? no
   * If it's a custom dictionary, what is the phoneset?   phone_set_type: PINYIN
   
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? no
   * If it's a model you've trained, what data was it trained on? 

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] Linux
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] Ubuntu 20.04
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**
[logfile.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8056043/logfile.txt)

**Comment by mmcauliffe** [comment]
Thanks, this looks like it's caused by baumwelch 0.3.7 removing the lr parameter.  I'll try to get a fix out for this soon, but since you're on ubuntu, you can try downgrading via `conda install baumwelch=0.3.6` as a temporary workaround

**Comment by massimo1980** [comment]
Hi Michael and thanks for the quick reply!
the workaround seems to work
take care
