### ISSUE TITLE
[BUG] Can't align Portuguese IPA

### ISSUE THREAD

**Issue by douglas125** [MontrealCorpusTools/Montreal-Forced-Aligner#406]
**Debugging checklist**

[X] Have you updated to latest MFA version?
[X] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

If I run
`mfa --clean align pt/ portuguese_brazil_ipa portuguese pt_aligned/`

I basically don't get any acoustic models: `Phones missing acoustic models:` (all of them)

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? Portuguese
   * How many files/speakers? 2
   * Are you using lab files or TextGrid files for input? lab files
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? portuguese_brazil_ipa
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? portuguese
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] Tried using Windows and Linux. Same problem
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**
It doesn't look like there is a possible combination of acoustic and dictionary that allows alignment in Portuguese. Any help is appreciated.

Thanks

**Comment by mmcauliffe** [comment]
So the `portuguese` models were trained using the GlobalPhone dictionary, so you'll have to use the `portuguese_g2p` model from https://github.com/MontrealCorpusTools/mfa-models/releases/tag/g2p-archive-1.0 to generate the dictionary first. I am hoping to get a trained IPA model for portuguese and the rest of the languages up soon.

**Comment by mmcauliffe** [comment]
Version 2.0.0rc4 can now download and use the new IPA-based models, so if you want to try out the Portuguese one, it's here: https://mfa-models.readthedocs.io/en/latest/acoustic/Portuguese/Portuguese%20MFA%20acoustic%20model%20v2_0_0.html#Portuguese%20MFA%20acoustic%20model%20v2_0_0.  It was trained with corpora on both Brazilian and European Portuguese, but you can just use the [Brazilian Portuguese dictionary](https://mfa-models.readthedocs.io/en/latest/dictionary/Portuguese/Portuguese%20%28Brazil%29%20MFA%20dictionary%20v2_0_0.html#portuguese-brazil-mfa-dictionary-v2-0-0) to limit the pronunciations.  

Also, if there's anything off with the dictionary or phone set, please let me know!  I have made some decisions [here](https://mfa-models.readthedocs.io/en/latest/mfa_phone_set.html#portuguese) mostly to ensure consistency across languages, any feedback is welcome!
