### ISSUE TITLE
[BUG] misleading error: "Try installing another version of sox with support for directory"

### ISSUE THREAD

**Issue by cdleong** [MontrealCorpusTools/Montreal-Forced-Aligner#407]
https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/63473f9a4fabd31eec14e1e5022882f85cfdaf31/montreal_forced_aligner/utils.py#L226

This line outputs an error along the lines of "unsupported file type". It gets the file type by taking the last word of the error message.

However, I had a file with a _space in the name_, causing the error "no such file or directory". And it somehow triggered this line. So then it said: "Try installing another version of sox with support for **directory**".

**Comment by mmcauliffe** [comment]
Should be fixed in 2.0.0rc4.
