### ISSUE TITLE
ValueError: too many values to unpack (expected 2) [mfa validate]

### ISSUE THREAD

**Issue by kc-li** [MontrealCorpusTools/Montreal-Forced-Aligner#411]
Hi, 

I was try to train a new acoustic model on a language I'm working on. I prepared a small dataset and try to validate whether the format is correct.  When I used the command `mfa validate ~/dataset  ~/dictionary.txt` it always returns with the error:

ValueError: too many values to unpack (expected 2)

I previously used version 1 and successfully trained acoustic dataset on another language, but now with the new version when I used the same material it also return this error.

-----------------
The transcription in each interval in the textgrid is like this (read speech): 
xiao in nie le ge sii zii
xiao in nie le ge sii zii
xiao in nie le ge sii zii
sii xiao in nie le ge sii zii,bu sii xiao gang
xiao in sou gong hao ca ma
lian xiao in dou nie le ge sii zii,ni za ge sa zii dou zo bu cu lai lan
xiao in nie le ge sii zii
xiao in na le ge lan zii
xiao in na le ge lan zii
xiao in na le ge lan zii
sii xiao in na le ge lan zii,bu sii xiao ming
xiao in duei ji ti ho dong cong lai dou bu z1e xin
......

And the dictionary.txt file is like this (basically, the inventory of the syllable in the language)
er	 	er
zii	z	ii
cii	c	ii
sii	s	ii
z1ii	z1	ii
ba	b	a
pa	p	a
ma	m	a
fa	f	a
da	d	a
ta	t	a
na	n	a
la	l	a
za	z	a
ca	c	a
sa	s	a
ga	g	a
ka	k	a
nga	ng	a
ha	h	a
a	 	a
bai	b	ai
pai	p	ai
mai	m	ai
dai	d	ai
tai	t	ai
nai	n	ai
lai	l	ai
zai	z	ai
cai	c	ai
sai	s	ai
gai	g	ai
kai	k	ai
ngai	ng	ai
hai	h	ai
ai	 	ai
......

Could you help me have a look what's causing the problem there?

**Comment by kc-li** [comment]
Here's the thing that solves my problem: in the dictionary file, there can be a tab between the lexicon and the phonemes, but between phonemes only use space. I hope there are more descriptions in the documentation on the formatting of the dictionary file.

**Comment by lanmo0923** [comment]
I also encountered this problem, can you tell me the details of the solution?
