### ISSUE TITLE
Expose training configuration to users

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/Montreal-Forced-Aligner#42]
Currently training and model parameters are fixed, user should be able to specify some/all, probably through a yaml file.

**Comment by mmcauliffe** [comment]
Additionally, expose beam and retry-beam options, especially for aligning longer sound files (maybe also do some better setting of defaults based off of mean utterance length).

**Comment by sirifarif** [comment]
Any progress on this issue? I can see a branch [advanced-training](/MontrealCorpusTools/Montreal-Forced-Aligner/tree/advanced-training), Is it realty to this issue.

**Comment by agangzz** [comment]
if training and model parameters are able to specify through some file, such as yaml file, it would be more convenient and flexible. Looking forward these new feature.

**Comment by mmcauliffe** [comment]
Advanced training work is finally done and merged in.
