### ISSUE TITLE
Be clearer about which files failed to align and why

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/Montreal-Forced-Aligner#43]
Currently if a file can't be aligned, no mention is made in the console.  MFA should inspect the aligning logs to find which files could not be decoded even with the retry beam, and make some suggestions for why they could not be aligned (errors in transcription, too long for the beam size, increasing the beam, etc).

**Comment by mmcauliffe** [comment]
Inspect feature creation logs as well, and detect when WAV files can't be read by Kaldi (results in missing features).

**Comment by agangzz** [comment]
Be clearer about which files failed to align and why

Looking forwarding to this feature which would be more useful for checking the errors

**Comment by mmcauliffe** [comment]
Addressed by new `validate_dataset` executable rather than alignment executables.
