### ISSUE TITLE
[BUG] aligned textgrids not appearing in designated output directory

### ISSUE THREAD

**Issue by emilyahn** [MontrealCorpusTools/Montreal-Forced-Aligner#431]
**Debugging checklist**

[x - 2.0.0rc5 ] Have you updated to latest MFA version?
[x ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

The output textgrids after aligning (w/ pretrained English) are not going into the specfied output directory--instead, going into MFA-internal directory. Here is my command, and one of the lines of the run:

> ```
> $ mfa align --clean Desktop/input/ Documents/MFA/pretrained_models/dictionary/english_mfa.dict Documents/MFA/pretrained_models/acoustic/english_mfa.zip ~/Desktop/output/
> 
> INFO - Finished exporting TextGrids to /Users/eahn/Documents/MFA/input_pretrained_aligner/pretrained_aligner/textgrids!
> ```

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? - english_mfa
   * How many files/speakers? - 4 files/4 speakers
   * Are you using lab files or TextGrid files for input? - TextGrid
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? - yes; english_mfa
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? - english_mfa
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] - OSX (Mac)
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] - MacOSX 10.14.6
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**
The log has this line, which might be the one causing issues:

> `DEBUG - Not overwriting existing directory, exporting to /Users/eahn/Documents/MFA/input_pretrained_aligner/pretrained_aligner/textgrids`

**Comment by emilyahn** [comment]
[pretrained_aligner.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8517047/pretrained_aligner.log)

**Comment by hhm853610070** [comment]
hi,i have the same problem.TextGrids are exported to ~\Document\MFA\test_data_pretrained_aligner\pretrained_aligner\textgrids,but the designated output path is empty.Do you solve the problem?

**Comment by ngoquanghuy99** [comment]
I got the same issue!
