### ISSUE TITLE
Phones containing underscores pass validation but don't work in aligner

### ISSUE THREAD

**Issue by catiR** [MontrealCorpusTools/Montreal-Forced-Aligner#432]
I have a pronunciation dictionary where some of the phone labels contain underscores, e.g. {'k_h', 'J_0'}. 

mfa validate reported no errors, and its output shows these underscores in the list of non_silence_phones.

However, mfa align had `ValueError: too many values to unpack (expected 2)`. I did not change the default `position_dependent_phones` so I guess that was `True`.

```
> mfa align --verbose --num_jobs 4 --output_format json --temp_directory /scratch/caitlinr/capt/mfa/temp_json /scratch/caitlinr/capt/data/capt1ni /scratch/caitlinr/capt/mfa/lexs/combined_added_lexicon.txt samromur /scratch/caitlinr/capt/data/output1
...
Exception: Traceback (most recent call last):
  File "/home/caitlinr/.conda/envs/capt2/lib/python3.10/site-packages/montreal_forced_aligner/utils.py", line 404, in run
    for result in self.function.run():
  File "/home/caitlinr/.conda/envs/capt2/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 811, in run
    word_intervals, phone_intervals = self.cleanup_intervals(
  File "/home/caitlinr/.conda/envs/capt2/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 645, in cleanup_intervals
    phone, position = phone_label.split("_")
ValueError: too many values to unpack (expected 2)
```
I changed line 645 in https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/montreal_forced_aligner/alignment/multiprocessing.py
from 
`phone, position = phone_label.split("_")` 
to 
`phone, position = phone_label.rsplit("_",1)`
and then my corpus alignment was successful.

The same error happened with MFA 2.0.0rc5 and 2.0.0rc4 (minus the output_format specification) and the same thing fixed it. However I don't know if this breaks anything else and it would be better to change the phone labels to avoid underscores.

**Debugging checklist**

[ x] Have you updated to latest MFA version?
[ x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
Phone labels that contain underscores are allowed through validation but don't work with alignment, at least when using position dependent phones.

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? - Icelandic
   * How many files/speakers? - 125 speakers, about 13000 files
   * Are you using lab files or TextGrid files for input? - lab files
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? - no, https://github.com/grammatek/iceprondict/blob/master/version_22.01/ice_pron_dict_complete_2201.csv
   * If it's a custom dictionary, what is the phoneset? - listed in attached log file
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? - no
   * If it's a model you've trained, what data was it trained on? - it's a bit of a mystery but we think a previous lab member trained it with some previous version of MFA :) probably at least 20 hours of Icelandic.

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] - linux
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] - Debian 11
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**

[slurm-128280.out.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8521737/slurm-128280.out.txt)

**Comment by manhph2211** [comment]
Hi @catiR,
I met the same error here. The error would be shown up as a KeyError because the input key of dict doesn't contain `_` like the right key when I trained on my custom `lexicon.txt` to be exact!
Of course, the bug can be fixed by handling as you mentioned but in my case :+1: , I chose to fix my `lexicon.txt`, in which doesn't use any of `_` characters :smile: 
Anyway I'm not sure if this is a bug, or something is not on the right track :confused: 
Hopefully someone will have the answer!
