### ISSUE TITLE
the content format problem of TextGrids

### ISSUE THREAD

**Issue by hhm853610070** [MontrealCorpusTools/Montreal-Forced-Aligner#434]
hi,i use mfa of version2.0.0.0rc5(windows).
The content format of TextGrid is:
File type = "ooTextFile"
Object class = "TextGrid"

0
9.8125
<exists>
2
"IntervalTier"
"words"
0
9.8125
37
0
0.84
""
0.84
1.17
"lv4"
1.17
1.33
"shi4"
1.33
1.61
"yang2"
1.61
1.91
"chun1"
1.91
2.12
"yan1"

it is different from the format i have seen online,the format is:
File type = "ooTextFile"
Object class = "TextGrid"

xmin = 0.0
xmax = 9.8125
tiers? <exists>
size = 2
item []:
    item [1]:
        class = "IntervalTier"
        name = "words"
        xmin = 0.0
        xmax = 9.8125
        intervals: size = 37
            intervals [1]:
                xmin = 0.0
                xmax = 0.84
                text = ""
            intervals [2]:
                xmin = 0.84
                xmax = 1.17
                text = "lv4"
            intervals [3]:
                xmin = 1.17
                xmax = 1.33
                text = "shi4"

is the content format changed or i have got the wrong format?

**Comment by ngoquanghuy99** [comment]
I got the same issue! 
Don't know how to address this? @mmcauliffe

**Comment by mmcauliffe** [comment]
You can change the output format to "long_textgrid" here via the `--output_format` flag here: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/alignment.html#cmdoption-mfa-align-output_format.  I'll revert it back to exporting long textgrids by default, but this will work in the meantime.

**Comment by ngoquanghuy99** [comment]
Problem fixed! This issue should be closed!
