### ISSUE TITLE
No TextGrid Files in the Output and No Error Messages

### ISSUE THREAD

**Issue by A7Alzohaile** [MontrealCorpusTools/Montreal-Forced-Aligner#441]
I'm trying to use MFA in my project so I follow API guide to write some code
```
pretra_aligner = PretrainedAligner(acoustic_model_path, dictionary_path, corpus_directory,  output_directory, temporary_directory, verbose=True, clean=True, beam=100)

pretra_aligner.align()
```

and as a sample I aligned 1 audio file (wav) with 1 transcript (txt) using pretrained pronunciation dictionary ([librispeech-lexicon](http://www.openslr.org/resources/11/librispeech-lexicon.txt)) and acoustic model ([English](https://github.com/MontrealCorpusTools/mfa-models/raw/main/acoustic/english.zip)).
when using command line I got textgrid output in the desired folder but when using mine I got nothing also there is no error message and everything works fine.

here is my [log file.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8599409/log.file.txt)

[output.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8599411/output.txt) output when running 

am I missing something in the workflow other than call `align()` function from `PretrainedAligner` ?

**Comment by mmcauliffe** [comment]
Can you try running it with keyword arguments instead? Also the output directory is used as an argument to `export_files`, rather than in initialization:

```
pretra_aligner = PretrainedAligner(acoustic_model_path=acoustic_model_path, dictionary_path=dictionary_path, corpus_directory=corpus_directory, temporary_directory=temporary_directory, verbose=True, clean=True, beam=100)

pretra_aligner.align()
pretra_aligner.export_files(output_directory)
```

See https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/montreal_forced_aligner/command_line/align.py#L31-L41 for reference

**Comment by A7Alzohaile** [comment]
thanks for reference.. it made made me understand the workflow better
