### ISSUE TITLE
[BUG] mfa g2p fails on TextGrid folder, works only with word list

### ISSUE THREAD

**Issue by Lisa-MoJo** [MontrealCorpusTools/Montreal-Forced-Aligner#449]
**Debugging checklist**

[ Yes] Have you updated to latest MFA version?
[ Yes] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

**For Reproducing your issue**
While running `mfa g2p -v --clean sh_g2p_1w.zip LongTGX sh_2w.dict` we receive the error (repro on either Mac or WSL2):
CorpusError: There were no files found for this corpus. Please validate the corpus.

Please note - the command does work when running with a word list as input (see WordListC.txt attached)

1. Corpus structure
   * What language is the corpus in? Shoshoni
   * How many files/speakers? 2 (for the sample data attached)
   * Are you using lab files or TextGrid files for input? TextGrid
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? No
   * If it's a custom dictionary, what is the phoneset? See attached model
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? No
   * If it's a model you've trained, what data was it trained on? n/a

[WordListC.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8694144/WordListC.txt)

**Desktop (please complete the following information):**
 - OS: Mac or WSL2 (both failing)
 - Version Mac Monterey / Windows 11

There are a large number of files I want to process. The error though is reproducible with 1 pair of files (see attached)
[MFA_G2P_Error.zip](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8694143/MFA_G2P_Error.zip)

**Comment by mmcauliffe** [comment]
This should be resolved as of 2.0.0rc8!
