### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory: 'split3/feats.0.scp'

### ISSUE THREAD

**Issue by GaryGao99** [MontrealCorpusTools/Montreal-Forced-Aligner#452]
**Debugging checklist**

[ YES] Have you updated to latest MFA version?
[ YES] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
When I running "mfa align corpus  mandarin_pinyin.dict  mandarin_mfa.zip alignment --clean  ",  receive the error 

"NFO - Generating base features (mfcc)...
INFO - Generating MFCCs...
   0%|                                                                                                                                                                 | 0/50 [00:01<?, ?it/s]
ERROR - There was an error in the run, please see the log.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/py3.8/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 982, in main
    run_align_corpus(args, unknown)
  File "py3.8/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 102, in run_align_corpus
    align_corpus(args, unknown_args)
  File "py3.8/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 39, in align_corpus
    aligner.align()
  File "py3.8/lib/python3.8/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 435, in align
    self.setup()
  File "lib/python3.8/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 88, in setup
    self.load_corpus()
  File "p3.8/lib/python3.8/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 1059, in load_corpus
    self.generate_features()
  File "/py3.8/lib/python3.8/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 238, in generate_features
    self.mfcc()
  File "py3.8/lib/python3.8/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 541, in mfcc
    with open(j.feats_scp_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wav/split1/feats.0.scp'"

The Error info means that I didn't create the mfcc feature successfully, but when  I  take a look in  ~/split3/log/make_mfcc.0.log，there is no error, only one command line:
” mfa/thirdparty/bin/extract-segments scp:split3/wav.0.scp split3/segments.0.scp ark:- “

But when running with "**--disable_mp**", then output error info:
" montreal_forced_aligner.exceptions.ThirdpartyError: ThirdpartyError: Could not find 'compute-and-process-kaldi-pitch-feats'. Please ensure that you have installed MFA's "

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [CentOS Linux release 7.7.1908]

**Comment by GaryGao99** [comment]
So there is a bug : It not process the exception when use multiprocessing .
Then I fix the bug:

```
--- a/montreal_forced_aligner/corpus/acoustic_corpus.py
+++ b/montreal_forced_aligner/corpus/acoustic_corpus.py
@@ -498,6 +498,11 @@ class AcousticCorpusMixin(CorpusMixin, FeatureConfigMixin, metaclass=ABCMeta):
                         if stopped.stop_check():
                             continue
                     except Empty:
+                        if isinstance(result, Exception):
+                            key = "error"
+                            if isinstance(result, KaldiProcessingError):
+                                key = result.job_name
+                            error_dict[key] = result
                         for proc in procs:
                             if not proc.finished.stop_check():
                                 break

--- a/montreal_forced_aligner/exceptions.py
+++ b/montreal_forced_aligner/exceptions.py
@@ -125,6 +125,7 @@ class ThirdpartyError(MFAError):
         self, binary_name, open_fst=False, open_blas=False, libc=False, sox=False, error_text=None
     ):
         super().__init__("")
+        self.job_name = None
         if error_text:
             self.message_lines = [


```

**Comment by mmcauliffe** [comment]
Thanks for this, I'll make sure those get caught!  I did add a basic check for third party binaries in the initial run, but I'll expand it a bit.  Did you manage to fix the actual issue of not finding `compute-and-process-kaldi-pitch-feats`?  Is your Kaldi at the latest version, can you run that executable normally with `compute-and-process-kaldi-pitch-feats --help` and see what it outputs?

**Comment by WelkinYang** [comment]
> Thanks for this, I'll make sure those get caught! I did add a basic check for third party binaries in the initial run, but I'll expand it a bit. Did you manage to fix the actual issue of not finding `compute-and-process-kaldi-pitch-feats`? Is your Kaldi at the latest version, can you run that executable normally with `compute-and-process-kaldi-pitch-feats --help` and see what it outputs?

I have the same issue and the log shows "/usr/local/anaconda3/bin/compute-mfcc-feats: error while loading shared libraries: libfst.so.6: cannot open shared object file: No such file or directory" and i am sure the kaldi is the latest version

**Comment by GaryGao99** [comment]
> Thanks for this, I'll make sure those get caught! I did add a basic check for third party binaries in the initial run, but I'll expand it a bit. Did you manage to fix the actual issue of not finding `compute-and-process-kaldi-pitch-feats`? Is your Kaldi at the latest version, can you run that executable normally with `compute-and-process-kaldi-pitch-feats --help` and see what it outputs?

Yes, the actual issue is not finding 'compute-and-process-kaldi-pitch-feats'. 
Now MFA can run normally .

**Comment by mmcauliffe** [comment]
@WelkinYang Can you double check that you've activated the correct environment or create a new environment for MFA?  It looks like it's references the root anaconda lib directory, where it should have an environment prefixed.  The dependencies for mfa/Kaldi are little tricky when it comes to OpenFst, as Kaldi uses its own internal older version of OpenFst (1.7.6, libfst.so.16), rather than the most recent one (1.8.2, libfst.so.19).  So I don't know why it's looking for openfst.so.6 when that's a very old version that the kaldi conda forge package shouldn't be linking against.  Maybe you have an old version that was created before I took over the kaldi feedstock? It was stale for ~3 years before that, so could be the source of the libfst.so.6.  The most recent version of kaldi on conda forge should be 5.5.1016: https://anaconda.org/conda-forge/kaldi/files.

I'm going to close this since @GaryGao99 found a resolution, but feel free to open another issue if the above doesn't work, @WelkinYang .
