### ISSUE TITLE
[BUG] Can train 362 models but not one model with the same data

### ISSUE THREAD

**Issue by nrgslp** [MontrealCorpusTools/Montreal-Forced-Aligner#468]
**Debugging checklist**

[ Yes, 2.0.0rc9] Have you updated to latest MFA version?
[ Yes, I always use this flag] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
I have 362 speaker-level dirs. I can train 362 models, one for each dir. Each dir validates/trains to completion: 362 log files end with a line containing the string "Done!" and there are 362 zip files in the model output folder.

However, when I attempt to train one model on the top level of these same audio/TG directory (so, the top level dir containing 362 subdirs), the MFA does not run to completion.

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
   American English
   * How many files/speakers?
   ~172k files with 362 speakers
   * Are you using lab files or TextGrid files for input?
   TGs

2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   default librispeech.dict

3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   No - trying to train a model

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: 
 Ubuntu 20.04.4 LTS
 - Any other details about the setup (Cloud, Docker, etc)
 Running with -j 40 on a distributed supercomputing system; scheduling via Condor v 9.8.0 2022-04-21

**Additional context**
The error message changed from 2.0.0rc3 to 2.0.0.rc9 but it still does not run.

[PERCEPT2-2-1train.err.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8920500/PERCEPT2-2-1train.err.txt)
[PERCEPT2-2-1train.out.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8920501/PERCEPT2-2-1train.out.txt)

**Comment by nrgslp** [comment]
Update: I am seeing that the corpus format page implies that TG files should not be nested...

`+-- textgrid_corpus_directory
|   --- recording1.wav
|   --- recording1.TextGrid
|   --- recording2.wav
|   --- recording2.TextGrid
|   --- ...

+-- prosodylab_corpus_directory
|   +-- speaker1
|       --- recording1.wav
|       --- recording1.lab
|       --- recording2.wav
|       --- recording2.lab
|   +-- speaker2
|       --- recording3.wav
|       --- recording3.lab
|   --- ...`

So I am flattening my directory structure then will reattempt training

**Comment by mmcauliffe** [comment]
Oh no, you should be able to nest them, it just uses the directory name as the speaker name, but it does recurse through all subfolders.

Can you take a look for a `compile_train_graphs.X.log` in the `monophone/log` directory and see what's going wrong there? I don't think it's an issue is the corpus format.

**Comment by nrgslp** [comment]
Thanks for checking in!

monophone/log is empty...

**Comment by mmcauliffe** [comment]
Oh weird... Ok so in the latest log it has "Found 362 speakers across 317796 files, average number of utterances per speaker: 877.889502762431", so it looks like it parsed the directory correctly, "Generated features in 962.7053928375244" seems reasonable for generating MFCCs for that number utterances.  Maybe there was an issue in dictionary creation?  Or maybe try re-running the command to see if it generates the compile_train_graphs logs correctly?

**Comment by nrgslp** [comment]
wait my bad, I had mistyped the name of the temp dir in my sh file so I was looking in the wrong place. Here is the contents of monophone/log
[compile_train_graphs.1.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8921485/compile_train_graphs.1.log)
[compile_train_graphs.0.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8921486/compile_train_graphs.0.log)

**Comment by mmcauliffe** [comment]
Are there just the two compile_train_graph log files?  Not 40 of them?  Maybe it's an issue where one of the jobs doesn't actually have any files assigned to it due to sampling.  But it also should be subset_10000 to help get better initial sampling of rare phones... Are you using a custom configuration?  Can you try setting the subset to 10000 for that?  The current default settings are here: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/montreal_forced_aligner/acoustic_modeling/trainer.py#L92 (the docs might not reflect them yet, I'll double check).

**Comment by nrgslp** [comment]
Correct, those are the only two compile_train_graph log files. To my knowledge I am not using a custom configuration. I will pass --subset 10000 to the end of my command and give that another try. Thanks for these thoughts!

**Comment by mmcauliffe** [comment]
Ok, just to confirm the sampling gap hypothesis causing it, can you check if `text.1.2.int.scp` or if another `text.1.{0-40}.int.scp`  is missing or empty in the subset directory?

**Comment by mmcauliffe** [comment]
Aha! Ok, I'll add some better checks for that so that it doesn't jobs that don't have any data associated with them.

**Comment by nrgslp** [comment]
Roger that re: --subset flag. 

I really appreciate your responsiveness to this so I can keep chugging along...

**Comment by mmcauliffe** [comment]
@nrgslp 2.0.0 should be up on conda, can you try it out and see if it works for you?

**Comment by nrgslp** [comment]
@mmcauliffe thanks so much for this update. Training with 2.0.0 - it compiled the training graphs but crashed during generating initial alignments.

The subset_10000 dir now has [cmvn, feats, spk2utt, text, utt2spk].1.2.scp files but not x.1.4.scp and 1.1.5.scp

[train_acoustic_model.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8933579/train_acoustic_model.log)

**Comment by nrgslp** [comment]
side note - it ran perfectly with 8 jobs
