### ISSUE TITLE
Ask confirmation for cleaning the output directory

### ISSUE THREAD

**Issue by wieling** [MontrealCorpusTools/Montreal-Forced-Aligner#47]
I realize this is due to my own mistake (RTFM...), but I did not expect MFA to first remove all files and sub-directories from the specified output folder. I don't know if it is essential for the output folder to be empty, but I'd prefer a solution in which files are simply overwritten if they already exist. Even if it is essential to have an empty output directory, it might be good to ask the user (unless e.g., a -nowarn flag or so is set) confirmation for removing all contents of the folder. Otherwise, good work :)

**Comment by mmcauliffe** [comment]
Deletion of output directory no longer happens.
