### ISSUE TITLE
Very few files processed by the aligner

### ISSUE THREAD

**Issue by julianzaidi** [MontrealCorpusTools/Montreal-Forced-Aligner#48]
Hi, 

I need to process a huge audio database with the Montreal Forced Aligner tool. Typically, I have 184 actors folders and in each of these folders there are hundreds of audios with their corresponding .lab files.
However, I encounter a problem when I want to process this database with the pre-trained English model that is given with the tool 
`bin/mfa_align /path/to/librispeech/dataset /path/to/librispeech/lexicon.txt english ~/Documents/aligned_librispeech`
With this function, only 3 of my 184 folders have been processed by the aligner and contain `.TextGrid` files. Other folders are inexistant in `~/Documents/aligned_librispeech`

My audio database is of good quality, then I don't really understand why the aligner remove the large part of the data. 

Any help would be useful. Thanks.

**Comment by Tzeviya** [comment]
> Hi,
> 
> I need to process a huge audio database with the Montreal Forced Aligner tool. Typically, I have 184 actors folders and in each of these folders there are hundreds of audios with their corresponding .lab files.
> However, I encounter a problem when I want to process this database with the pre-trained English model that is given with the tool
> `bin/mfa_align /path/to/librispeech/dataset /path/to/librispeech/lexicon.txt english ~/Documents/aligned_librispeech`
> With this function, only 3 of my 184 folders have been processed by the aligner and contain `.TextGrid` files. Other folders are inexistant in `~/Documents/aligned_librispeech`
> 
> My audio database is of good quality, then I don't really understand why the aligner remove the large part of the data.
> 
> Any help would be useful. Thanks.

Hi, did you solve this somehow?
