### ISSUE TITLE
Enable ignore_case = False

### ISSUE THREAD

**Issue by ibleaman** [MontrealCorpusTools/Montreal-Forced-Aligner#487]
I'm running `mfa validate` and `mfa train` on a small corpus with a dictionary file. My dictionary entries are case-sensitive, e.g., a word like _Main_ would be defined with a different pronunciation than _main_. I see that one can specify `ignore_case` as a parameter -- but how exactly is that accomplished?

For context, I created a file named `config.yaml` containing one line:
```
ignore_case: false
```
and then ran `mfa validate --config_path config.yaml corp lex.txt`, but based on the OOV list, all words are still being converted to lowercase.

Thanks!

**Comment by mmcauliffe** [comment]
What version of MFA are you using and can you try it on the latest one?  I'm not seeing this show up when using the xsampa test data:

https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/tests/data/lab/xsampa.lab
https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/tests/data/dictionaries/xsampa.txt

**Comment by ibleaman** [comment]
@mmcauliffe My apologies for the delay! I'm returning to this now and still have the same issue.

I am using version 2.0.6, installed in the standard conda way (on Google Colab).

I've run both of these commands:

    mfa validate --config_path yid_config.yaml yid_corp yid_corp/yiddish_lexicon.txt
    mfa train --config_path yid_config.yaml --include_original_text yid_corp yid_corp/yiddish_lexicon.txt alignments

_yid_config.yaml_ contains this line:

    ignore_case: false

(I wasn't sure from the [documentation](https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/global.html) whether to capitalize _false_ but assumed from [this file](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/ed8229a3aa0580dc2a91c7a40292130cd3bc838d/tests/data/configs/xsampa_train.yaml) that I shouldn't.)

The directory _yid_corp_ consists of matched .TextGrid and .wav files, 2 tiers each, 1 per speaker, as well as the lexicon file. The lexicon file has words with both lowercase and uppercase characters, mapped onto their phones. The capitalization is important because I have many minimal pairs.

The resulting aligned .TextGrid files (including the original utterance text tier!) are entirely in lowercase. Both _oov_counts_yiddish_lexicon.txt_ and _oovs_found_yiddish_lexicon.txt_ are also all lowercase. Interestingly, _words.txt_ (inside _/Documents/MFA/yid_corp_train_acoustic_model/dictionary/1_yiddish_lexicon/_) shows the correct capitalization.

Am I using the configuration file incorrectly? Please let me know what you advise. Thank you!

**Comment by ibleaman** [comment]
@mmcauliffe Do you have any updates on this issue? Thanks!
