### ISSUE TITLE
[BUG] error using pretrained acoustic models

### ISSUE THREAD

**Issue by YugwonWon** [MontrealCorpusTools/Montreal-Forced-Aligner#495]
**Debugging checklist**

[v ] Have you updated to latest MFA version?
[v ] Have you tried rerunning the command with the `--clean` flag?

* After using the mfa g2p command, I used the mfa align command. But in mfa align I get an error.
* I'm getting pretrainedModelNotFoundError on Korean model. The commands I've tried are: I have correctly entered the path of the pretrained model as the third argument. Still it doesn't work.
```
  align_cmd = ['mfa', 'align', f'{temp_name}/in', f'{temp_name}/dict', '/Users/username/Desktop/projects/mfa/korean_mfa.zip', f'{temp_name }/out', '-t', f'{temp_name}/log', '--clean', '-v', '--config_path', '/Users/yugwon/Desktop/projects/mfa/align_config. yaml', '>', f'{os.path.join(temp_name, "align.log")}']
  os.system(' '.join(align_cmd))
```
* error msg:
```
PretrainedModelNotFoundError:

   Could not find a model named "/Users/username/Desktop/projects/mfa/tmp/4376135040/dict" for dictionary.
Traceback (most recent call last):
```

I am using mac os and I am using miniconda3 installed in python 3.8 environment.
i use 1 wav_file, 1 text_file, 5sec length wav

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [mac os]
 - Version MacOSX 12.04

**Additional context**

**Comment by mmcauliffe** [comment]
You should be able to work around it by adding ".txt" or ".dict" to the dictionary file name.  I'll add a better check for whether it should interpret it as a pretrained name versus a full path, but in general I would recommend having an explicit file extension.
