### ISSUE TITLE
[BUG] g2p stage is stale on big dataset

### ISSUE THREAD

**Issue by SolomidHero** [MontrealCorpusTools/Montreal-Forced-Aligner#514]
**Debugging checklist**

[ ] Have you updated to latest MFA version? yes montreal-forced-aligner   2.0.6            py39hadf6535_0    conda-forge
[ ] Have you tried rerunning the command with the `--clean` flag? yes

**Describe the issue**
I tried to transcribe commonvoice v10 dataset (validated part). It hangs on `mfa g2p` command.
I also successfully transcribed other small datasets like librispeech (800+ speakers, 360hrs) in the same environment with that command.

command:
```
mfa g2p --clean -j16 english_us_arpa /home/ubuntu/data/cv10/split /home/ubuntu/data/cv10/phoneme_dict.txt
```

stdout/stderr:
```
INFO - Setting up corpus information...
INFO - Loading corpus from source files...
100%|████████████████████████████████████████| 1358149/1358149 [03:39<00:00, 6189.92it/s]
INFO - Found 68782 speakers across 1358149 files, average number of utterances per speaker: 19.745703817859322
INFO - Generating pronunciations...
  2%|▉                                      | 10644/448574 [1:11:37<685:39:30,  5.64s/it]
```

It is 3+ hrs on the same progress value

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? english
   * How many files/speakers? Found 68782 speakers across 1358149 files
   * Are you using lab files or TextGrid files for input? '.lab' and '.wav'
2. G2P
   * Are you using a g2p from MFA? If so, which one? 
   * If it's a custom dictionary, what is the phoneset? -

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] ubuntu 18.04.6 LTS
 - Any other details about the setup (Cloud, Docker, etc) AWS, 16vCPU

**Comment by SolomidHero** [comment]
I reduced the number of speakers to 13k. It processed a lot, but now stale at the end of g2p:
```
INFO - Setting up corpus information...
INFO - Loading corpus from source files...
100%|██████████████████████████████████████████| 706729/706729 [01:58<00:00, 5946.05it/s]
INFO - Found 12459 speakers across 706729 files, average number of utterances per speaker: 56.724375953126255
INFO - Generating pronunciations...
100%|████████████████████████████████████████▊| 308963/309996 [19:29:28<03:08,  5.47it/s]
```
4+ hrs from this point

**Comment by lifeiteng** [comment]
@SolomidHero Have you improved the speed of G2P? too slow ...

**Comment by mmcauliffe** [comment]
You can specify an existing dictionary via `--dictionary_path`: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/dictionary_generating.html#cmdoption-mfa-g2p-dictionary_path, so that it's not re-generating pronunciations that already exist.

**Comment by lifeiteng** [comment]
> You can specify an existing dictionary via `--dictionary_path`: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/dictionary_generating.html#cmdoption-mfa-g2p-dictionary_path, so that it's not re-generating pronunciations that already exist.

`mfa g2p ${my_corpus} english_us_arpa ${my_corpus}/g2pped_oovs.txt --dictionary_path english_us_arpa`
on a corpus which has 580 hours data
