### ISSUE TITLE
[BUG] IndexError: list out of range. Happened on utterance with word starting with clitic

### ISSUE THREAD

**Issue by SolomidHero** [MontrealCorpusTools/Montreal-Forced-Aligner#520]
**Debugging checklist**

[ ] Have you updated to latest MFA version?
[ ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

`mfa align --clean ` ... failes every time.

I also put try/catch block on if at `multiprocessing.py:833` with print
```
print(utterance_name, words_index, words, utterance_begin, intervals)
```

Print:
`6501 12 ['the', 'stores', 'were', 'rebranded', 'as', 'either', 'the', 'local', "'thresher", 'or', 'wine', 'rack'] 0.0 [CtmInterval(begin=0.0, end=0.06, label='1', utterance=6501), CtmInterval(begin=0.06, end=0.62, label='1', utterance=6501), CtmInterval(begin=0.62, end=0.64, label='DH', utterance=6501), CtmInterval(begin=0.64, end=0.7, label='AH0', utterance=6501), CtmInterval(begin=0.7, end=0.81, label='S', utterance=6501), CtmInterval(begin=0.81, end=0.87, label='T', utterance=6501), CtmInterval(begin=0.87, end=1.01, label='AO1', utterance=6501), CtmInterval(begin=1.01, end=1.11, label='R', utterance=6501), CtmInterval(begin=1.11, end=1.19, label='Z', utterance=6501), CtmInterval(begin=1.19, end=1.25, label='W', utterance=6501), CtmInterval(begin=1.25, end=1.32, label='ER0', utterance=6501), CtmInterval(begin=1.32, end=1.43, label='R', utterance=6501), CtmInterval(begin=1.43, end=1.5, label='IY0', utterance=6501), CtmInterval(begin=1.5, end=1.57, label='B', utterance=6501), CtmInterval(begin=1.57, end=1.66, label='R', utterance=6501), CtmInterval(begin=1.66, end=1.76, label='AE2', utterance=6501), CtmInterval(begin=1.76, end=1.8, label='N', utterance=6501), CtmInterval(begin=1.8, end=1.84, label='D', utterance=6501), CtmInterval(begin=1.84, end=1.9, label='IH0', utterance=6501), CtmInterval(begin=1.9, end=1.95, label='D', utterance=6501), CtmInterval(begin=1.95, end=2.18, label='AE1', utterance=6501), CtmInterval(begin=2.18, end=2.29, label='Z', utterance=6501), CtmInterval(begin=2.29, end=2.48, label='AY1', utterance=6501), CtmInterval(begin=2.48, end=2.54, label='DH', utterance=6501), CtmInterval(begin=2.54, end=2.71, label='ER0', utterance=6501), CtmInterval(begin=2.71, end=2.88, label='1', utterance=6501), CtmInterval(begin=2.88, end=2.99, label='DH', utterance=6501), CtmInterval(begin=2.99, end=3.08, label='AH0', utterance=6501), CtmInterval(begin=3.08, end=3.18, label='L', utterance=6501), CtmInterval(begin=3.18, end=3.3, label='OW1', utterance=6501), CtmInterval(begin=3.3, end=3.41, label='K', utterance=6501), CtmInterval(begin=3.41, end=3.43, label='AH0', utterance=6501), CtmInterval(begin=3.43, end=3.49, label='L', utterance=6501), CtmInterval(begin=3.49, end=3.59, label='spn', utterance=6501), CtmInterval(begin=3.59, end=3.79, label='1', utterance=6501), CtmInterval(begin=3.79, end=3.95, label='TH', utterance=6501), CtmInterval(begin=3.95, end=4.03, label='R', utterance=6501), CtmInterval(begin=4.03, end=4.07, label='EH1', utterance=6501), CtmInterval(begin=4.07, end=4.2, label='SH', utterance=6501), CtmInterval(begin=4.2, end=4.32, label='ER0', utterance=6501), CtmInterval(begin=4.32, end=4.63, label='1', utterance=6501), CtmInterval(begin=4.63, end=4.82, label='AO1', utterance=6501), CtmInterval(begin=4.82, end=4.94, label='R', utterance=6501), CtmInterval(begin=4.94, end=5.04, label='1', utterance=6501), CtmInterval(begin=5.04, end=5.18, label='W', utterance=6501), CtmInterval(begin=5.18, end=5.31, label='AY1', utterance=6501), CtmInterval(begin=5.31, end=5.35, label='N', utterance=6501), CtmInterval(begin=5.35, end=5.47, label='R', utterance=6501), CtmInterval(begin=5.47, end=5.57, label='AE1', utterance=6501), CtmInterval(begin=5.57, end=5.8, label='220', utterance=6501), CtmInterval(begin=5.8, end=6.82, label='1', utterance=6501)]`

Error:
```
INFO - Setting up corpus information...
INFO - Loading corpus from source files...
100%|████████████████████████████████████████████| 49274/49274 [00:09<00:00, 5396.06it/s]
INFO - Found 650 speakers across 49274 files, average number of utterances per speaker: 75.80615384615385
INFO - Initializing multiprocessing jobs...
INFO - Creating corpus split for feature generation...
INFO - Generating base features (mfcc)...
INFO - Generating MFCCs...
100%|████████████████████████████████████████████▉| 49270/49274 [07:16<00:00, 112.88it/s]
INFO - Calculating CMVN...
INFO - Creating corpus split with features...
INFO - Compiling training graphs...
100%|█████████████████████████████████████████████| 49274/49274 [01:05<00:00, 757.92it/s]
INFO - Performing first-pass alignment...
INFO - Generating alignments...
100%|████████████████████████████████████████████▉| 49228/49274 [03:00<00:00, 272.79it/s]
INFO - Calculating fMLLR for speaker adaptation...
100%|██████████████████████████████████████████████████| 650/650 [01:56<00:00,  5.57it/s]
INFO - Performing second-pass alignment...
INFO - Generating alignments...
100%|████████████████████████████████████████████▉| 49262/49274 [02:51<00:00, 287.45it/s]
INFO - Exporting TextGrids to /home/ubuntu/data/cv10/split...
INFO - Collecting phone and word alignments from alignment lattices...
  6%|██▋                                          | 2973/49274 [00:08<00:39, 1187.16it/s]
  6%|██▉                                           | 3137/49274 [00:21<05:20, 144.12it/s]
ERROR - There was an error in the run, please see the log.
MultiprocessingError:

  Job 2 encountered an error:
  Traceback (most recent call last):

    File "/home/ubuntu/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/abc.py", line 73, in
    run
      yield from self._run()

    File
    "/home/ubuntu/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/multiprocessing.py",
     line 994, in _run
      word_intervals, phone_intervals = self.cleanup_intervals(

    File
    "/home/ubuntu/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/multiprocessing.py",
     line 856, in cleanup_intervals
      raise e

    File
    "/home/ubuntu/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/multiprocessing.py",
     line 840, in cleanup_intervals
      or words[words_index].endswith(self.clitic_marker)

  IndexError: list index out of range
```

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? english
   * How many files/speakers? 18k speakers, 1105k files
   * Are you using lab files or TextGrid files for input? .lab + .wav
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? english_us_arpa
   * If it's a custom dictionary, what is the phoneset? concatenated with g2p on oov_words
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * If it's a model you've trained, what data was it trained on?

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] ubuntu
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] 18.04
 - Any other details about the setup (Cloud, Docker, etc) -

**Comment by SolomidHero** [comment]
@mmcauliffe 
how it works with such below sentences?
```
["More recently, advances in sensing and computing technology have given rise to 'predictive maintenance'.",
 "For simplicity, 'gear inches' is normally rounded to the nearest whole number.",
 "An X terminal runs an X 'server'.",
 "There's one that says, 'Everything that happens once can never happen again.",
 "Yet all of the body language here is 'go away.",
 "Undefined reference to 'swizzle'.",
 "Doug Church also was very involved as a 'Creative Editor' on covers, layouts, features.",
 "The ticket office, on the 'up' side, is situated in the substantial station building.",
 "This can be achieved by a filter with a 'sinc' impulse response.",
 'Her motto was "Surtout Loyal", which translates to \'Loyal above all\'.']
```

**Comment by MicaelLemelin** [comment]
Hi!

I'm having the same issue. When trying here and there different settings, it seems to be happening only when aligning a large amount of files. Thats something I also see in the original bug.

The original poster has 49274 :

> Found 650 speakers across 49274 files

and me 39796.

> Found 7403 speakers across 39796 files

I can generate smaller chunks without issue but when going for the whole directory I get ignored files during MFCCs generation and this issue.

I'm going to try to align parts of the total corpus one by one to see if it could be a workaround.

**Comment by MicaelLemelin** [comment]
> Hi!
> 
> I'm having the same issue. When trying here and there different settings, it seems to be happening only when aligning a large amount of files. Thats something I also see in the original bug.
> 
> The original poster has 49274 :
> 
> > Found 650 speakers across 49274 files
> 
> and me 39796.
> 
> > Found 7403 speakers across 39796 files
> 
> I can generate smaller chunks without issue but when going for the whole directory I get ignored files during MFCCs generation and this issue.
> 
> I'm going to try to align parts of the total corpus one by one to see if it could be a workaround.

This was incorrect in the end. But I identified the line with the issue. I'll keep looking. I see 'thresher in the original report words and my line also have a word that starts with an '. Actually a 't wich is a clitic marker if I'm correct. My word starts with an S so its 's. Also a clitic marker. Maybe that's part of what is going on.

**Comment by himilu728** [comment]
Are you solve this problem? how?

**Comment by himilu728** [comment]
Are you solving this problem? how?

**Comment by MicaelLemelin** [comment]
@himilu728 Well, I'm not very acquainted with the mfa source code so I haven't solved it per say. (I have no code fix nor MR). Although, right now I have a workaround which is to do a first pass on the text before sending it to mfa. I use a regex to identify words starting with ' and remove the '. It at least allows me to align the text.

For example,  " 'since " becomes " since ". I don't think its a perfect solution but it unblocked me for now :)
