### ISSUE TITLE
[BUG] create_segments stops because of pickle error?

### ISSUE THREAD

**Issue by jhdeov** [MontrealCorpusTools/Montreal-Forced-Aligner#522]
**Debugging checklist**

[ x] Have you updated to latest MFA version?
[x ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
I wanted to see what `create_segments` does. So I made a simple test sound file in a test folder. I ran the command:

`mfa create_segments /Users/Hovsep/Desktop/test /Users/Hovsep/Desktop/test_output --clean`

But while it tries to calculate the VAD, it just stops and says there was a pickling error.

I put the print outs here: https://dpaste.com/HFL4CS2BP

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? English
   * How many files/speakers? 1 file, 1 speaker
   * Are you using lab files or TextGrid files for input? no
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? no
   * If it's a custom dictionary, what is the phoneset? no
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? no
   * If it's a model you've trained, what data was it trained on? no

**Log file**
[segmentation.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/9972376/segmentation.log)

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: MacOSX 10.15.7

**Comment by mmcauliffe** [comment]
Next version will have a revamped segmentation/diarization workflow, so this should be working again.
