### ISSUE TITLE
[BUG] Deprecation warning with Bio.pairwise2

### ISSUE THREAD

**Issue by sidhiadkoli** [MontrealCorpusTools/Montreal-Forced-Aligner#527]
**Issue**

`Bio.pairwise2` appears to be deprecated in the latest version [v1.8](https://github.com/biopython/biopython/blob/master/DEPRECATED.rst#biopairwise2) of `biopython`.

Warning message:

`/home/[USER]/.conda/envs/aligner/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.`

**Reproducing this issue**

Install dependencies via conda:  `conda create -n aligner -c conda-forge montreal-forced-aligner`

**Desktop:**

 - OS: Linux
 - Version: Ubuntu 18.04.6 LTS
 - Any other details about the setup: MFA install via conda in a Docker container.

**Comment by n8young** [comment]
Having the same issue on Mac OS 13.0.1 (22A400). Gets stuck at 11%

**Comment by Ma-Hansen** [comment]
I encountered the same issue today. Is V2.1 already launched or is it about to happen and this should then resolve the issue?
