### ISSUE TITLE
generate new language dict failed.

### ISSUE THREAD

**Issue by attitudechunfeng** [MontrealCorpusTools/Montreal-Forced-Aligner#53]
I want to generate mandarin dict using the g2p model advised in the tutorial. But when i run the example, errors like "FileNotFoundError: [Errno 2] No such file or directory: 'phonetisaurus-g2pfst'" occurred. Can anybody tells me how to fix this problem?

**Comment by Jackiexiao** [comment]
Have you generate mandarin dict  successfully?
