### ISSUE TITLE
[BUG] G2P Won't Train

### ISSUE THREAD

**Issue by NataliaShmueli** [MontrealCorpusTools/Montreal-Forced-Aligner#557]
**Debugging checklist**

[ x] Have you updated to latest MFA version?
[ x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
**Trying to run the G2P on a German dictionary with appended --phonetisaurus and model refuses to load. I also have -j 4 and the --temp_directory redirecting to my K: drive. I've run it before, but I wanted to fix about 20 words, and now in 2.1.3, it won't run.** 

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
   * **N/A**
   * How many files/speakers?
   * **N/A**
   * Are you using lab files or TextGrid files for input?
   * **N/A**
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * **My own German phonetic dictionary with approx. 250k entries**
   * If it's a custom dictionary, what is the phoneset?
   * **X-SAMPA**
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * **N/A**
   * If it's a model you've trained, what data was it trained on?
   * **N/A**

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).
[German.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10702785/German.log)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux]
 - **Windows**
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]
 - **10**
 - Any other details about the setup (Cloud, Docker, etc)
 - **N/A**

**Additional context**
![image](https://user-images.githubusercontent.com/66705387/217973685-25a84d22-a985-4ba5-80ac-c91fc47677a3.png)
Here is a photo. It's been at this stage for about an hour now.

**Comment by mmcauliffe** [comment]
Can you try updating to the latest version `conda update montreal-forced-aligner pgvector`?  I fixed a couple of issues that could be affecting the start up here, but you might also need to delete the pg_mfa_global directory in the temporary folder to clear out the previous failed runs after updating.

**Comment by NataliaShmueli** [comment]
Trying to update gives me `PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\Natalia\miniconda3
  package name: montreal-forced-aligner`
  
 I deleted everything from my temp directory, and it worked with a standard G2P model, but when I re-deleted everything and ran with --phonetisaurus, it wouldn't run again.

**Comment by NataliaShmueli** [comment]
Wait, I updated via `conda create -n aligner -c conda-forge montreal-forced-aligner` and that did something, but it's still on 1.2.3, it seems. I then cleaned the temp folder, and it's training now, it seems.

**Comment by mmcauliffe** [comment]
Ok sounds like it's working, so I'll close this out
