### ISSUE TITLE
[BUG] G2P Won't Export

### ISSUE THREAD

**Issue by NataliaShmueli** [MontrealCorpusTools/Montreal-Forced-Aligner#560]
**Debugging checklist**

[ x] Have you updated to latest MFA version?
[ x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
**Updated to 2.1.5, and for some reason, it will state the exported G2P is "not found" even though the system itself if exporting it.**

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
   * **French**
   * How many files/speakers?
   * **N/A**
   * Are you using lab files or TextGrid files for input?
   * **N/A**
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * **My own**
   * If it's a custom dictionary, what is the phoneset?
   * **X-SAMPA**
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * **N/A**
   * If it's a model you've trained, what data was it trained on?
   * **N/A**

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).
[MLFrenchOOVs.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10716936/MLFrenchOOVs.log)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux]
 - **Windows**
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**

**Comment by mmcauliffe** [comment]
What's the exact command you're running?  Does the directory you're trying to export to exist?

**Comment by NataliaShmueli** [comment]
Sorry, I didn't mean to open two of them; I thought the first never posted. The command line was `mfa g2p C:\Users\Natalia\Desktop\Dictionaries\French\OOVs\MLFrenchTest.txt C:\Users\Natalia\Desktop\Dictionaries\French\FrenchAbrvG2P.zip C:\Users\Natalia\Desktop\Dictionaries\French\Output\MLFrenchOutputTest.txt --clean --verbose -j 4 --temporary_directory K:\ToTrain`. The directory did not exist but does now. Originally, in 1.2.2 and previously, it did not need the directory created, prior and it made it. Moving forward, should I plan for that now?

**Comment by mmcauliffe** [comment]
Did it? It will make directories that don't exist if the output specified is a directory (like exporting textgrids), but I don't recall and can't see any functionality in previous versions that would have made any directory structure for when just a full file path is specified like a g2pped file.

I'll add better validation for existence of directories of files specified, but I'm always a little leery about automatically making things when non-existence could be the result of typos etc.

**Comment by NataliaShmueli** [comment]
Yeah, it would export the output .txt file with it in the specified directory. But now that I know this, I can 100% make a new folder for it to deposit into. Thank you!
