### ISSUE TITLE
[BUG] G2P Export Issues

### ISSUE THREAD

**Issue by NataliaShmueli** [MontrealCorpusTools/Montreal-Forced-Aligner#561]
**Debugging checklist**

[ x] Have you updated to latest MFA version?
[ x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
**Updated MFA to 2.1.5, and for some reason, it won't export the list of words ran on the G2P claiming "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Natalia\\Desktop\\Dictionaries\\French\\Output\\MLFrenchOutput.txt'"**

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
   * **French**
   * How many files/speakers?
   * **N/A**
   * Are you using lab files or TextGrid files for input?
   * **N/A**
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * **Self-made**
   * If it's a custom dictionary, what is the phoneset?
   * **X-SAMPA**
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * **N/A**
   * If it's a model you've trained, what data was it trained on?
   * **N/A**

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).
[MLFrenchOOVs.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10717306/MLFrenchOOVs.log)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux]
 - **Windows**
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]
 - **10**
 - Any other details about the setup (Cloud, Docker, etc)
 - **None**

**Additional context**
![image](https://user-images.githubusercontent.com/66705387/218337163-6b21043d-902f-4850-a041-0e00302a02fc.png)

**Comment by mmcauliffe** [comment]
Yes, but like I said in #560, does the `C:\Users\Natalia\Desktop\French\Output` directory exist?  If not, create it and it should work.

**Comment by NataliaShmueli** [comment]
Oh weird, it posted this twice, sorry! Testing now.
