### ISSUE TITLE
[BUG] Training Fails on Corpus

### ISSUE THREAD

**Issue by NataliaShmueli** [MontrealCorpusTools/Montreal-Forced-Aligner#563]
**Debugging checklist**

[ x] Have you updated to latest MFA version?
[ x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
**I am attempting to train a model of MLS Polish, but it keeps crashing. I then tried converting all the files to .mp3, which has zero corruption (checked with Audacity). The samples do not go past 20 seconds at most. The command I'm running is `mfa train K:\Training_Models\Spoken\Polish\mls_polish\PolishMP3 C:\Users\Natalia\Desktop\Dictionaries\Polish\PolishFull.txt C:\Users\Natalia\Desktop\Dictionaries\Polish\PolishAligner.zip --clean --verbose -j 4 --output_directory C:\Users\Natalia\Desktop\Dictionaries\Polish\PolishTextGrids`. I even increased the beam settings to 20:80 and higher, but nothing. Strangely enough, the Russian LibriSpeech corpus, which is set up the exact same way did train, but is .wav?**

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
   * **Polish**
   * How many files/speakers?
   * **19 speakers**
   * Are you using lab files or TextGrid files for input?
   * **.labs**
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * **Own**
   * If it's a custom dictionary, what is the phoneset?
   * **X-SAMPA**
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * **None**
   * If it's a model you've trained, what data was it trained on?
   * **None**
**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).
[PolishMP3.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10728082/PolishMP3.log)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux]
 - **Windows**
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]
 **10**
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**
![image](https://user-images.githubusercontent.com/66705387/218623872-30d55863-3c3c-44ce-a50f-b7fc71e01a36.png)

**Comment by NataliaShmueli** [comment]
Why does it keep posting before I'm ready? Anyways, the samples are not long enough to get the errors and not train, but it might be a file type error.

**Comment by mmcauliffe** [comment]
Can you check the `make_mfccs` log? Likely there's something going wrong in feature generation.  Can you try updating `conda update sox` to ensure sox is up-to-date?

**Comment by NataliaShmueli** [comment]
[make_mfcc.1.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10728727/make_mfcc.1.log)
`make_mfcc.1.log` says no specific errors. I also ran `conda update sox` and it updated but now won't train at all?
![image](https://user-images.githubusercontent.com/66705387/218638400-2f27f2d4-45a9-4c3a-9ee6-23bafa9eb02b.png)

**Comment by mmcauliffe** [comment]
I'd just remake the environment, dunno what happened to soundfile dependencies during the update.

**Comment by mmcauliffe** [comment]
> Why does it keep posting before I'm ready? Anyways, the samples are not long enough to get the errors and not train, but it might be a file type error.

I don't understand what you mean by this.  Are the lengths being reported not right?  If they should be longer than what's being reported by the alignment (len =number of frames per 10 ms, so divide by 100 to get seconds).  Or do you mean that you're you training with less than 10000 utterances?

Also check the compile_train_graphs logs, see if there's anything weird there.

**Comment by NataliaShmueli** [comment]
[compile_train_graphs.1.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10729139/compile_train_graphs.1.log)
There is no issue with compiling training graphs. I completely deleted conda and reinstalled it, yet it's giving the same issue. There also don't seem to be any issues with the MFCC creation or final feature creation.

**Comment by mmcauliffe** [comment]
You can try converting the files to wav, but I think it's likely a data issue in transcriptions not matching up, lacking coverage in dictionary or something else wonky in the input files.  The issue is that no files are getting aligned after the initial round, but I have not seen that occur in any of my testing, and you're not getting it on other corpora, so my guess is that it's something particular with this dataset.
