### ISSUE TITLE
Collecting phone and word alignments from alignment lattices

### ISSUE THREAD

**Issue by jiaqiAA** [MontrealCorpusTools/Montreal-Forced-Aligner#573]
Hi,
How to deal with 
`praatio.utilities.errors.CollisionError: Attempted to insert interval (544.82, 545.05, 'neng2') into tier words of textgrid but overlapping entries 
    [(544.651, 544.821, 'you3')] already exist `
Thanks!

**Comment by mmcauliffe** [comment]
Is this on the latest version (2.2.X)?

**Comment by jiaqiAA** [comment]
montreal-forced-aligner   2.1.5

**Comment by mmcauliffe** [comment]
Can you update via `conda update montreal-forced-aligner` to the latest version and see if the behavior is the same?

**Comment by jiaqiAA** [comment]
I use `montreal-forced-aligner  2.2.3`, but it still has the same problem.

**Comment by jiaqiAA** [comment]
I fix it.
I meet another error
`sqlalchemy.exc.OperationalError: (psycopg2.errors.ProgramLimitExceeded) index row size 4288 exceeds btree version 4 maximum 2704 for index "ix_utterance_text"
DETAIL:  Index row references tuple (0,5) in relation "utterance".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.`
Do you know how to solve it?
Thanks!

**Comment by mmcauliffe** [comment]
Ah that usually means that MFA is trying to parse a file that is too big, like using a file that contains metadata for all utterances in the corpus, tens of thousands of lines long and treating it as an "utterance", rather than skipping it.  What command were you running when you encountered it?

**Comment by jiaqiAA** [comment]
The exact command I run is `mfa align data mandarin_mfa mandarin_mfa`.
Can't MFA parse a file that's too big? How do I solve this problem?

**Comment by DingouerFish** [comment]
> The exact command I run is `mfa align data mandarin_mfa mandarin_mfa`. Can't MFA parse a file that's too big? How do I solve this problem?
latest version 2.2.4
 same problem  @mmcauliffe

**Comment by mmcauliffe** [comment]
How long are your audio files?  Is there some really large text file associated with one of them?

**Comment by DingouerFish** [comment]
audio file: 21mins08s, file size: 20.3MB
lab file: 379lines, 12187 characters, file size: 12KB

**Comment by mmcauliffe** [comment]
Yeah, that's longer than I would expect a decent alignment to come out.  You can try increasing the buffer sizes for the postgresql via the settings in postgres.conf like in https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/server/index.html, but I would say that you're likely going to need to increase the beam size quite a bit to get it to align, depending on the quality of the transcription.  For reference, I usually have sub 2 minute files/intervals for training data, but I haven't really explored or optimized for longer file alignments.

**Comment by DingouerFish** [comment]
well, but the HIT from the error message is  "Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing",  I am not sure which config item of postgres.conf  file relates to this issue, I guess,  according the HIT the only way to solve this problem is to change the  index "ix_utterance_text" to MD5 hash based index or full text index, but I don't know how, can you please tell me how ? Thanks a lot.

**Comment by pxcai** [comment]
Hi, I also suffer the same problem with you. 
`praatio.utilities.errors.CollisionError: Attempted to insert interval (203.719, 203.939, 'mi4') into tier words of textgrid but overlapping entries [(203.64, 203.72, 'de5')] already exist`
Could you give me some advice for this problem? Are you a Chinese? Could you tell me your e-mail or wechat?
