### ISSUE TITLE
[BUG] MFA2 performances issue

### ISSUE THREAD

**Issue by nbusser** [MontrealCorpusTools/Montreal-Forced-Aligner#578]
**Debugging checklist**

[x] Have you updated to latest MFA version?
[x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
Hi ! I noticed big performance downgrade from MFA 1 to MFA 2.  

Our program calls MFA's g2p module multiple times, via command line, on single french words that cannot be found in the dictionary.

With french prosodylab g2p model, a g2p operation on a single word takes around:  
- MFA 1:  0.3 second
- MFA 2: 8 seconds 
We noticed a long initialization time for each MFA 2 calls, including database initialization and stuff.

I tried to play with `--use_mp` and `-j` argument, but it does not change anything.

Is there somewhat a way to keep MFA session alive between calls?

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Manjaro
 - Any other details about the setup: we performed the MFA 2 calls on Docker

**Comment by mmcauliffe** [comment]
This should be resolved with the latest versions, you can pipe stdin/stdout to mfa g2p now and it will skill the overhead of the larger data prep steps: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/dictionary_generating.html#piping-stdin-stdout
