### ISSUE TITLE
[BUG]there are incompatible upgrade in parratio==6.0.0

### ISSUE THREAD

**Issue by yt605155624** [MontrealCorpusTools/Montreal-Forced-Aligner#579]
please check https://github.com/timmahrt/praatIO/issues/54

**Comment by mmcauliffe** [comment]
Have you upgraded to the latest version of MFA?  Everything should be working for PraatIO 6.0.0 from MFA 2.1 onward.

**Comment by yt605155624** [comment]
that's great, I just found this bug in PaddleSpeech and thought MFA also rely on parratio, so here to remind you 😁
