### ISSUE TITLE
MFA didn't generate all the textgrid file for wav

### ISSUE THREAD

**Issue by Jackiexiao** [MontrealCorpusTools/Montreal-Forced-Aligner#58]
I have trained my own acoustic model and align some wav files, but the strange thing is that it only generate some textgrid files and ignore other wav file (these audio are recorded in the same environment). Do there anyone have the same problem?

**Comment by mmcauliffe** [comment]
In general, files with bad alignments (usually for just a part of a file, like a mispronunciation or a hesitation or extra content not in the transcription) don't have alignments generated.  For the next release, there will be some configuration that users can do to allow these worse alignments and still output files, I just need to get time to finish it up and release it.

**Comment by Jackiexiao** [comment]
@mmcauliffe Looking forward to it
