### ISSUE TITLE
Possible to re-use trained GMM/HMM for additional aligning

### ISSUE THREAD

**Issue by lematt1991** [MontrealCorpusTools/Montreal-Forced-Aligner#582]
Is it possible to re-use the GMM/HMM model that was trained in a call to `mfa align ...` for aligning new transcribed audio files?  If I align a corpus once, and then want to align more transcribed audio coming from a similar distribution, but want to skip all of the steps of the `mfa align` command, is it possible to re-use the model that was trained the first time?  

My motivation is: I have a very large corpus that I would like to align (60k+ hours/17M utterances), but `mfa align` is taking way too long.  I'd like to train a model on a subset of the data, and then distribute the aligning process across many machines.  Is this kind of workflow possible?

**Comment by mmcauliffe** [comment]
Do you mean you used `mfa train ...` to train a new model?  `mfa align` uses a pretrained model and calculates per-speaker feature transforms, but it doesn't do any training.  So yes, if you split up the corpus into subsets (with making sure a given speaker's utterances aren't split up), then it should have the same performance as aligning the whole.

**Comment by lematt1991** [comment]
Thanks for the clarification.  Running multiple `align` workflows in subsets of the data (split by subsets of speakers) ended up working.  Thanks
