### ISSUE TITLE
Compilation issue 

### ISSUE THREAD

**Issue by cveaux** [MontrealCorpusTools/Montreal-Forced-Aligner#59]
Hi, thanks for this great tool! I'm trying it install it on  a ppc64 machine with Ubuntu-16.04. 
It didn't work from the tar.gz archive for Linux, as I got a "wrong executable format" for thebin/mfa_train_and_align (which I guess is because I'm on a ppc64). Therefore I'm trying to compile it from source (I have already Kaldi installed). However, when I run `freezing/freeze.sh` I got this error message:

`Failure: objcopy: Unable to recognise the format of the input file /home/support/alignement/Montreal-Forced-Aligner-1.0.0/build/train_and_align/train_and_align'`

Can you tell me which format are these files so I can specify it manually to objcopy? 

Thanks

**Comment by mmcauliffe** [comment]
Hm, I haven't seen anything like that before, it might be related to architecture as well?  You could try running MFA as a module, as a workaround.

From the root MFA directory:

```
python -m aligner.command_line.train_and_align
python -m aligner.command_line.align
python -m aligner.command_line.generate_dictionary
python -m aligner.command_line.train_g2p
```

And then that command would replace the calls to `bin/mfa_train_and_align`, `bin/mfa_align`, etc. in any examples in the documentation.

**Comment by cveaux** [comment]
Thanks for the quick reply, didn't thought of it, it will very well do as a workaround.
