### ISSUE TITLE
[BUG] Issue with TextGrids Incorrectly Aligning

### ISSUE THREAD

**Issue by NataliaShmueli** [MontrealCorpusTools/Montreal-Forced-Aligner#592]
**Debugging checklist**

[x ] Have you updated to latest MFA version?
[x ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
**For TextGrid-based alignments, the timing connects it automatically, leading to incorrect alignments on pre-sections. (Apologies, I don't know how to explain this and attached photos).**

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
   * **Korean**
   * How many files/speakers?
   * **40 speakers/ 240 samples (Seoul Corpus)**
   * Are you using lab files or TextGrid files for input?
   * **TextGrid**
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * **Custom**
   * If it's a custom dictionary, what is the phoneset?
   * **X-SAMPA**
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * **N/A**
   * If it's a model you've trained, what data was it trained on?
   * **The Seoul Corpus**

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).
[Model.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10975570/Model.log)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux]
 - **Windows**
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]
 - **10**
 - Any other details about the setup (Cloud, Docker, etc)
 - **N/A**

**Additional context**
**The early parts of utterances keep moving beforehand, leading to strange alignments.
Before:
![Before](https://user-images.githubusercontent.com/66705387/225193044-526c48a9-14f6-4a87-85b3-83b904826fe3.png)

After:
![After](https://user-images.githubusercontent.com/66705387/225193084-511369f6-de88-4507-a22a-a8fdef77fd78.png)
**

**Comment by NataliaShmueli** [comment]
I updated it to 2.2.6, and I figured out the issue. It's automatically removing word boundaries/spacing and making them touch, leading to incorrect spacing. This only occurs after the beginning of the utterance though. It's even doing this on corpora that only use .lab (such as this Russian one from MAI Labs), not just longer audio that uses .TextGrids.
![image](https://user-images.githubusercontent.com/66705387/226492262-efe84b4c-8bc6-4c9f-8b4c-b599df402da1.png)

**Comment by massimolipari** [comment]
This seems to be the same issue as #603. I've gotten around it by adding the --no_textgrid_cleanup flag

**Comment by NataliaShmueli** [comment]
@massimolipari **_thank you thank you so much_**. All I'll do is remove "sil" from all of these. It's definitely an issue with --textgrid_cleanup

![image](https://user-images.githubusercontent.com/66705387/229377368-18344bc0-668c-4e2d-8d44-932cd64380fa.png)
![image](https://user-images.githubusercontent.com/66705387/229381349-792dbd83-c91e-482e-810e-80871e470e0c.png)

**Comment by NataliaShmueli** [comment]
How strange! It still seems to have some issues with some TextGrid models, such as the Seoul corpus, but otherwise, we have great results! Thanks again!
![image](https://user-images.githubusercontent.com/66705387/229609899-839ea0b7-0a93-4457-a9a8-47787bc13bf3.png)
