### ISSUE TITLE
[BUG] KaldiProcessing error, running Kaldi binaries

### ISSUE THREAD

**Issue by thomasles566** [MontrealCorpusTools/Montreal-Forced-Aligner#597]
**Debugging checklist**

[YES ] Have you updated to latest MFA version?
[YES ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
I'm attempting to validate a small speech corpus taken from a larger dataset: 1 speaker, 20 files. The data consist of short, phrase-level extractions from a sociolinguistic interview. After multiple attempts with `mfa validate` and `--clean`, I'm still receiving the same error. What's surprising is that I ran the LibriSpeech example and everything worked fine. I also noticed that after the failed validate runs, the files were deleted from the input directory.

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? **Spanish (Colombian)**
   * How many files/speakers? **20 files, 1 speaker**
   * Are you using lab files or TextGrid files for input? **TextGrid**
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? **Yes, Spanish MFA dictionary v2.0.0a**
   * If it's a custom dictionary, what is the phoneset? N/A
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? **Yes, Spanish MFA acoustic model v2.0.0a**
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

```
(aligner) C:\Users\thoma>mfa validate C:\Users\thoma\Documents\MFA spanish_mfa spanish_mfa --clean
waiting for server to start.... done
server started
 INFO     Setting up corpus information...
 INFO     Loading corpus from source files...
   1% ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/100  [ 0:00:18 < -:--:-- , ? it/s ]
 INFO     Found 1 speaker across 10 files, average number of utterances per speaker: 10.0
 INFO     Initializing multiprocessing jobs...
 WARNING  Number of jobs was specified as 3, but due to only having 1 speakers, MFA will only use 1 jobs. Use the
          --single_speaker flag if you would like to split utterances across jobs regardless of their speaker.
 INFO     Normalizing text...
  10% ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/10  [ 0:00:16 < -:--:-- , ? it/s ]
 INFO     Creating corpus split for feature generation...
   5% ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/20  [ 0:00:14 < -:--:-- , ? it/s ]
 INFO     Generating MFCCs...
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/10  [ 0:00:09 < -:--:-- , ? it/s ]
 ERROR    There was an error in the run, please see the log.
 INFO     Stopping the global MFA database server...
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x00000121D7AA23B0>>
Traceback (most recent call last):
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\mfa.py", line 102, in history_save_handler
    raise self.exception
  File "C:\Users\thoma\miniconda3\envs\aligner\Scripts\mfa-script.py", line 9, in <module>
    sys.exit(mfa_cli())
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\rich_click\rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\validate.py", line 113, in validate_corpus_cli
    validator.validate()
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\validation\corpus_validator.py", line 595, in validate
    self.setup()
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\validation\corpus_validator.py", line 575, in setup
    self.generate_features()
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\acoustic_corpus.py", line 464, in generate_features
    self.mfcc()
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\acoustic_corpus.py", line 669, in mfcc
    for _ in run_kaldi_function(MfccFunction, arguments, pbar.update):
  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\utils.py", line 753, in run_kaldi_function
    raise v
montreal_forced_aligner.exceptions.MultiprocessingError: MultiprocessingError:

Job 1 encountered an error:
Traceback (most recent call last):

  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\abc.py", line 89, in run
    yield from self._run()

  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\features.py", line 548, in _run
    self.check_call(mfcc_copy_proc)

  File "C:\Users\thoma\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\abc.py", line 116, in check_call
    raise KaldiProcessingError([self.log_path])

montreal_forced_aligner.exceptions.KaldiProcessingError: KaldiProcessingError:

There were 1 job(s) with errors when running Kaldi binaries.
See the log files below for more information.
C:\Users\thoma\Documents\MFA\MFA\MFA\split3\log\make_mfcc.1.log
```
[make_mfcc(LOGFILE).1.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/11033922/make_mfcc.LOGFILE.1.log)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] Windows
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] Windows 10
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**
**SAMPLE FILES**
[MFA_sample.zip](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/11033883/MFA_sample.zip)

**Comment by mmcauliffe** [comment]
So it says: `sox FAIL formats: can't open input file `C:\Users\thoma\Documents\MFA\data\allá9.wav': No such file or directory`  Is that the correct path to one of the sound files?  It's not corrupted or anything, correct?  If that's what it should  be, then you can try renaming it to ascii only (i.e., sub `a` for `á`), though I do have tests for unicode file names on windows and they are passing, but that could be due to my local set up.   I'll see if I can replicate it.

**Comment by rbennett24** [comment]
Same issue here, and it may also be related to non-ASCII filenames (e.g. the character û). Each time I run validation I get an error for a different file, but perhaps that's expected.

**Comment by thomasles566** [comment]
> So it says: `sox FAIL formats: can't open input file 'C:\Users\thoma\Documents\MFA\data\allá9.wav': No such file or directory` Is that the correct path to one of the sound files? It's not corrupted or anything, correct? If that's what it should be, then you can try renaming it to ascii only (i.e., sub `a` for `á`), though I do have tests for unicode file names on windows and they are passing, but that could be due to my local set up. I'll see if I can replicate it.

Yes, that is the correct path. I also checked the file and it's not corrupted. I'm going to try a run with files that don't contain any non-ascii characters. I'll let you know what I find.

**Comment by thomasles566** [comment]
> > So it says: `sox FAIL formats: can't open input file 'C:\Users\thoma\Documents\MFA\data\allá9.wav': No such file or directory` Is that the correct path to one of the sound files? It's not corrupted or anything, correct? If that's what it should be, then you can try renaming it to ascii only (i.e., sub `a` for `á`), though I do have tests for unicode file names on windows and they are passing, but that could be due to my local set up. I'll see if I can replicate it.
> 
> Yes, that is the correct path. I also checked the file and it's not corrupted. I'm going to try a run with files that don't contain any non-ascii characters. I'll let you know what I find.

Ok, the alignment with the new file set was successful. I checked the alignments and they look good. The issue I'm facing now is that the full corpus contains around 15,000 files. Since I'm working with Spanish data, many of these files have non-ascii characters in their filenames (á, ó, é, í, and ú). Are there any solutions to this that don't involve renaming all of the files containing non-ascii characters?
