### ISSUE TITLE
Format of the pronunciation dictionnary

### ISSUE THREAD

**Issue by cveaux** [MontrealCorpusTools/Montreal-Forced-Aligner#60]
Hi, it's more a question than an issue. Does MFA make the difference between capital and small letters when it comes to the pronunciation dictionary? Does it have to be all in capital letters?  I have already the phonetic transcription of the text that I want to align and the pronunciation dictionary but this dictionary uses small letter 'a' and capital 'A' to represent different phonemes (and same for some other phonemes).

Thanks

**Comment by mmcauliffe** [comment]
So all orthography gets converted to lower case, all phonetic characters are left as is.  So A and a would get collapsed for words, but if they represent different phones, then they'll be treated as such.

**Comment by cveaux** [comment]
Actually, is there a way to directly input the phonetic transcriptions of each utterance file instead of providing a lexicon? I use festival to generate the phonetic labels and it applies post-lexical rules such as vowel reduction and 'final-r' deletion so a lookup in a pronunciation dictionary won't match these transcriptions.

**Comment by cveaux** [comment]
Yes, one possibility for me is to disable all post-lexical rules inferred by Festival and let these variations be learned by the acoustic modelling since the models are context-dependent. Maybe it was necessary to apply these post-lexical rules at the frontend level for unit-selection speech synthesis but not so much needed anymore.

**Comment by cveaux** [comment]
I'm closing this issue. I have implemented a solution similar to your 3rd suggestion and it works well. Most of the variants induced by the post-lexical rules are for the schwa and the deleted final /r/  (non-rhotic RP English).  Given these are very limited cases maybe it would be better to include them all in the lexicon as pronunciation variants (i.e your solution 1). Some speakers don't have a strictly non-rhotic pronunciation for instance. But my application is TTS and in that case I would also need to learn a language model for each speaker (instead of applying systematically the post-lexical rules for RP English), so I'll leave that for later. 
Thanks for your suggestions anyway.

**Comment by agangzz** [comment]
From the document, the sil phone is used to model silence.
so how to add sil in dictonary and in transcription? Thanks
