### ISSUE TITLE
[BUG] Word Boundaries Spacing Issues

### ISSUE THREAD

**Issue by Denevvv** [MontrealCorpusTools/Montreal-Forced-Aligner#603]
**Debugging checklist**

[x ] Have you updated to latest MFA version?
[x ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
Spaces in audio are not perceived and the phonemes are always connected with spaces 

**For Reproducing your issue**
Please fill out the following: 

1. Corpus structure
   * What language is the corpus in? Irish 
   * How many files/speakers? 168
   * Are you using lab files or TextGrid files for input? lab files
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? N.A
   * If it's a custom dictionary, what is the phoneset? Living Audio 
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? n/a
   * If it's a model you've trained, what data was it trained on? CommonVoice And Living Audio

**Logfile**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

[IrishCombined.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/11070611/IrishCombined.log)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] Windows
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] 11
 - Any other details about the setup (Cloud, Docker, etc) 

**Additional context**
Add any other context
![Screenshot 2023-03-25 212053](https://user-images.githubusercontent.com/128946655/227751756-82359511-8b5b-44ae-a0c3-a34c196c2b48.png)

All the files look like this

**Comment by massimolipari** [comment]
I ran into the same issue, adding the --no_textgrid_cleanup flag seems to have fixed things
