### ISSUE TITLE
Questions about pronunciation dictionaries

### ISSUE THREAD

**Issue by treya-lin** [MontrealCorpusTools/Montreal-Forced-Aligner#607]
Hi I hope this is the right place to post this. 

So, I am using the russian dictionary and turkish dictionary and I noticed that the phone symbols come with diacritics which are often used in strict phonetic transcription like mʲ and  n̪ etc. I am actually very curious about how the MFA pronunciation dictionaries are produced in the first place before using the g2p model to expand the size, like, did you used any other open sourced tool and mapped them to the ipa symbols, or you used the dictionary of other parties as the baseline dictionary? Or did you did linguistic research and phonetize the dictionary in a rule-based manner? Are there any language-specific consideration when you design the phone set or linguistic rules? 

I assume for different languages you guys have used different ways to phonetize it right, because the resource accessibility can be different. I am very curiouis about the procedure how the dictionaries were designed and developed, but I didn't find such information in the info page of your dictionaries, and I look around online and in the issue page and found no discussion on how MFA generate pronunciation dictionaries. 

Actually the dictionaries are very important components, I wish there could be more description in the documents. I think more information for the dictionaries is very important actually for us to understand the model performance in downstreams tasks too. 

Thanks a lot if you could kindly share more info about the mfa dictionaries.

**Comment by mmcauliffe** [comment]
There's a description of the source and cleaning procedures for each language here: https://mfa-models.readthedocs.io/en/latest/mfa_phone_set.html. If you have suggestions for improvement of certain languages, let me know since I'm only an expert in a few of the languages, but I have tried to follow what literature and descriptions I could in transforming the wiktionary pronunciations.

**Comment by treya-lin** [comment]
> There's a description of the source and cleaning procedures for each language here: https://mfa-models.readthedocs.io/en/latest/mfa_phone_set.html. If you have suggestions for improvement of certain languages, let me know since I'm only an expert in a few of the languages, but I have tried to follow what literature and descriptions I could in transforming the wiktionary pronunciations.

Got it! Great thanks!
