### ISSUE TITLE
mfa align ignores every WAV even though mfa validate shows everything is fine [BUG]

### ISSUE THREAD

**Issue by ryamldess** [MontrealCorpusTools/Montreal-Forced-Aligner#613]
**Debugging checklist**

[yes] Have you updated to latest MFA version?
[yes] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
I run `mfa validate` on my test corpus (I pulled a single speaker from LibriTTS train-500). This generates .lab files with an IPA representation of the .txt transcripts of my WAV files. It says everything is great. Then I run` mfa align` on the same corpus with the .lab files. It normalizes text, but accomplishes 0/73; writes the lexicon (1/146); generates the MFCCs (0/73), calculatres cmvn and generates final features (0/73); it then shoots through all 73 files and ignores them before failing alignment. Again, `mfa validate` says the same corpus checks out fine.

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? **English**
   * How many files/speakers? **1**
   * Are you using lab files or TextGrid files for input? **.lab**
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? **english_us_mfa**
   * If it's a custom dictionary, what is the phoneset? **N/A**
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? **english_mfa**
   * If it's a model you've trained, what data was it trained on? **N/A**

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Log file is attached; there does not appear to be a log entry for this event.**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] **Windows**
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] **10**
 - Any other details about the setup (Cloud, Docker, etc) **Miniconda3, latest version (performed a reinstall of Miniconda3 with the latest win64 binary and ran `conda update -n base -c defaults conda`, and then `conda update --all`). Conda env python version is 3.10.10**

**Additional context**

Issuing this command:

`mfa align G:\1_Projects\M\Synthetic-Self\source\hg\blinkpopshift-synthetic-self\data\training_test_data_LibriTTS_speaker_20\MFA english_us_mfa english_mfa G:\1_Projects\M\Synthetic-Self\source\hg\blinkpopshift-synthetic-self\data\training_test_data_LibriTTS_speaker_20\MFA`

Corpus looks like this:

MFA
 ----corpus
 --------20
 ------------audio
 ----------------wav1.wav
 ----------------...
 ------------text
 ----------------wav1.original.lab
 ----------------wav1.original.txt
 ----------------...
                
Text transcripts look like this before attempt to align:

`The younger Miss Thorpes being also dancing, Catherine was left to the mercy of Mrs. Thorpe and Mrs. Allen, between whom she now remained.`

Labs look like this before attempt to align:

`ð j ɐ ŋ ɡ ɚ mʲ ɪ s θ ɒ ɹ p s bʲ iː ɪ ŋ ɒ ɫ s ow d æ n s ɪ ŋ cʰ æ θ ə ɹ ɪ n w ɐ z l ɛ f t tʰ ow ð m ɝ s i ə mʲ ɪ s ɪ z θ ɒ ɹ p æ n d mʲ ɪ s ɪ z æ l ə n bʲ ɪ t w i n h ʉː m ʃ iː n aw ɹ ɪ m ej n d`

[pg_log_global.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/11206772/pg_log_global.txt)

**Comment by mmcauliffe** [comment]
There are a couple of issues with how you've set up your corpus.  The more major one is that sound files and transcripts have to have the same base name, so you should rename your text transcript (I'm assuming it's the `wav1.original.txt`), to `wav1.txt`.  

The second is that MFA expects file pairs to be located in the same location, so I would recommend moving  the new `wav1.txt` files to the audio directory.  If you want to keep them split, you would have have to specify `--audio_directory` (see https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/alignment.html#cmdoption-mfa-align-a).  However, `.lab` files are used as transcripts before `.txt` files, so be sure not to rename the .lab files with phones to `wav1.lab`
