### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lhzwangwei** [MontrealCorpusTools/Montreal-Forced-Aligner#617]
**Debugging checklist**

[ Y] Have you updated to latest MFA version?
[Y ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
The trained model is aligned, but the sil at the beginning and end is not recognized, and is aligned directly to the first word
**For Reproducing your issue**
Please fill out the following:
Since then, I have tried using ({sl} sil) and adding {sl} at the beginning and end of the sentence but it is being identified as [brackets], and I would like to know if I need to manually add {sl} at the beginning and end of the sentence myself. If so, Can I use spk like (spk1 sil) to add at the beginning and end, if I don't need to add manually, what might be the problem?
1. Corpus structure
   * What language is the corpus in? burmese
   * How many files/speakers? 2
   * Are you using lab files or TextGrid files for input? I use like 1.wav and 1.txt 
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? N
   * If it's a custom dictionary, what is the phoneset? b d dʑ ð ɡ h j k kʰ l l̥ m m̥ n n̥ ɲ ɲ̥ ŋ ŋ̊ p pʰ ɹ s sʰ ʃ t tʰ tɕ tɕʰ θ w ʍ ɴ z ʔ a à á a̰ aɪ àɪ áɪ a̰ɪ aʊ àʊ áʊ a̰ʊ e è é ḛ eɪ ɛ ὲ ɛ́ ɛ̰ ə i ì í ḭ ɪ ɪ̀ ɪ́ ɪ̰ ò ó o̰ oʊ òʊ óʊ o̰ʊ ɔ ɔ́ ɔ̀ ɔ̰ ù ú ṵ ʊ ʊ̀ ʊ́ ʊ̰
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? N
   * If it's a model you've trained, what data was it trained on? my data

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux]windows
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]win10
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**

**Comment by lhzwangwei** [comment]
Also, I wrote my own punctuation directly into doc/MFA/global_config.yaml, but after every mfa train run, this line disappears unless I don't --clean. I directly write mfa g2p./ Burmese_corpus_N5_3_addsil_v6. /22.zip./Burmese_no_shugang.txt --punctuation :, each time I run mfa train.
So -- punctuation can work?

**Comment by mmcauliffe** [comment]
Right, punctuation isn't set globally, instead as you note, you have to specify the punctuation on a per run basis via `mfa train ... --punctuation :,` or constructing a configuration yaml and using it via `mfa train --config_path /path/to/burmese.yaml` (see https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/train_acoustic_model.html#cmdoption-mfa-train-c).

The config path would then contain something like:

```
punctuation: ":,"
``` 

You can see an example config file here: https://github.com/MontrealCorpusTools/mfa-models/blob/main/config/acoustic/thai.yaml (this one does no punctuation or clitic marker parsing).
