### ISSUE TITLE
How to Get More Silence?

### ISSUE THREAD

**Issue by Moon-sung-woo** [MontrealCorpusTools/Montreal-Forced-Aligner#630]
Hello, first of all, thank you for making a great MFA.

I trained the MFA model for Korean and checked the results, but there is no silence with all spacing units.

Can we get MFA results including more silence?

What parameters should I modify if I can get it?

Thank you.

**Comment by mmcauliffe** [comment]
You can try playing around with the command line options for `--silence_probability` (I'm not 100% sure if you can affect silence probabilities of trained dictionaries, since there's a lot of per-pronunciation modeling that goes on) and `--boost_silence=1.5` or something greater than 1.0.

**Comment by mmcauliffe** [comment]
Oh and also double check that you're on the latest version, there was a bug recently fixed made it seem like there were no silences with `--cleanup_textgrids`, but `--no_cleanup_textgrids` showed the silence (https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/alignment.html#cmdoption-mfa-align-textgrid_cleanup).

**Comment by Moon-sung-woo** [comment]
Hi! @mmcauliffe .
Thank you for the comments.
I'll try as you told me.
Thank you!
