### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mgs96** [MontrealCorpusTools/Montreal-Forced-Aligner#636]
**Debugging checklist**

[x] Have you updated to latest MFA version?
[x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
Speechbrain is not installed in the docker version of mfa.

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?: English
   * How many files/speakers?: 1 File, 1 Speaker
   * Are you using lab files or TextGrid files for input?: Lab files
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?: No
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? No
   * If it's a model you've trained, what data was it trained on?

 - OS: [Docker, macOS, apple silicon M1]
 - Version [macOS 13.3.1, Docker Engine: 23.0.5]

**Additional context**
When running the following command: `mfa segment --speechbrain --clean corpus output`
I get the following error:
 `Could not import speechbrain, please ensure it is installed via pip install speechbrain`

**Comment by mmcauliffe** [comment]
Did you run `pip install speechbrain`?  That will install it so you can use it.  Speechbrain is not on Conda forge, so it doesn't get installed by default.

**Comment by mgs96** [comment]
I did tried that but still get the same message as before, I'm using the latest version of `mmcauliffe/montreal-forced-aligner:latest`
