### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by cveaux** [MontrealCorpusTools/Montreal-Forced-Aligner#64]
Hi, from my experiments it seems that the MFA is running on only one cpu when there is only one speaker to align. I am running the alignment on the LJSpeech corpus (one speaker, 13100 audio files) and have specified `-j 8 ` in the arguments. However I got num_jobs=1 in the mfcc function in multiprocessing.py (and same for subsequent steps). Do you confirm this behaviour or I am doing something wrong?

p.s.: I am running the MFA with this command:

`python ~/corpustools/montreal_forced_aligner/aligner/command_line/train_and_align.py -s 0 -t ~/MFA  -j 8 --verbose --clean ljspeech word_lexicon.txt mfa_align`

Thanks

**Comment by cveaux** [comment]
pps: Indeed, I just saw in `corpus.py` (in `__init__` and `find_best_groupings`) that the actual number of parallel jobs depends of the number of speakers and different sampling rates. I guess that a way to do multi-processing with a single speaker might be to split the data beforehand into several "speakers" and then stop the training after the trigram alignement.

**Comment by mmcauliffe** [comment]
Yeah, that would be my thought as well.  The original use case is geared towards datasets that have lots of speakers, rather than just one.  In principle, it shouldn't be too hard to assign extra processes to speakers with the most data.  I'll think some more about it.

**Comment by cveaux** [comment]
Hi, just a further question on this multi-processing topic. For now, I am doing multi-processing by splitting the training data into as many sub-directories as available cpus. However since I just have a single speaker and quite a lot of data I am using the train_and_align command but I am stopping it after the trigram alignment. So my question is, in this case, will the MFA learn a single model across all "speakers" (sub-directories) or a just a model for each?  If it's the latter it's obviously not what I want.

Thanks!

**Comment by phtephanx** [comment]
Did you come to a conclusion?

```
I guess that a way to do multi-processing with a single speaker might be to split the data beforehand into several "speakers" and then stop the training after the trigram alignment.
```
Is this the workaround to choose?

**Comment by cveaux** [comment]
Hi, yes, that's what I did, works very well. However I haven't followed latest updates of MFA so maybe the multi-processing for a single speaker has been implemented since.

**Comment by JRMeyer** [comment]
this caught me as well, glad to find this thread!

**Comment by owaski** [comment]
Is single-speaker multi-processing supported now?
