### ISSUE TITLE
Compile Kaldi linked to OpenBLAS rather than ATLAS

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/Montreal-Forced-Aligner#66]
I'm using Arch Linux and unfortunately I'm unable to use the current release for Linux without compiling it myself with alternate Kaldi flags. When initially running the prebuilt release, I get the same ` FileNotFoundError: [Errno 2] No such file or directory: '/Documents/MFA/LibriSpeech/train/mfcc/raw_mfcc.0.scp'` error that exists in issue #44. This is due to not having installed the ATLAS library.

However, Arch doesn't have an official package for ATLAS and so I would have to compile ATLAS myself to use it. This is problematic for me as compiling ATLAS requires disabling CPU throttling.

I was able to fix the issues by using an alternative linear algebra library when I compiled Kaldi as described [here](http://kaldi-asr.org/doc/matrixwrap.html). Specifically I used OpenBLAS.

**Comment by mmcauliffe** [comment]
Ok, the linux build should now use OpenBLAS as well, will also double check that the Mac build does too.
