### ISSUE TITLE
Math domain error.

### ISSUE THREAD

**Issue by nonusg** [MontrealCorpusTools/Montreal-Forced-Aligner#663]
#305 
I'm trying to validate russian corpus, and caught the error.
![IMAGE 2023-07-12 11_48_38.jpg](https://s2.loli.net/2023/07/12/Vrj1iIU5KSHaLcZ.jpg)
![IMAGE 2023-07-12 11_49_53.jpg](https://s2.loli.net/2023/07/12/ifQ85VsrdW2GeIF.jpg)

**Comment by nonusg** [comment]
Solved. It's data's problem.

**Comment by magic-umbrella** [comment]
I know, it's been almost a year, but what was the issue with the data? I'm also trying to validate/allign a russian corpus, it works with russian_cv dictionary and model, but i get this error with russian_mfa.

**Comment by mmcauliffe** [comment]
I'm currently in the process of correcting some data issues with the Russian training corpora and retraining a model, so once that's released, your issues should be resolved.
