### ISSUE TITLE
The default behavior of mfa align

### ISSUE THREAD

**Issue by huangruizhe** [MontrealCorpusTools/Montreal-Forced-Aligner#680]
Hello! Just wondered if I use this command to obtain alignment, what's the default behavior? Say, will the speaker adaptation or fine-tuning (fine-tune the pretrained model on the target data) happen?

`mfa align --overwrite --clean --single_speaker ${data} english_mfa english_mfa ${data}/alignment`

Just realized that `--single_speaker` is not related to speaker adaptation at all, while on the other hand the speaker adaptation option `--uses_speaker_adaptation false` is just [fixed recently](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/482). BTW, this option is not mentioned in the [doc](https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/alignment.html#align-with-an-acoustic-model-mfa-align). So I hope to double check.

**Comment by mmcauliffe** [comment]
As of 3.0.0a5, `--single_speaker` will imply `--uses_speaker_adaptation false`, since speaker adaptation doesn't add anything in this case. I've updated the docs to reflect this as well.
