### ISSUE TITLE
[BUG] Can't run mfa after installation: syntax error in multiprocessing.py

### ISSUE THREAD

**Issue by dreamk73** [MontrealCorpusTools/Montreal-Forced-Aligner#698]
**Debugging checklist**

[ X] Have you updated to latest MFA version?
[ ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

I just installed the montreal forced aligner using the conda command in the readme.md file. I have python 3.8 installed and numpy 1.24.4 in a clean conda environment. Whatever I try to do, I just get a syntax error in multiprocessing.py:

  File "~/miniconda3/envs/py38-fairseq/bin/mfa", line 6, in <module>
    from montreal_forced_aligner.command_line.mfa import mfa_cli
  File "~/miniconda3/envs/py38-fairseq/lib/python3.8/site-packages/montreal_forced_aligner/__init__.py", line 4, in <module>
    import montreal_forced_aligner.acoustic_modeling as acoustic_modeling
  File "~/miniconda3/envs/py38-fairseq/lib/python3.8/site-packages/montreal_forced_aligner/acoustic_modeling/__init__.py", line 7, in <module>
    from montreal_forced_aligner.acoustic_modeling.base import AcousticModelTrainingMixin  # noqa
  File "~/miniconda3/envs/py38-fairseq/lib/python3.8/site-packages/montreal_forced_aligner/acoustic_modeling/base.py", line 21, in <module>
    from montreal_forced_aligner.alignment import AlignMixin
  File "~/miniconda3/envs/py38-fairseq/lib/python3.8/site-packages/montreal_forced_aligner/alignment/__init__.py", line 6, in <module>
    from montreal_forced_aligner.alignment.adapting import AdaptingAligner
  File "~/miniconda3/envs/py38-fairseq/lib/python3.8/site-packages/montreal_forced_aligner/alignment/adapting.py", line 19, in <module>
    from montreal_forced_aligner.alignment.multiprocessing import AccStatsArguments, AccStatsFunction
  File "~/miniconda3/envs/py38-fairseq/lib/python3.8/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 407
    self.session() as session,
                   ^

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
   * How many files/speakers?
   * Are you using lab files or TextGrid files for input?
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux]
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**

**Comment by scutcsq** [comment]
I got the same problem when I tried the command from  https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/index.html#first-steps "mfa model download acoustic english_us_arpa", and I still do not know how to solve it.

**Comment by mmcauliffe** [comment]
That is very odd, that line definitely doesn't have a syntax error that should be thrown on any recent version of python and all the conda forge builds have been fine.  The line in question: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/montreal_forced_aligner/alignment/multiprocessing.py#L407 shouldn't have an issue with python 3.8. Can you try creating a new environment and installing there?  Alternatively, you can try using python 3.11, but I don't think there's anything new in recent version of python that would affect those lines.

**Comment by dreamk73** [comment]
A new environment with python 3.11 works. I am currently trying a new environment with 3.8 and it has been trying to solve the environment for the past few hours and appears to be stuck.

**Comment by evdv** [comment]
The offending lines are 403-406 (https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/16292fa012a2f735db47ba4b8d2705303a94085a/montreal_forced_aligner/alignment/multiprocessing.py#L403)
Python version 3.8 does not support parenthesized context expressions. To be Python 3.8 compliant, the context statement would need to look as follows:

`with self.session() as session, thread_logger("kalpy.graphs", self.log_path, job_name=self.job_name) as graph_logger:`

For which the whitespace would need to reorganised as well.

**Comment by abhijeet1275** [comment]
> I got the same problem when I tried the command from https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/index.html#first-steps "mfa model download acoustic english_us_arpa", and I still do not know how to solve it.

Hey! Have you found the solution to it?
