### ISSUE TITLE
wav files with 8k, not restarting, 0 division...

### ISSUE THREAD

**Issue by rafaelvalle** [MontrealCorpusTools/Montreal-Forced-Aligner#7]
Hi all! Thanks for putting this together.

First I had problems when trying to align wav files that were 8k (ZeroDivisionError) then after converting the files the aligner was still stuck in the ZeroDivisionError. To fix it, I had to remove the TEMP file for the dataset I was using. 

Can you please investigate this?

**Comment by mmcauliffe** [comment]
Thanks for letting me know, as mentioned on http://montreal-forced-aligner.readthedocs.io/en/stable/sound_files.html#sampling-rate, we currently only support sampling rates of 16k or higher.  I haven't done any testing on files lower than that, so they might work, they might not.

There is a command-line option to clear up any temporary files using `--clean`.  Do you know if the dataset changed at all between the runs or if you used the same name as a previously aligned dataset?  We do caching on preparation to speed up subsequent runs (and allow for pausing alignment), but it's not a very sophisticated system at the moment and can't detect when the source dataset has changed.

**Comment by rafaelvalle** [comment]
Hey Michael. It would be very useful if MFA failed "gracefully" and covered cases such as
missing .lab files, not supported wav files...

I did not run the `--clean` and did upsample the wav files to fit the specs, keeping the same folder and file name structure. I do not remember if I performed other modifications.

**Comment by mmcauliffe** [comment]
Ok, I've added some explicit warnings and logging to when files are ignored.  I've also updated the documentation to make it clearer why 8k sampling rate files are not currently supported.  Thanks again!
