### ISSUE TITLE
[BUG] --clean flag deletes pretrained_model

### ISSUE THREAD

**Issue by danielanphd** [MontrealCorpusTools/Montreal-Forced-Aligner#704]
**Debugging checklist**

[ ] Have you updated to latest MFA version? yes
[ ] Have you tried rerunning the command with the `--clean` flag? yes

**Describe the issue**

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? Korean
   * How many files/speakers? 1
   * Are you using lab files or TextGrid files for input? No.
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? korean_mfa
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? korean_mfa
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] Linux (Ubuntu)
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**

When I run mfa align with --clean flag, it deletes the acoustic and dictionary model, and the aligner does not work. I have to download the acoustic and dictionary models.

**Comment by danielanphd** [comment]
I was on the alpha version. I downgraded to the 2.2.17 version and this problem disappeared.

**Comment by mmcauliffe** [comment]
So I can fix this in 3.0, what was the exact command you were running?

**Comment by danielanphd** [comment]
I did:
mfa align --clean . korean_mfa korean_mfa .
Almost everything in the Documents/MFA folder got deleted with the --clean and it threw an error of "dictionary not found". So I had to download the dictionary and acoustics again.

**Comment by danielanphd** [comment]
I found the problem. If I do
mfa align --clean . korean_mfa korean_mfa .
Almost everything in the Documents/MFA folder got deleted as I wrote above. However, if I write the directory name in the first ., like
mfa align --clean /home/user/wav_txt_directory korean_mfa korean_mfa .
then the problem does not happen.
