### ISSUE TITLE
Convert existing mdl model into alimdl model instead of trainning

### ISSUE THREAD

**Issue by wei2222** [MontrealCorpusTools/Montreal-Forced-Aligner#718]
Debugging checklist

[Yes] Have you updated to latest MFA version?
[Yes] Have you tried rerunning the command with the --clean flag?

Describe the issue:
mfa validate/align does not support old mfa model

Hi, is there any possible way to convert an old version model into a new one? Thanks.

**Comment by wei2222** [comment]
@mmcauliffe Do you have any idea? Could anyone help or explain this?

**Comment by Jon-Zbw** [comment]
请问您解决了吗？我也是报错assert self.alignment_model_path.suffix == ".alimdl" @wei2222

**Comment by wei2222** [comment]
没有解决 把这行去掉l可以运行 但不知道有没有其他问题

**Comment by Jon-Zbw** [comment]
@wei2222 
我是重新装的2.2.4版本可以运行，您说的去掉这行什么意思？修改源码？
