### ISSUE TITLE
[BUG] upgrade issue with conda on Ubuntu

### ISSUE THREAD

**Issue by jah238** [MontrealCorpusTools/Montreal-Forced-Aligner#737]
**Debugging checklist**

[ x ] Have you updated to latest MFA version?
[ x ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
Failed attempt to upgrading earlier MFA conda installation to latest version.

**For Reproducing your issue**
Please fill out the following:

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-155-generic x86_64)
 
root@llt-iscan-prd1: /home/# conda create -n aligner -c conda-forge montreal-forced-aligner
Retrieving notices: ...working... done
WARNING: A conda environment already exists at '/opt/miniconda3/envs/aligner'
Remove existing environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): - Killed

**Comment by mmcauliffe** [comment]
You can try using mamba as the solver instead: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#general-installation it generally has better performance, but this could also have just been a transient error due to OpenFst 1.8.3 dependency issues.
