### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YjmLj** [MontrealCorpusTools/Montreal-Forced-Aligner#739]
I was training a new acoustic model with MFA 2.0.6

[command]
mfa train $my_corpus_path english_us_mfa $align_json_dir --num_jobs 20 --clean --output_format=json --temporary_directory=$temp_dir

Describe the issue
After Finished exporting TextGrids to $align_json_dir, i got error: 
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7f228bc951e0>>
montreal_forced_aligner/command_line/mfa.py", line 101, in history_save_handler
update_command_history(history_data)
montreal_forced_aligner/config.py", line 114, in update_command_history
history = load_command_history()
montreal_forced_aligner/config.py", line 95, in load_command_history
for h in history:
TypeError: 'NoneType' object is not iterable 
Desktop (please complete the following information):

Linux: Ubuntu
Version 20.04.6
install and run MFA on private environment of conda

**Comment by mmcauliffe** [comment]
This shouldn't affect anything in the run or anything, it's just an error on exit.  It's been fixed in versions since 2.0.6.
