### ISSUE TITLE
FileNotFoundError: No 0.occs file

### ISSUE THREAD

**Issue by Jackiexiao** [MontrealCorpusTools/Montreal-Forced-Aligner#74]
```
FileNotFoundError [Error 2] No such file or directory:
'/home/jackie/Documents/MFA/thsst/tri/0.occs' 
-> '/home/jackie/Documents/MFA/thsst/tri.1.occs'
```

**Comment by Jackiexiao** [comment]
It looks like I have to set lexicon to `liang3 l iang3`(word phone1 phone2) instead of `liang3 liang3`

**Comment by maogewudi007** [comment]
hello, I met the same question like you. Are you align the song "liang liang" by Bichen Zhang?  I want to align the song "shi nian" by Yixun Chen. Can you show me the .lab and .txt ? Thanks a lot!!!

**Comment by Jackiexiao** [comment]
the lab file is like
```
lv4 shi4 yang2 chun1 yan1 jing3 da4 kuai4 wen2 zhang1 de5 di3 se4 si4 yue4 de5 lin2 luan2 geng4 shi4 lv4 de2 xian1 huo2 xiu4 mei4 shi1 yi4 ang4 ran2
```
You just need to set your lexicon like https://github.com/Jackiexiao/MTTS/blob/master/misc/mandarin-for-montreal-forced-aligner-pre-trained-model.lexicon
