### ISSUE TITLE
[BUG] TypeError: __init__() got an unexpected keyword argument 'two_models'

### ISSUE THREAD

**Issue by hantien2002** [MontrealCorpusTools/Montreal-Forced-Aligner#742]
Hi, here are all the command line I have run:
conda create -n mfa-test python=3.8 --yes
conda activate mfa-test
conda install -c conda-forge montreal-forced-aligner
mfa model download acoustic english_us_arpa
mfa model download dictionary english_us_arpa

then I run:
mfa validate ~/mfa_data/my_corpus english_us_arpa english_us_arpa
it passed.

then I run:
mfa align ~/mfa_data/my_corpus english_us_arpa english_us_arpa ~/mfa_data/my_corpus_aligned
it gave me the error.

<img width="1510" alt="error1" src="https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/assets/90298039/9099148c-cd57-417d-94e7-0605ccc1bcbb">
<img width="1509" alt="error2" src="https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/assets/90298039/47ff1317-b5dd-46e1-9c86-09bdfe8918c1">

**Comment by gadese** [comment]
@mmcauliffe 

This isn't a MFA issue. [Version 0.6.0 of Kalpy](https://github.com/mmcauliffe/kalpy/pull/12/files) changed the function signature for the arguments of FmllrComputer but MFA wasn't updated accordingly.

@hantien2002 Until MFA is updated, you can set the kalpy version to 0.5.9 in your conda env to ignore this issue.

**Comment by hantien2002** [comment]
@gadese Thank you so much! It works perfect now!

**Comment by HildaNya** [comment]
Follow up question: by setting kalpy to  0.5.9, do you mean removing the latest kalpy?

**Comment by hantien2002** [comment]
I just did "conda install kalpy=0.5.9", and it works for me.

So after this, "conda list kalpy" should return something like:
kalpy                     0.5.9
