### ISSUE TITLE
[BUG] Cutoffs aligned as spn rather than generating pronunciations for cutoff words

### ISSUE THREAD

**Issue by praat-enthusiast** [MontrealCorpusTools/Montreal-Forced-Aligner#755]
**Debugging checklist**

[X] Have you updated to latest MFA version?
[X ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
I'm trying to align cutoffs using --use_cutoff_model, but rather than generating pronunciations for the cutoffs, the end result has all the cutoffs aligned as spn. I've tried to follow the guidance given [here](https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/dictionary.html#modeling-cutoffs-and-hesitations), but am not sure if I might be misinterpreting how to transcribe cutoffs in the data - for clarity an example of what I'm doing is: (li-_like)

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? English
   * How many files/speakers? One file, two speakers.
   * Are you using lab files or TextGrid files for input? TextGrids
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? english_uk_mfa
   * If it's a custom dictionary, what is the phoneset? n/a
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? english_mfa
   * If it's a model you've trained, what data was it trained on? n/a

**Log file**
[input_v3.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/14360951/input_v3.log)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
I've tried this on both MFA 2.2.17 and v3. I usually use 2.2.17 but updated to v3 for the purposes of the bug report. As a strange extra problem, when running this on v3, it generates a TextGrid that Praat can't read - see screenshot of error. I've inspected the TextGrid in Notepad++, however, and as far as I can tell there is absolutely nothing wrong with Line 1116. 
![praat error](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/assets/42466235/05a30a87-b85b-4481-bed4-0e6b6efe5e40)

**Comment by mmcauliffe** [comment]
You need the word "cutoff" as the first part for MFA to parse it as such so `(CUTOFF-like)` or just `<CUTOFF>`, though the way that it works currently is that it doesn't use any text following the word cutoff, the CUTOFF model is simply based on the following word, which may be less than ideal for your case.  I can probably update it to split based on '-' and look up based on that (so `<CUTOFF-like>` would base its pronunciations on `like`), but cutoff annotations are not very consistently annotated in corpora.

The TextGrid issue should be fixed as of 3.0.0rc2.

**Comment by praat-enthusiast** [comment]
Thanks, that's really helpful and good to know!
