### ISSUE TITLE
[Question] What is the purpose of --single_speaker flag for mfa train? and the relation with the --speaker_characters?

### ISSUE THREAD

**Issue by Jxu-Thu** [MontrealCorpusTools/Montreal-Forced-Aligner#762]
Hi, 
  Thanks for your great tools.
  I have a group of audios and transcrips. Without --single_speaker, I have to organize the audios in the following format for multiprocessing.
  /speaker1
    aaa.wav
    aaa.lab
    bbb.wav
 /speaker2
     ...

  However,  the splits is biased. Some speakers have many audios while some only have one audio, for example. Thus, I want to conduct MFA train for aligning based on random and evenly split. 
  I find that --single_speaker seems to be for this purpose. Could you provide more explanations for this flag? When I set  --single_speaker, the --speaker_characters should be invalid. right?

**Comment by mmcauliffe** [comment]
No it's better to have files properly assigned to their speakers, as the feature space transforms for speakers will be much better.  Speakers with single utterances won't benefit as much from the speaker adaptation, but that's not really a reason to make speaker adaptation worse for other speakers.  Balance per speaker doesn't matter as much as accurate speaker metadata.  

`--single_speaker` is for cases of TTS training where they have tens of thousands of files of just one speaker but still need to split across multiple jobs, as typical use for MFA has a given speaker assigned to a single job for processing.

**Comment by mmcauliffe** [comment]
Oh, and in regards to `--speaker_characters`, if you have speakers already set up via different directories, you don't need worry about `--speaker_characters`, that's only an option in case you have all speakers' files in single flat directory.

See https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/corpus_structure.html for more details about the supported formats and options.  I'll try to add a section to it as well that details the effects and use cases of the various flags.

**Comment by Jxu-Thu** [comment]
Thanks for your quick response!  My concerns have been solved.
