### ISSUE TITLE
Third party error with MFA; was working fine before

### ISSUE THREAD

**Issue by mchaturv24** [MontrealCorpusTools/Montreal-Forced-Aligner#765]
Hi, 
I'm failing to run any MFA commands and get the following error:

Could not find 'sox'. Please ensure that you have installed MFA conda dependencies and are in the correct environment.

Would be grateful for any help, thank you so much!

**Comment by mmcauliffe** [comment]
If you're in the correct environment, can you run `sox --help` and get output? You can try reinstalling sox in particular via `conda install -c conda-forge sox`, but it's likely either something got messed up in the environment or it's not actually activated.  You can recreate the environment via `conda create -c conda-forge -n aligner montreal-forced-aligner` to ensure the environment is properly set up.
