### ISSUE TITLE
some question about AlignConfig() default setting

### ISSUE THREAD

**Issue by agangzz** [MontrealCorpusTools/Montreal-Forced-Aligner#77]
AlignConfig(): beam(200.0), retry_beam(0.0), careful(false)

accoding decoder-wrappers.h in kaldi, there are three parameters for configuration. In montreal-forced-aligner, the beam is 10, retry_beam is 40 default, but cann't find "careful" parameter.

so how to setting "careful" parameter to "true" in montreal-forced-aligner?

Thanks

**Comment by mmcauliffe** [comment]
So a couple of things. In general all of the recipes in kaldi set careful
to false, I haven't seen an instance of true used. Additionally, none of
the alignment executables (or any executable) uses the option. It seems
like it probably got deprecated and removed, but some aspects haven't been
updated for it yet.

So MFA doesn't specify careful because it doesn't change anything about how
it's run.

**Comment by agangzz** [comment]
@mmcauliffe thanks for your apromt reply.

From my evaluation I found that MFA sometimes align sucessefully when the audio and text doen't match. 

In my situation , I have thousands of audio& text pairs,  and some pairs are mismatching. So, I want to find out the mismatching pairs of audio&text using MFA, which parameter of MFA should be revised? What about your suggestion? 

Thanks.

**Comment by mmcauliffe** [comment]
In general, MFA is on the more conservative side of things when it comes to alignment quality, so if there's a deviation between the transcript and the audio, alignment shouldn't be outputted.  In the next release, I'm planning on having the user be able to specify this better, as well expand the (very alpha) functionality currently in the aligner for looking for mismatches in transcripts and audio specifically.

If you'd be willing to share the files that got aligned despite the mismatching, that would be great for me to try and see what exactly happened there.  You can email them to me at michael.e.mcauliffe@gmail.com.
