### ISSUE TITLE
ERROR: FstPrinter: Integer -1 is not mapped to any textual symbol, symbol table =

### ISSUE THREAD

**Issue by SaurabhKNath** [MontrealCorpusTools/Montreal-Forced-Aligner#778]
**Describe the issue**
When I run mfa align /Users/saurabhkumarnath/Desktop/dictionary/input /Users/saurabhkumarnath/Desktop/dictionary/dictionary.txt english_mfa /Users/saurabhkumarnath/Desktop/dictionary/output, I get the error. Please see the attachment. [base.pdf](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/14610592/base.pdf)

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? Assamese
   * How many files/speakers? 1 file
   * Are you using lab files or TextGrid files for input? TextGrid
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? No, I have created one.
   * If it's a custom dictionary, what is the phoneset? As I'm using mfa_english acoustic model, my phoneset includes symbols from English MFA dictionary v3.0.0
   * If you're using an acoustic model, is it one download through MFA? If so, which one? yes, mfa model download acoustic english_mfa
   * If it's a model you've trained, what data was it trained on? No

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`). PFA
[input.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/14610539/input.log)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] MacBook Air M1 chip
 
Any suggestions? Thanks a lot.

**Comment by Nanayeb34** [comment]
I am facing the same issue. will be watching this for any updates

**Comment by ariadnasc** [comment]
I am also facing the same issue. I will wait for updates!
