### ISSUE TITLE
Alignment slows down significantly during textgrid export

### ISSUE THREAD

**Issue by Barham-K** [MontrealCorpusTools/Montreal-Forced-Aligner#786]
**Debugging checklist**

[ ] Have you read the troubleshooting page (https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/troubleshooting.html) and searched the documentation to ensure that your issue is not addressed there? yes
[ ] Have you updated to latest MFA version (check https://montreal-forced-aligner.readthedocs.io/en/latest/changelog/changelog_3.0.html)? What is the output of `mfa version`? 3.0.3
[ ] Have you tried rerunning the command with the `--clean` flag? yes

**Describe the issue**
When running mfa train on a corpus, the process slows down to a halt in the "Exporting alignment TextGrid to <output_path> phase"

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? English
   * How many files/speakers? 104,000 files, 1000 speakers 
   * Are you using lab files or TextGrid files for input? lab files
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? no
   * If it's a custom dictionary, what is the phoneset? IPA
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? no
   * If it's a model you've trained, what data was it trained on? Librispeach English 360, LjSpeech, and others

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: Windows
 - Version:11
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**

**Comment by dan-ya** [comment]
@Barham-K, the problem should be solved in 3.1.0, see the discussion of #807 issue.
