### ISSUE TITLE
Spellcheck only option?

### ISSUE THREAD

**Issue by JoeyStanley** [MontrealCorpusTools/Montreal-Forced-Aligner#80]
I've got some conversations that I've manually transcribed and, as expected, they're full of typos and out-of-dictionary words. When I run the aligner, it looks like it sets up the training data, calculates the MFCCs, and calculates the CMVNs before checking whether all the words are in the dictionary. It would save a bit of time if a flag could be added to the command that would skip the setup and just do the spellcheck. Does something like that already exist? Thanks.

**Comment by mmcauliffe** [comment]
For the next version, there's a standalone executable for validating and testing the dataset.  It does include MFCC generation (as well as doing some very basic alignment for error checking before committing to any more intensive training), but I'll make a note to have a flag for skipping the computationally intensive part to address this.

**Comment by JoeyStanley** [comment]
Awesome. Thank you!

**Comment by JoeyStanley** [comment]
On a related note, it would be nice to have the utterance_oovs.txt file sorted as integers, rather than by strings. Thus, in the file I'm working on now, the sort is 1513, 154, 24, 268:

47-Sean_47-Sean_1_1513_8815_1518_0704 omsi
47-Sean_47-Sean_1_154_8134_156_0087 homebase
47-Sean_47-Sean_1_24_4663_31_0327 wachob
47-Sean_47-Sean_1_268_0651_274_6553 interships

Since Praat doesn't loop around when searching for words, I find myself scrolling to the beginning a lot. It would be nice if this were resorted as 24, 145, 268, 1513:

47-Sean_47-Sean_1_24_4663_31_0327 wachob
47-Sean_47-Sean_1_154_8134_156_0087 homebase
47-Sean_47-Sean_1_268_0651_274_6553 interships
47-Sean_47-Sean_1_1513_8815_1518_0704 OEMs

Is there any way that could be implemented in the next version as well?

**Comment by mmcauliffe** [comment]
Now possible through `validate_dataset` executable with the  `--ignore_acoustics` flag.
