### ISSUE TITLE
Pytest cache checked in

### ISSUE THREAD

**Issue by pganssle** [MontrealCorpusTools/Montreal-Forced-Aligner#83]
Seems that someone checked in their `.pytest_cache` some time ago. Probably a good idea to delete that. Some time ago `pytest` changed from using [`.cache`](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/master/.gitignore#L54) to using `.pytest_cache`, so might want to add that to the `.gitignore` as well.

**Comment by mmcauliffe** [comment]
Yes, I noticed that too, it's added to the gitignore on another branch that should get merged in soon. Thanks!
