### ISSUE TITLE
[BUG] Dependency issues (?) with installation

### ISSUE THREAD

**Issue by Kedersha** [MontrealCorpusTools/Montreal-Forced-Aligner#838]
**Debugging checklist**

[X] Have you read the troubleshooting page (https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/troubleshooting.html) and searched the documentation to ensure that your issue is not addressed there? Not there.
[X] Have you updated to latest MFA version (check https://montreal-forced-aligner.readthedocs.io/en/latest/changelog/changelog_3.0.html)? What is the output of `mfa version`? **zsh command not found: mfa**
[X] Have you tried rerunning the command with the `--clean` flag? N/A

**Describe the issue**
I'm trying to help 3 RA's install the aligner on their machines. (Demoing issue from just one Mac, but we got the same errors on the second Mac and the Windows machine as well.) We've got Conda on all 3 now, and have been following the Getting Started instructions for a conda install. We tried mamba too, but didn't have any luck there either. Here's the console output:

```conda config --add channels conda-forge
(success)
conda install montreal-forced-aligner
Retrieving notices: ...working... done
Channels:
- conda-forge
- defaults
- conda-forge/label/python_rc
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: - warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package montreal-forced-aligner-2.2.10-pyhd8ed1ab_0 requires biopython 1.79.*, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ montreal-forced-aligner is installable with the potential options
│  ├─ montreal-forced-aligner [2.0.0|2.0.0rc3|...|2.2.4] would require
│  │  └─ python >=3.10,<3.11.0a0 *_cpython, which can be installed;
│  ├─ montreal-forced-aligner [2.0.0|2.0.0b11|...|2.2.4] would require
│  │  └─ python >=3.8,<3.9.0a0 *_cpython, which can be installed;
│  ├─ montreal-forced-aligner [2.0.0|2.0.0b11|...|2.2.4] would require
│  │  └─ python >=3.9,<3.10.0a0 *_cpython, which can be installed;
│  ├─ montreal-forced-aligner [2.2.10|2.2.11|...|2.2.9] would require
│  │  └─ biopython 1.79.* with the potential options
│  │     ├─ biopython 1.79 would require
│  │     │  └─ python >=3.10,<3.11.0a0 *_cpython, which can be installed;
│  │     ├─ biopython 1.79 would require
│  │     │  └─ python >=3.11,<3.12.0a0 *_cpython, which can be installed;
│  │     ├─ biopython 1.79 would require
│  │     │  └─ python >=3.8,<3.9.0a0 *_cpython, which can be installed;
│  │     ├─ biopython 1.79 would require
│  │     │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  │     ├─ biopython 1.79 would require
│  │     │  └─ python >=3.9,<3.10.0a0 *_cpython, which can be installed;
│  │     └─ biopython 1.79 would require
│  │        └─ python >=3.9,<3.10.0a0 , which can be installed;
│  └─ montreal-forced-aligner [2.2.15|2.2.17|...|3.2.0] would require
│     └─ scikit-learn <1.3 with the potential options
│        ├─ scikit-learn [0.23.2|0.24.0|...|1.2.2] would require
│        │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│        ├─ scikit-learn [0.23.2|0.24.0|...|1.2.2] would require
│        │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│        ├─ scikit-learn [1.0.1|1.0.2|...|1.2.2] would require
│        │  └─ python >=3.10,<3.11.0a0 *_cpython, which can be installed;
│        ├─ scikit-learn [1.0.1|1.0.2|...|1.2.2] would require
│        │  └─ python >=3.8,<3.9.0a0 *_cpython, which can be installed;
│        ├─ scikit-learn [1.0.1|1.0.2|...|1.2.2] would require
│        │  └─ python >=3.9,<3.10.0a0 *_cpython, which can be installed;
│        ├─ scikit-learn [1.1.3|1.2.0|1.2.1|1.2.2] would require
│        │  └─ python >=3.11,<3.12.0a0 *_cpython, which can be installed;
│        ├─ scikit-learn [1.0.2|1.1.1|...|1.2.2] would require
│        │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│        └─ scikit-learn [1.1.3|1.2.1|1.2.2] would require
│           └─ python >=3.11,<3.12.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.
```

Running `python --version`, we're on 3.12.3. Following instructions elsewhere, we downgraded to Python 3.11 and tried to install the MFA again, but this time it spun on "Solving environment" until it ran out of memory and aborted.

Would you be able to shed some light on these dependency issues? We'll keep trying things as we think of them, but have been hitting dead ends, and I thought you might want to know if there are issues that could alter the installation workflow. Thanks for your time!

**For Reproducing your issue**
N/A, haven't gotten to the point of having a corpus.

**Log file**
None created so far.

**Desktop (please complete the following information):**
 - OS: OSX
 - Version: Sonoma 14.5
 - Any other details about the setup (Cloud, Docker, etc): MacBook Air with M2 chip trying to install from conda / mamba

**Comment by indiejoseph** [comment]
+1

**Comment by Kedersha** [comment]
Ran into this issue on a different computer (running Win11) and downgrading to python 3.11 eventually did sort things out at least for now, for that machine. Commands:
`conda install python 3.11`
`conda create -n aligner -c conda-forge montreal-forced-aligner`
(then success!)

The Mac that this issue was originally about never ended up succeeding.

**Comment by mmcauliffe** [comment]
Removed the pin on scikit-learn<1.3 since other dependencies have since been updated to support later versions of it, should be fixed now.
