### ISSUE TITLE
[BUG] Transition model update: Overall {objf_impr / count} ZeroDivisionError

### ISSUE THREAD

**Issue by freemedom** [MontrealCorpusTools/Montreal-Forced-Aligner#839]
**Debugging checklist**

[x] Have you read the troubleshooting page (https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/troubleshooting.html) and searched the documentation to ensure that your issue is not addressed there?
[x] Have you updated to latest MFA version (check https://montreal-forced-aligner.readthedocs.io/en/latest/changelog/changelog_3.0.html)? What is the output of `mfa version`?
3.2.0
[x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
  File "C:\Users\xxx\.conda\envs\aligner\Lib\site-packages\montreal_forced_aligner\acoustic_modeling\base.py", line 321, in acc_stats
    f"Transition model update: Overall {objf_impr / count} "
                                        ~~~~~~~~~~^~~~~~~
ZeroDivisionError: float division by zero

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? mfa validate ...\alignSound english_us_arpa english_us_arpa
   * How many files/speakers? 1 mp3 and 1 txt
   * Are you using lab files or TextGrid files for input? i'm not sure.
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? english_us_arpa
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? english_us_arpa
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Windows 10
 - Any other details about the setup: conda

**Additional context**
Add any other context about the problem here.

**Comment by freemedom** [comment]
i just want to align some english mp3 and txt. i don't know much about these technical terms.

**Comment by freemedom** [comment]
https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/746

**Comment by freemedom** [comment]
i'm not sure what happened. i think i don't need to train, i just need english pretrained model.

**Comment by freemedom** [comment]
i find that `mfa align <mp3 and txt> english_us_arpa english_us_arpa <output textgrid> --clean --beam 100 --retry_beam 400` is ok. it just can't run `mfa validate`

**Comment by mmcauliffe** [comment]
If you're looking to use `mfa validate` using an acoustic model, you need to specify it via `--acoustic_model_path`: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/data_validation.html#mfa-validate, but it seems like you have the aligned outputs working.
