### ISSUE TITLE
some question about next MFA release version

### ISSUE THREAD

**Issue by agangzz** [MontrealCorpusTools/Montreal-Forced-Aligner#85]
some question about next MFA release version
1. what are the new features in the next MFA release version?
2. according the latest document of MFA, MFA support nnet2. 
So do MFA support GPU for accelerating training, especially for nnet2 training?
3. Will next MFA version become more flexible, such as open more configuration parameters, display alignment failure reason, support alignment more longer audio/text.
4. when do next MFA version release?

Thanks

**Comment by mmcauliffe** [comment]
There's a high level overview of the implemented changes here: https://montreal-forced-aligner.readthedocs.io/en/latest/whats_new_1.1.html.

GPU support is not enabled at the moment.

I'm planning on releasing a beta testing version for 1.1 potentially this week, now that everything feels more stable (some known issues notwithstanding).

**Comment by agangzz** [comment]
Looking forward the new release

**Comment by mmcauliffe** [comment]
Beta release up now!
