### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/wav/train/mfcc/raw_mfcc.0.scp'

### ISSUE THREAD

**Issue by chenbblei** [MontrealCorpusTools/Montreal-Forced-Aligner#91]
I got the errors below,pelease help me to solve it
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 146, in validate_args
  File "aligner/command_line/align.py", line 93, in align_corpus
  File "aligner/aligner/pretrained.py", line 71, in __init__
  File "aligner/aligner/pretrained.py", line 117, in setup
  File "aligner/aligner/base.py", line 80, in setup
  File "aligner/corpus.py", line 970, in initialize_corpus
  File "aligner/corpus.py", line 848, in create_mfccs
  File "aligner/corpus.py", line 859, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/wav/train/mfcc/raw_mfcc.0.scp'
Failed to execute script align

**Comment by shartoo** [comment]
i got an error same as you.

```
No such file or directory: '/home/top/Documents/MFA/wav/corpus_data/split1/feats.0.scp'
```

**Comment by mmcauliffe** [comment]
Hi both, could you please let me know what system this is running on, as well as any errors in `~/Documents/MFA/DATASET_NAME/corpus_data/splitX/make_mfcc.0.log`.  @chenbblei it looks like you're running version 1.0 and @shartoo running version 1.1 beta, is that right?

**Comment by shartoo** [comment]
@mmcauliffe yes,exractly！

**Comment by agangzz** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/data1/MFATMP/B17B4EBE56E267927823E331D29E6E0C/train/mfcc/raw_mfcc.0.scp'

**Comment by sirifarif** [comment]
I think inside the ```tempDir/<corpus_name>/corpus_data``` directory, the __feats.scp__ and __cmvn.scp__ files are missing. The __feats.scp__ file is created but its empty.

After a little debugging, I found out that,  in the [corpus.py](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/master/aligner/corpus.py) file, these two files (__feats.scp__, __cmvn.scp__ ) are never written.

I created a [branch](https://github.com/sirifarif/Montreal-Forced-Aligner/tree/fixingBug) to fix the issue but its not complete.

**Comment by sirifarif** [comment]
@Jackiexiao Did you compile it from source?

**Comment by johndouglascm** [comment]
>  might fix the issue

It does!  I need a minor adjustment to the sym link path - precisely:

` (cd montreal-forced-aligner/lib/thirdparty/bin && rm libopenblas.so.0  && ln -s ../../libopenblasp-r0-8dca6697.3.0.dev.so libopenblas.so.0)`

**Comment by shartoo** [comment]
@johndouglascm  Thank you,it really work.

**Comment by mmcauliffe** [comment]
Ok, this should now be fixed in Beta 2 (https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases/tag/v1.1.0-beta.2)

**Comment by Olabiyisam** [comment]
Hello I am having this Error, any help from anyone FileNotFoundError: [Errno 2] No such file or directory: 'MFA/audio_file/corpus_data/split3/utterance_lengths.0.scp.

**Comment by taichuai** [comment]
It work for me by:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/anaconda3/envs/aligner/lib/ `

**Comment by ZhaoJiangJie** [comment]
> > might fix the issue
> 
> It does! I needed a minor adjustment to the sym link path - precisely:
> 
> ` (cd montreal-forced-aligner/lib/thirdparty/bin && rm libopenblas.so.0 && ln -s ../../libopenblasp-r0-8dca6697.3.0.dev.so libopenblas.so.0)`

solved perfectly,thx.
