### ISSUE TITLE
run failed when the size of corpus is larger than 10000

### ISSUE THREAD

**Issue by qiuhuiGithub** [MontrealCorpusTools/Montreal-Forced-Aligner#99]
I run Montreal-Forced-Aligner on the windows OS, when the size of corpus is smaller than 10000, its OK. But when the size is 13000, is throw a exception:  Failed to open script file 'C:\Users\XX\Documents\MFA\wav\corpus_data\subset_10000\features_mfcc_cmvn_lda_fmllr.0.scp', But I find the file is in MFA\wav\corpus_data\split1! What's wrong?

**Comment by yevgenm** [comment]
I'm having the exact same issue on Linux.

**Comment by qiuhuiGithub** [comment]
> I'm having the exact same issue on Linux.

I solve the problem by replacing all 10000 into a larger number, such as 30000, so it won't create subset_10000 folder, and it works fine, hope it can help you.

**Comment by zhbbupt** [comment]
I  got the same problem. Could anybody fix this bugs?

**Comment by yevgenm** [comment]
I've commented out lines 132-133 in ./aligner/trainers/base.py:
https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/5324f0b61a3d7c4061f14c2f6f83fa02141bef0e/aligner/trainers/base.py#L132-L133

Which fixed it for me.
